export const SENTINEL_LABELS: Record<string, string> = {
  '': 'Any',
  'ALL': 'All',
  'all': 'All',
  'ANYWHERE': 'Anywhere',
};

export const COUNTRY_LABELS: Record<string, string> = {
  'ad': 'Andorra',
  'ae': 'United Arab Emirates',
  'af': 'Afghanistan',
  'ag': 'Antigua & Barbuda',
  'ai': 'Anguilla',
  'al': 'Albania',
  'am': 'Armenia',
  'an': 'Curaçao',
  'ao': 'Angola',
  'aq': 'Antarctica',
  'ar': 'Argentina',
  'as': 'American Samoa',
  'at': 'Austria',
  'au': 'Australia',
  'aw': 'Aruba',
  'ax': 'Åland Islands',
  'az': 'Azerbaijan',
  'ba': 'Bosnia & Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Belgium',
  'bf': 'Burkina Faso',
  'bg': 'Bulgaria',
  'bh': 'Bahrain',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bl': 'St. Barthélemy',
  'bm': 'Bermuda',
  'bn': 'Brunei',
  'bo': 'Bolivia',
  'bq': 'Caribbean Netherlands',
  'br': 'Brazil',
  'bs': 'Bahamas',
  'bt': 'Bhutan',
  'bv': 'Bouvet Island',
  'bw': 'Botswana',
  'by': 'Belarus',
  'bz': 'Belize',
  'ca': 'Canada',
  'cb': 'Caribbean Nations',
  'cc': 'Cocos (Keeling) Islands',
  'cd': 'Congo - Kinshasa',
  'cf': 'Central African Republic',
  'cg': 'Congo - Brazzaville',
  'ch': 'Switzerland',
  'ci': 'Côte d’Ivoire',
  'ck': 'Cook Islands',
  'cl': 'Chile',
  'cm': 'Cameroon',
  'cn': 'China',
  'co': 'Colombia',
  'cr': 'Costa Rica',
  'cs': 'Serbia',
  'cu': 'Cuba',
  'cv': 'Cape Verde',
  'cw': 'Curaçao',
  'cx': 'Christmas Island',
  'cy': 'Cyprus',
  'cz': 'Czechia',
  'de': 'Germany',
  'dj': 'Djibouti',
  'dk': 'Denmark',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'dz': 'Algeria',
  'ec': 'Ecuador',
  'ee': 'Estonia',
  'eg': 'Egypt',
  'eh': 'Western Sahara',
  'er': 'Eritrea',
  'es': 'Spain',
  'et': 'Ethiopia',
  'fi': 'Finland',
  'fj': 'Fiji',
  'fk': 'Falkland Islands',
  'fm': 'Micronesia',
  'fo': 'Faroe Islands',
  'fr': 'France',
  'ga': 'Gabon',
  'gb': 'United Kingdom (gb)',
  'gd': 'Grenada',
  'ge': 'Georgia',
  'gf': 'French Guiana',
  'gg': 'Guernsey',
  'gh': 'Ghana',
  'gi': 'Gibraltar',
  'gl': 'Greenland',
  'gm': 'Gambia',
  'gn': 'Guinea',
  'gp': 'Guadeloupe',
  'gq': 'Equatorial Guinea',
  'gr': 'Greece',
  'gs': 'South Georgia & South Sandwich Islands',
  'gt': 'Guatemala',
  'gu': 'Guam',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'hk': 'Hong Kong SAR China',
  'hm': 'Heard & McDonald Islands',
  'hn': 'Honduras',
  'hr': 'Croatia',
  'ht': 'Haiti',
  'hu': 'Hungary',
  'ic': 'Canary Islands',
  'id': 'Indonesia',
  'ie': 'Ireland',
  'il': 'Israel',
  'im': 'Isle of Man',
  'in': 'India',
  'io': 'British Indian Ocean Territory',
  'iq': 'Iraq',
  'ir': 'Iran',
  'is': 'Iceland',
  'it': 'Italy',
  'je': 'Jersey',
  'jm': 'Jamaica',
  'jo': 'Jordan',
  'jp': 'Japan',
  'ke': 'Kenya',
  'kg': 'Kyrgyzstan',
  'kh': 'Cambodia',
  'ki': 'Kiribati',
  'km': 'Comoros',
  'kn': 'St. Kitts & Nevis',
  'ko': 'Kosovo',
  'kp': 'North Korea',
  'kr': 'South Korea',
  'kw': 'Kuwait',
  'ky': 'Cayman Islands',
  'kz': 'Kazakhstan',
  'la': 'Laos',
  'lb': 'Lebanon',
  'lc': 'St. Lucia',
  'li': 'Liechtenstein',
  'lk': 'Sri Lanka',
  'lr': 'Liberia',
  'ls': 'Lesotho',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'lv': 'Latvia',
  'ly': 'Libya',
  'ma': 'Morocco',
  'mc': 'Monaco',
  'md': 'Moldova',
  'me': 'Montenegro',
  'mf': 'St. Martin',
  'mg': 'Madagascar',
  'mh': 'Marshall Islands',
  'mk': 'North Macedonia',
  'ml': 'Mali',
  'mm': 'Myanmar (Burma)',
  'mn': 'Mongolia',
  'mo': 'Macao SAR China',
  'mp': 'Northern Mariana Islands',
  'mq': 'Martinique',
  'mr': 'Mauritania',
  'ms': 'Montserrat',
  'mt': 'Malta',
  'mu': 'Mauritius',
  'mv': 'Maldives',
  'mw': 'Malawi',
  'mx': 'Mexico',
  'my': 'Malaysia',
  'mz': 'Mozambique',
  'na': 'Namibia',
  'nc': 'New Caledonia',
  'ne': 'Niger',
  'nf': 'Norfolk Island',
  'ng': 'Nigeria',
  'ni': 'Nicaragua',
  'nl': 'Netherlands',
  'no': 'Norway',
  'np': 'Nepal',
  'nr': 'Nauru',
  'nu': 'Niue',
  'nz': 'New Zealand',
  'om': 'Oman',
  'pa': 'Panama',
  'pe': 'Peru',
  'pf': 'French Polynesia',
  'pg': 'Papua New Guinea',
  'ph': 'Philippines',
  'pk': 'Pakistan',
  'pl': 'Poland',
  'pm': 'St. Pierre & Miquelon',
  'pn': 'Pitcairn Islands',
  'pr': 'Puerto Rico',
  'ps': 'Palestinian Territories',
  'pt': 'Portugal',
  'pw': 'Palau',
  'py': 'Paraguay',
  'qa': 'Qatar',
  're': 'Réunion',
  'ro': 'Romania',
  'rs': 'Serbia',
  'ru': 'Russia',
  'rw': 'Rwanda',
  'sa': 'Saudi Arabia',
  'sb': 'Solomon Islands',
  'sc': 'Seychelles',
  'sd': 'Sudan',
  'se': 'Sweden',
  'sg': 'Singapore',
  'sh': 'St. Helena',
  'si': 'Slovenia',
  'sj': 'Svalbard & Jan Mayen',
  'sk': 'Slovakia',
  'sl': 'Sierra Leone',
  'sm': 'San Marino',
  'sn': 'Senegal',
  'so': 'Somalia',
  'sr': 'Suriname',
  'ss': 'South Sudan',
  'st': 'São Tomé & Príncipe',
  'sv': 'El Salvador',
  'sx': 'Sint Maarten',
  'sy': 'Syria',
  'sz': 'Eswatini',
  'tc': 'Turks & Caicos Islands',
  'td': 'Chad',
  'tf': 'French Southern Territories',
  'tg': 'Togo',
  'th': 'Thailand',
  'tj': 'Tajikistan',
  'tk': 'Tokelau',
  'tl': 'Timor-Leste',
  'tm': 'Turkmenistan',
  'tn': 'Tunisia',
  'to': 'Tonga',
  'tp': 'Timor-Leste',
  'tr': 'Türkiye',
  'tt': 'Trinidad & Tobago',
  'tv': 'Tuvalu',
  'tw': 'Taiwan',
  'tz': 'Tanzania',
  'ua': 'Ukraine',
  'ug': 'Uganda',
  'uk': 'United Kingdom (uk)',
  'um': 'U.S. Outlying Islands',
  'us': 'United States',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  'va': 'Vatican City',
  'vc': 'St. Vincent & Grenadines',
  've': 'Venezuela',
  'vg': 'British Virgin Islands',
  'vi': 'U.S. Virgin Islands',
  'vn': 'Vietnam',
  'vu': 'Vanuatu',
  'wf': 'Wallis & Futuna',
  'ws': 'Samoa',
  'xk': 'Kosovo',
  'ye': 'Yemen',
  'yt': 'Mayotte',
  'yu': 'Serbia',
  'za': 'South Africa',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
};

export const LANGUAGE_LABELS: Record<string, string> = {
  'aa': 'Afar',
  'ab': 'Abkhazian',
  'ach': 'Acoli',
  'acm': 'Mesopotamian Arabic',
  'ae': 'Avestan',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'Amharic',
  'an': 'Aragonese',
  'apc': 'Levantine Arabic',
  'ar': 'Arabic',
  'arb': 'Arabic',
  'ars': 'Najdi Arabic',
  'ary': 'Moroccan Arabic',
  'arz': 'Egyptian Arabic',
  'as': 'Assamese',
  'av': 'Avaric',
  'ay': 'Aymara',
  'az': 'Azerbaijani',
  'ba': 'Bashkir',
  'be': 'Belarusian',
  'bem': 'Bemba',
  'bg': 'Bulgarian',
  'bh': 'Bhojpuri',
  'bho': 'Bhojpuri',
  'bi': 'Bislama',
  'bl': 'Bangla',
  'bm': 'Bambara',
  'bn': 'Bangla',
  'bo': 'Tibetan',
  'br': 'Breton',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'cb': 'Sorani Kurdish',
  'ce': 'Chechen',
  'ceb': 'Cebuano',
  'ch': 'Chamorro',
  'chr': 'Cherokee',
  'ci': 'Sicilian',
  'ck': 'Cherokee',
  'ckb': 'Central Kurdish',
  'cmn': 'Chinese',
  'co': 'Corsican',
  'cr': 'Cree',
  'crs': 'Seselwa Creole French',
  'cs': 'Czech',
  'cu': 'Church Slavic',
  'cv': 'Chuvash',
  'cx': 'Cebuano',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'dr': 'Dari',
  'dv': 'Divehi',
  'dz': 'Dzongkha',
  'ee': 'Ewe',
  'el': 'Greek',
  'en': 'English',
  'en-gb': 'British English',
  'en-in': 'English (India)',
  'en-us': 'American English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'es-419': 'Latin American Spanish',
  'es-us': 'Spanish (United States)',
  'et': 'Estonian',
  'eu': 'Basque',
  'fa': 'Persian',
  'ff': 'Fula',
  'fi': 'Finnish',
  'fil': 'Filipino',
  'fj': 'Fijian',
  'fo': 'Faroese',
  'fr': 'French',
  'fr-ca': 'Canadian French',
  'fy': 'Western Frisian',
  'ga': 'Irish',
  'gaa': 'Ga',
  'gd': 'Scottish Gaelic',
  'gl': 'Galician',
  'gn': 'Guarani',
  'gu': 'Gujarati',
  'gv': 'Manx',
  'ha': 'Hausa',
  'hak-tw': 'Hakka Chinese (Taiwan)',
  'haw': 'Hawaiian',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hmn': 'Hmong',
  'ho': 'Hiri Motu',
  'hr': 'Croatian',
  'ht': 'Haitian Creole',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'hz': 'Herero',
  'ia': 'Interlingua',
  'id': 'Indonesian',
  'ie': 'Interlingue',
  'ig': 'Igbo',
  'ii': 'Sichuan Yi',
  'ik': 'Inupiaq',
  'io': 'Ido',
  'is': 'Icelandic',
  'it': 'Italian',
  'iu': 'Inuktitut',
  'iw': 'Hebrew',
  'ja': 'Japanese',
  'jp': 'Japanese',
  'jv': 'Javanese',
  'jw': 'Javanese',
  'ka': 'Georgian',
  'kg': 'Kongo',
  'ki': 'Kikuyu',
  'kj': 'Kuanyama',
  'kk': 'Kazakh',
  'kl': 'Kalaallisut',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'kr': 'Kanuri',
  'kri': 'Krio',
  'ks': 'Kashmiri',
  'ku': 'Kurdish',
  'kv': 'Komi',
  'kw': 'Cornish',
  'ky': 'Kyrgyz',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lg': 'Ganda',
  'li': 'Limburgish',
  'ln': 'Lingala',
  'lo': 'Lao',
  'loz': 'Lozi',
  'lt': 'Lithuanian',
  'lu': 'Luba-Katanga',
  'lua': 'Luba-Lulua',
  'lv': 'Latvian',
  'mfe': 'Morisyen',
  'mg': 'Malagasy',
  'mh': 'Marshallese',
  'mi': 'Māori',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mo': 'Romanian',
  'mos': 'Mossi',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'mv': 'Maldivian',
  'my': 'Burmese',
  'na': 'Nauru',
  'nan-tw': 'Min Nan Chinese (Taiwan)',
  'nb': 'Norwegian Bokmål',
  'nd': 'North Ndebele',
  'ne': 'Nepali',
  'ng': 'Ndonga',
  'nl': 'Dutch',
  'nn': 'Norwegian Nynorsk',
  'no': 'Norwegian',
  'nr': 'South Ndebele',
  'ns': 'Northern Sotho',
  'nso': 'Northern Sotho',
  'nv': 'Navajo',
  'ny': 'Nyanja',
  'nyn': 'Nyankole',
  'oc': 'Occitan',
  'oj': 'Ojibwa',
  'om': 'Oromo',
  'or': 'Odia',
  'os': 'Ossetic',
  'pa': 'Punjabi',
  'pcm': 'Nigerian Pidgin',
  'pi': 'Pali',
  'pl': 'Polish',
  'ps': 'Pashto',
  'pt': 'Portuguese',
  'pt-br': 'Brazilian Portuguese',
  'pt-pt': 'European Portuguese',
  'qu': 'Quechua',
  'rm': 'Romansh',
  'rn': 'Rundi',
  'ro': 'Romanian',
  'ru': 'Russian',
  'rw': 'Kinyarwanda',
  'ry': 'Rusyn',
  'sa': 'Sanskrit',
  'sc': 'Sardinian',
  'sd': 'Sindhi',
  'se': 'Northern Sami',
  'sg': 'Sango',
  'sh': 'Serbian (Latin)',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sm': 'Samoan',
  'sn': 'Shona',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'sr-latn': 'Serbian (Latin)',
  'sr-me': 'Montenegrin',
  'ss': 'Swati',
  'st': 'Southern Sotho',
  'su': 'Sundanese',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'sy': 'Syriac',
  'sz': 'Silesian',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'th': 'Thai',
  'ti': 'Tigrinya',
  'tk': 'Turkmen',
  'tl': 'Filipino',
  'tn': 'Tswana',
  'to': 'Tongan',
  'tpi': 'Tok Pisin',
  'tr': 'Turkish',
  'ts': 'Tsonga',
  'tt': 'Tatar',
  'tum': 'Tumbuka',
  'tw': 'Akan',
  'ty': 'Tahitian',
  'tz': 'Tamazight',
  'ug': 'Uyghur',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  've': 'Venda',
  'vi': 'Vietnamese',
  'vo': 'Volapük',
  'vu': 'Vanuatu',
  'wa': 'Walloon',
  'wo': 'Wolof',
  'wy': 'Waray',
  'xh': 'Xhosa',
  'xx': 'Unknown',
  'xx-bork': 'xx (Bork)',
  'xx-elmer': 'xx (ELMER)',
  'xx-hacker': 'xx (HACKER)',
  'xx-klingon': 'xx (KLINGON)',
  'xx-pirate': 'xx (PIRATE)',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'yue': 'Cantonese',
  'za': 'Zhuang',
  'zh': 'Chinese',
  'zh-cn': 'Chinese (China)',
  'zh-hans': 'Simplified Chinese',
  'zh-hant': 'Traditional Chinese',
  'zh-hk': 'Chinese (Hong Kong SAR China)',
  'zh-sg': 'Chinese (Singapore)',
  'zh-tw': 'Chinese (Taiwan)',
  'zu': 'Zulu',
  'zz': 'Zazaki',
};

export const CURRENCY_LABELS: Record<string, string> = {
  'aed': 'United Arab Emirates Dirham',
  'all': 'Albanian Lek',
  'amd': 'Armenian Dram',
  'ars': 'Argentine Peso',
  'aud': 'Australian Dollar',
  'awg': 'Aruban Florin',
  'azn': 'Azerbaijani Manat',
  'bam': 'Bosnia-Herzegovina Convertible Mark',
  'bgn': 'Bulgarian Lev',
  'bhd': 'Bahraini Dinar',
  'bmd': 'Bermudan Dollar',
  'brl': 'Brazilian Real',
  'bsd': 'Bahamian Dollar',
  'byn': 'Belarusian Ruble',
  'cad': 'Canadian Dollar',
  'chf': 'Swiss Franc',
  'clp': 'Chilean Peso',
  'cny': 'Chinese Yuan',
  'cop': 'Colombian Peso',
  'crc': 'Costa Rican Colón',
  'cup': 'Cuban Peso',
  'czk': 'Czech Koruna',
  'dkk': 'Danish Krone',
  'dop': 'Dominican Peso',
  'dzd': 'Algerian Dinar',
  'egp': 'Egyptian Pound',
  'eur': 'Euro',
  'gbp': 'British Pound',
  'gel': 'Georgian Lari',
  'hkd': 'Hong Kong Dollar',
  'huf': 'Hungarian Forint',
  'idr': 'Indonesian Rupiah',
  'ils': 'Israeli New Shekel',
  'inr': 'Indian Rupee',
  'irr': 'Iranian Rial',
  'isk': 'Icelandic Króna',
  'jmd': 'Jamaican Dollar',
  'jod': 'Jordanian Dinar',
  'jpy': 'Japanese Yen',
  'krw': 'South Korean Won',
  'kwd': 'Kuwaiti Dinar',
  'kzt': 'Kazakhstani Tenge',
  'lbp': 'Lebanese Pound',
  'mad': 'Moroccan Dirham',
  'mdl': 'Moldovan Leu',
  'mkd': 'Macedonian Denar',
  'mxn': 'Mexican Peso',
  'myr': 'Malaysian Ringgit',
  'nok': 'Norwegian Krone',
  'nzd': 'New Zealand Dollar',
  'omr': 'Omani Rial',
  'pab': 'Panamanian Balboa',
  'pen': 'Peruvian Sol',
  'php': 'Philippine Peso',
  'pkr': 'Pakistani Rupee',
  'pln': 'Polish Zloty',
  'qar': 'Qatari Riyal',
  'ron': 'Romanian Leu',
  'rsd': 'Serbian Dinar',
  'rub': 'Russian Ruble',
  'sar': 'Saudi Riyal',
  'sek': 'Swedish Krona',
  'sgd': 'Singapore Dollar',
  'thb': 'Thai Baht',
  'try': 'Turkish Lira',
  'twd': 'New Taiwan Dollar',
  'uah': 'Ukrainian Hryvnia',
  'usd': 'US Dollar',
  'vnd': 'Vietnamese Dong',
  'xpf': 'CFP Franc',
  'zar': 'South African Rand',
};

export const LOCALE_LABELS: Record<string, string> = {
  'ar-es': 'Argentina (Spanish)',
  'at-de': 'Austria (German)',
  'au-en': 'Australia (English)',
  'be-fr': 'Belgium (French)',
  'be-nl': 'Belgium (Dutch)',
  'bg-bg': 'Bulgaria (Bulgarian)',
  'br-pt': 'Brazil (Portuguese)',
  'ca-en': 'Canada (English)',
  'ca-fr': 'Canada (French)',
  'ch-de': 'Switzerland (German)',
  'ch-fr': 'Switzerland (French)',
  'ch-it': 'Switzerland (Italian)',
  'cl-es': 'Chile (Spanish)',
  'cn-zh': 'China (Chinese)',
  'co-es': 'Colombia (Spanish)',
  'ct-ca': 'Catalonia (Catalan)',
  'cz-cs': 'Czech Republic (Czech)',
  'de-de': 'Germany (German)',
  'dk-da': 'Denmark (Danish)',
  'ee-et': 'Estonia (Estonian)',
  'es-es': 'Spain (Spanish)',
  'fi-fi': 'Finland (Finnish)',
  'fr-fr': 'France (French)',
  'gr-el': 'Greece (Greek)',
  'hk-tzh': 'Hong Kong (Chinese)',
  'hr-hr': 'Croatia (Croatian)',
  'hu-hu': 'Hungary (Hungarian)',
  'id-en': 'Indonesia (English)',
  'id-id': 'Indonesia (Indonesian)',
  'ie-en': 'Ireland (English)',
  'il-he': 'Israel (Hebrew)',
  'in-en': 'India (English)',
  'it-it': 'Italy (Italian)',
  'jp-jp': 'Japan (Japanese)',
  'kr-kr': 'Korea (Korean)',
  'lt-lt': 'Lithuania (Lithuanian)',
  'lv-lv': 'Latvia (Latvian)',
  'mx-es': 'Mexico (Spanish)',
  'my-en': 'Malaysia (English)',
  'my-ms': 'Malaysia (Malay)',
  'nl-nl': 'Netherlands (Dutch)',
  'no-no': 'Norway (Norwegian)',
  'nz-en': 'New Zealand (English)',
  'pe-es': 'Peru (Spanish)',
  'ph-en': 'Philippines (English)',
  'ph-tl': 'Philippines (Tagalog)',
  'pl-pl': 'Poland (Polish)',
  'pt-pt': 'Portugal (Portuguese)',
  'ro-ro': 'Romania (Romanian)',
  'ru-ru': 'Russia (Russian)',
  'se-sv': 'Sweden (Swedish)',
  'sg-en': 'Singapore (English)',
  'sk-sk': 'Slovak Republic (Slovak)',
  'sl-sl': 'Slovenia (Slovenian)',
  'th-th': 'Thailand (Thai)',
  'tr-tr': 'Turkey (Turkish)',
  'tw-tzh': 'Taiwan (Chinese)',
  'ua-uk': 'Ukraine (Ukrainian)',
  'ue-es': 'United States (Spanish)',
  'uk-en': 'United Kingdom (English)',
  'us-en': 'United States (English)',
  've-es': 'Venezuela (Spanish)',
  'vn-vi': 'Vietnam (Vietnamese)',
  'wt-wt': 'No Region',
  'xa-ar': 'Arabia (Arabic)',
  'xa-en': 'Arabia (English)',
  'xl-es': 'Latin America (Spanish)',
  'za-en': 'South Africa (English)',
};
