import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_ads_transparency_center'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Ads Transparency Center',
  value: 'google_ads_transparency_center'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Params',
    name: 'search_params',
    type: 'collection',
    placeholder: 'Add Search Params',
    default: {},
    options: [
      {
        displayName: 'Advertiser ID (advertiser_id)',
        name: 'advertiser_id',
        type: 'string',
        default: '',
        description: 'Specifies the advertiser\'s unique ID. Multiple IDs can be provided, separated by commas. Required if domain is not provided.',
        routing: {
          request: {
            qs: {
              advertiser_id: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Domain (domain)',
        name: 'domain',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Google.ad', value: 'google.ad' },
          { name: 'Google.ae', value: 'google.ae' },
          { name: 'Google.al', value: 'google.al' },
          { name: 'Google.am', value: 'google.am' },
          { name: 'Google.as', value: 'google.as' },
          { name: 'Google.at', value: 'google.at' },
          { name: 'Google.az', value: 'google.az' },
          { name: 'Google.ba', value: 'google.ba' },
          { name: 'Google.be', value: 'google.be' },
          { name: 'Google.bf', value: 'google.bf' },
          { name: 'Google.bg', value: 'google.bg' },
          { name: 'Google.bi', value: 'google.bi' },
          { name: 'Google.bj', value: 'google.bj' },
          { name: 'Google.bs', value: 'google.bs' },
          { name: 'Google.bt', value: 'google.bt' },
          { name: 'Google.by', value: 'google.by' },
          { name: 'Google.ca', value: 'google.ca' },
          { name: 'Google.cat', value: 'google.cat' },
          { name: 'Google.cd', value: 'google.cd' },
          { name: 'Google.cf', value: 'google.cf' },
          { name: 'Google.cg', value: 'google.cg' },
          { name: 'Google.ch', value: 'google.ch' },
          { name: 'Google.ci', value: 'google.ci' },
          { name: 'Google.cl', value: 'google.cl' },
          { name: 'Google.cm', value: 'google.cm' },
          { name: 'Google.co.ao', value: 'google.co.ao' },
          { name: 'Google.co.bw', value: 'google.co.bw' },
          { name: 'Google.co.ck', value: 'google.co.ck' },
          { name: 'Google.co.cr', value: 'google.co.cr' },
          { name: 'Google.co.id', value: 'google.co.id' },
          { name: 'Google.co.il', value: 'google.co.il' },
          { name: 'Google.co.in', value: 'google.co.in' },
          { name: 'Google.co.jp', value: 'google.co.jp' },
          { name: 'Google.co.ke', value: 'google.co.ke' },
          { name: 'Google.co.kr', value: 'google.co.kr' },
          { name: 'Google.co.ls', value: 'google.co.ls' },
          { name: 'Google.co.ma', value: 'google.co.ma' },
          { name: 'Google.co.mz', value: 'google.co.mz' },
          { name: 'Google.co.nz', value: 'google.co.nz' },
          { name: 'Google.co.th', value: 'google.co.th' },
          { name: 'Google.co.tz', value: 'google.co.tz' },
          { name: 'Google.co.ug', value: 'google.co.ug' },
          { name: 'Google.co.uk', value: 'google.co.uk' },
          { name: 'Google.co.uz', value: 'google.co.uz' },
          { name: 'Google.co.ve', value: 'google.co.ve' },
          { name: 'Google.co.vi', value: 'google.co.vi' },
          { name: 'Google.co.za', value: 'google.co.za' },
          { name: 'Google.co.zm', value: 'google.co.zm' },
          { name: 'Google.co.zw', value: 'google.co.zw' },
          { name: 'Google.com', value: 'google.com' },
          { name: 'Google.com.af', value: 'google.com.af' },
          { name: 'Google.com.ag', value: 'google.com.ag' },
          { name: 'Google.com.ai', value: 'google.com.ai' },
          { name: 'Google.com.ar', value: 'google.com.ar' },
          { name: 'Google.com.au', value: 'google.com.au' },
          { name: 'Google.com.bd', value: 'google.com.bd' },
          { name: 'Google.com.bh', value: 'google.com.bh' },
          { name: 'Google.com.bn', value: 'google.com.bn' },
          { name: 'Google.com.bo', value: 'google.com.bo' },
          { name: 'Google.com.br', value: 'google.com.br' },
          { name: 'Google.com.bz', value: 'google.com.bz' },
          { name: 'Google.com.co', value: 'google.com.co' },
          { name: 'Google.com.cu', value: 'google.com.cu' },
          { name: 'Google.com.cy', value: 'google.com.cy' },
          { name: 'Google.com.do', value: 'google.com.do' },
          { name: 'Google.com.ec', value: 'google.com.ec' },
          { name: 'Google.com.eg', value: 'google.com.eg' },
          { name: 'Google.com.et', value: 'google.com.et' },
          { name: 'Google.com.fj', value: 'google.com.fj' },
          { name: 'Google.com.gh', value: 'google.com.gh' },
          { name: 'Google.com.gi', value: 'google.com.gi' },
          { name: 'Google.com.gt', value: 'google.com.gt' },
          { name: 'Google.com.hk', value: 'google.com.hk' },
          { name: 'Google.com.jm', value: 'google.com.jm' },
          { name: 'Google.com.kh', value: 'google.com.kh' },
          { name: 'Google.com.kw', value: 'google.com.kw' },
          { name: 'Google.com.lb', value: 'google.com.lb' },
          { name: 'Google.com.ly', value: 'google.com.ly' },
          { name: 'Google.com.mm', value: 'google.com.mm' },
          { name: 'Google.com.mt', value: 'google.com.mt' },
          { name: 'Google.com.mx', value: 'google.com.mx' },
          { name: 'Google.com.my', value: 'google.com.my' },
          { name: 'Google.com.na', value: 'google.com.na' },
          { name: 'Google.com.ng', value: 'google.com.ng' },
          { name: 'Google.com.ni', value: 'google.com.ni' },
          { name: 'Google.com.np', value: 'google.com.np' },
          { name: 'Google.com.om', value: 'google.com.om' },
          { name: 'Google.com.pa', value: 'google.com.pa' },
          { name: 'Google.com.pe', value: 'google.com.pe' },
          { name: 'Google.com.pg', value: 'google.com.pg' },
          { name: 'Google.com.ph', value: 'google.com.ph' },
          { name: 'Google.com.pk', value: 'google.com.pk' },
          { name: 'Google.com.pr', value: 'google.com.pr' },
          { name: 'Google.com.py', value: 'google.com.py' },
          { name: 'Google.com.qa', value: 'google.com.qa' },
          { name: 'Google.com.sa', value: 'google.com.sa' },
          { name: 'Google.com.sb', value: 'google.com.sb' },
          { name: 'Google.com.sg', value: 'google.com.sg' },
          { name: 'Google.com.sl', value: 'google.com.sl' },
          { name: 'Google.com.sv', value: 'google.com.sv' },
          { name: 'Google.com.tj', value: 'google.com.tj' },
          { name: 'Google.com.tr', value: 'google.com.tr' },
          { name: 'Google.com.tw', value: 'google.com.tw' },
          { name: 'Google.com.ua', value: 'google.com.ua' },
          { name: 'Google.com.uy', value: 'google.com.uy' },
          { name: 'Google.com.vc', value: 'google.com.vc' },
          { name: 'Google.com.vn', value: 'google.com.vn' },
          { name: 'Google.cv', value: 'google.cv' },
          { name: 'Google.cz', value: 'google.cz' },
          { name: 'Google.de', value: 'google.de' },
          { name: 'Google.dj', value: 'google.dj' },
          { name: 'Google.dk', value: 'google.dk' },
          { name: 'Google.dm', value: 'google.dm' },
          { name: 'Google.dz', value: 'google.dz' },
          { name: 'Google.ee', value: 'google.ee' },
          { name: 'Google.es', value: 'google.es' },
          { name: 'Google.fi', value: 'google.fi' },
          { name: 'Google.fm', value: 'google.fm' },
          { name: 'Google.fr', value: 'google.fr' },
          { name: 'Google.ga', value: 'google.ga' },
          { name: 'Google.ge', value: 'google.ge' },
          { name: 'Google.gg', value: 'google.gg' },
          { name: 'Google.gl', value: 'google.gl' },
          { name: 'Google.gm', value: 'google.gm' },
          { name: 'Google.gp', value: 'google.gp' },
          { name: 'Google.gr', value: 'google.gr' },
          { name: 'Google.gy', value: 'google.gy' },
          { name: 'Google.hn', value: 'google.hn' },
          { name: 'Google.hr', value: 'google.hr' },
          { name: 'Google.ht', value: 'google.ht' },
          { name: 'Google.hu', value: 'google.hu' },
          { name: 'Google.ie', value: 'google.ie' },
          { name: 'Google.im', value: 'google.im' },
          { name: 'Google.iq', value: 'google.iq' },
          { name: 'Google.is', value: 'google.is' },
          { name: 'Google.it', value: 'google.it' },
          { name: 'Google.je', value: 'google.je' },
          { name: 'Google.jo', value: 'google.jo' },
          { name: 'Google.kg', value: 'google.kg' },
          { name: 'Google.ki', value: 'google.ki' },
          { name: 'Google.kz', value: 'google.kz' },
          { name: 'Google.la', value: 'google.la' },
          { name: 'Google.li', value: 'google.li' },
          { name: 'Google.lk', value: 'google.lk' },
          { name: 'Google.lt', value: 'google.lt' },
          { name: 'Google.lu', value: 'google.lu' },
          { name: 'Google.lv', value: 'google.lv' },
          { name: 'Google.md', value: 'google.md' },
          { name: 'Google.me', value: 'google.me' },
          { name: 'Google.mg', value: 'google.mg' },
          { name: 'Google.mk', value: 'google.mk' },
          { name: 'Google.ml', value: 'google.ml' },
          { name: 'Google.mn', value: 'google.mn' },
          { name: 'Google.ms', value: 'google.ms' },
          { name: 'Google.mu', value: 'google.mu' },
          { name: 'Google.mv', value: 'google.mv' },
          { name: 'Google.mw', value: 'google.mw' },
          { name: 'Google.ne', value: 'google.ne' },
          { name: 'Google.nl', value: 'google.nl' },
          { name: 'Google.no', value: 'google.no' },
          { name: 'Google.nr', value: 'google.nr' },
          { name: 'Google.nu', value: 'google.nu' },
          { name: 'Google.pl', value: 'google.pl' },
          { name: 'Google.pn', value: 'google.pn' },
          { name: 'Google.ps', value: 'google.ps' },
          { name: 'Google.pt', value: 'google.pt' },
          { name: 'Google.ro', value: 'google.ro' },
          { name: 'Google.rs', value: 'google.rs' },
          { name: 'Google.ru', value: 'google.ru' },
          { name: 'Google.rw', value: 'google.rw' },
          { name: 'Google.sc', value: 'google.sc' },
          { name: 'Google.se', value: 'google.se' },
          { name: 'Google.sh', value: 'google.sh' },
          { name: 'Google.si', value: 'google.si' },
          { name: 'Google.sk', value: 'google.sk' },
          { name: 'Google.sm', value: 'google.sm' },
          { name: 'Google.sn', value: 'google.sn' },
          { name: 'Google.so', value: 'google.so' },
          { name: 'Google.sr', value: 'google.sr' },
          { name: 'Google.st', value: 'google.st' },
          { name: 'Google.td', value: 'google.td' },
          { name: 'Google.tg', value: 'google.tg' },
          { name: 'Google.tk', value: 'google.tk' },
          { name: 'Google.tl', value: 'google.tl' },
          { name: 'Google.tm', value: 'google.tm' },
          { name: 'Google.tn', value: 'google.tn' },
          { name: 'Google.to', value: 'google.to' },
          { name: 'Google.tt', value: 'google.tt' },
          { name: 'Google.vg', value: 'google.vg' },
          { name: 'Google.vu', value: 'google.vu' },
          { name: 'Google.ws', value: 'google.ws' },
        ],
        default: '',
        description: 'Defines the advertiser\'s verified domain (e.g., tesla.com). Required if advertiser_id is not provided.',
        routing: {
          request: {
            qs: {
              domain: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Ad Format (ad_format)',
        name: 'ad_format',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Image', value: 'image' },
          { name: 'Text', value: 'text' },
          { name: 'Video', value: 'video' },
        ],
        default: '',
        description: 'Filters results based on ad format',
        routing: {
          request: {
            qs: {
              ad_format: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Platform (platform)',
        name: 'platform',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Google maps', value: 'google_maps' },
          { name: 'Google play', value: 'google_play' },
          { name: 'Google search', value: 'google_search' },
          { name: 'Google shopping', value: 'google_shopping' },
          { name: 'Youtube', value: 'youtube' },
        ],
        default: '',
        description: 'Specifies the platform for which the ads are being retrieved',
        routing: {
          request: {
            qs: {
              platform: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Region (region)',
        name: 'region',
        type: 'options',
        options: [
          { name: 'AD', value: 'AD' },
          { name: 'AE', value: 'AE' },
          { name: 'AG', value: 'AG' },
          { name: 'AI', value: 'AI' },
          { name: 'AL', value: 'AL' },
          { name: 'AM', value: 'AM' },
          { name: 'Any', value: '' },
          { name: 'Anywhere', value: 'ANYWHERE' },
          { name: 'AO', value: 'AO' },
          { name: 'AQ', value: 'AQ' },
          { name: 'AR', value: 'AR' },
          { name: 'AS', value: 'AS' },
          { name: 'AT', value: 'AT' },
          { name: 'AU', value: 'AU' },
          { name: 'AW', value: 'AW' },
          { name: 'AZ', value: 'AZ' },
          { name: 'BA', value: 'BA' },
          { name: 'BB', value: 'BB' },
          { name: 'BD', value: 'BD' },
          { name: 'BE', value: 'BE' },
          { name: 'BF', value: 'BF' },
          { name: 'BG', value: 'BG' },
          { name: 'BH', value: 'BH' },
          { name: 'BI', value: 'BI' },
          { name: 'BJ', value: 'BJ' },
          { name: 'BM', value: 'BM' },
          { name: 'BN', value: 'BN' },
          { name: 'BO', value: 'BO' },
          { name: 'BQ', value: 'BQ' },
          { name: 'BR', value: 'BR' },
          { name: 'BS', value: 'BS' },
          { name: 'BT', value: 'BT' },
          { name: 'BV', value: 'BV' },
          { name: 'BW', value: 'BW' },
          { name: 'BY', value: 'BY' },
          { name: 'BZ', value: 'BZ' },
          { name: 'CA', value: 'CA' },
          { name: 'CC', value: 'CC' },
          { name: 'CD', value: 'CD' },
          { name: 'CF', value: 'CF' },
          { name: 'CG', value: 'CG' },
          { name: 'CH', value: 'CH' },
          { name: 'CI', value: 'CI' },
          { name: 'CK', value: 'CK' },
          { name: 'CL', value: 'CL' },
          { name: 'CM', value: 'CM' },
          { name: 'CN', value: 'CN' },
          { name: 'CO', value: 'CO' },
          { name: 'CR', value: 'CR' },
          { name: 'CV', value: 'CV' },
          { name: 'CW', value: 'CW' },
          { name: 'CX', value: 'CX' },
          { name: 'CY', value: 'CY' },
          { name: 'CZ', value: 'CZ' },
          { name: 'DE', value: 'DE' },
          { name: 'DJ', value: 'DJ' },
          { name: 'DK', value: 'DK' },
          { name: 'DM', value: 'DM' },
          { name: 'DO', value: 'DO' },
          { name: 'DZ', value: 'DZ' },
          { name: 'EC', value: 'EC' },
          { name: 'EE', value: 'EE' },
          { name: 'EG', value: 'EG' },
          { name: 'EH', value: 'EH' },
          { name: 'ER', value: 'ER' },
          { name: 'ES', value: 'ES' },
          { name: 'ET', value: 'ET' },
          { name: 'FI', value: 'FI' },
          { name: 'FJ', value: 'FJ' },
          { name: 'FK', value: 'FK' },
          { name: 'FM', value: 'FM' },
          { name: 'FO', value: 'FO' },
          { name: 'FR', value: 'FR' },
          { name: 'GA', value: 'GA' },
          { name: 'GB', value: 'GB' },
          { name: 'GD', value: 'GD' },
          { name: 'GE', value: 'GE' },
          { name: 'GF', value: 'GF' },
          { name: 'GG', value: 'GG' },
          { name: 'GH', value: 'GH' },
          { name: 'GI', value: 'GI' },
          { name: 'GL', value: 'GL' },
          { name: 'GM', value: 'GM' },
          { name: 'GN', value: 'GN' },
          { name: 'GP', value: 'GP' },
          { name: 'GQ', value: 'GQ' },
          { name: 'GR', value: 'GR' },
          { name: 'GS', value: 'GS' },
          { name: 'GT', value: 'GT' },
          { name: 'GU', value: 'GU' },
          { name: 'GW', value: 'GW' },
          { name: 'GY', value: 'GY' },
          { name: 'HK', value: 'HK' },
          { name: 'HM', value: 'HM' },
          { name: 'HN', value: 'HN' },
          { name: 'HR', value: 'HR' },
          { name: 'HT', value: 'HT' },
          { name: 'HU', value: 'HU' },
          { name: 'IC', value: 'IC' },
          { name: 'ID', value: 'ID' },
          { name: 'IE', value: 'IE' },
          { name: 'IL', value: 'IL' },
          { name: 'IM', value: 'IM' },
          { name: 'IN', value: 'IN' },
          { name: 'IO', value: 'IO' },
          { name: 'IQ', value: 'IQ' },
          { name: 'IS', value: 'IS' },
          { name: 'IT', value: 'IT' },
          { name: 'JE', value: 'JE' },
          { name: 'JM', value: 'JM' },
          { name: 'JO', value: 'JO' },
          { name: 'JP', value: 'JP' },
          { name: 'KE', value: 'KE' },
          { name: 'KG', value: 'KG' },
          { name: 'KH', value: 'KH' },
          { name: 'KI', value: 'KI' },
          { name: 'KM', value: 'KM' },
          { name: 'KN', value: 'KN' },
          { name: 'KR', value: 'KR' },
          { name: 'KW', value: 'KW' },
          { name: 'KY', value: 'KY' },
          { name: 'KZ', value: 'KZ' },
          { name: 'LA', value: 'LA' },
          { name: 'LB', value: 'LB' },
          { name: 'LC', value: 'LC' },
          { name: 'LI', value: 'LI' },
          { name: 'LK', value: 'LK' },
          { name: 'LR', value: 'LR' },
          { name: 'LS', value: 'LS' },
          { name: 'LT', value: 'LT' },
          { name: 'LU', value: 'LU' },
          { name: 'LV', value: 'LV' },
          { name: 'LY', value: 'LY' },
          { name: 'MA', value: 'MA' },
          { name: 'MC', value: 'MC' },
          { name: 'MD', value: 'MD' },
          { name: 'ME', value: 'ME' },
          { name: 'MF', value: 'MF' },
          { name: 'MG', value: 'MG' },
          { name: 'MH', value: 'MH' },
          { name: 'MK', value: 'MK' },
          { name: 'ML', value: 'ML' },
          { name: 'MM', value: 'MM' },
          { name: 'MN', value: 'MN' },
          { name: 'MO', value: 'MO' },
          { name: 'MP', value: 'MP' },
          { name: 'MQ', value: 'MQ' },
          { name: 'MR', value: 'MR' },
          { name: 'MS', value: 'MS' },
          { name: 'MT', value: 'MT' },
          { name: 'MU', value: 'MU' },
          { name: 'MV', value: 'MV' },
          { name: 'MW', value: 'MW' },
          { name: 'MX', value: 'MX' },
          { name: 'MY', value: 'MY' },
          { name: 'MZ', value: 'MZ' },
          { name: 'NA', value: 'NA' },
          { name: 'NC', value: 'NC' },
          { name: 'NE', value: 'NE' },
          { name: 'NF', value: 'NF' },
          { name: 'NG', value: 'NG' },
          { name: 'NI', value: 'NI' },
          { name: 'NL', value: 'NL' },
          { name: 'NO', value: 'NO' },
          { name: 'NP', value: 'NP' },
          { name: 'NR', value: 'NR' },
          { name: 'NU', value: 'NU' },
          { name: 'NZ', value: 'NZ' },
          { name: 'OM', value: 'OM' },
          { name: 'PA', value: 'PA' },
          { name: 'PE', value: 'PE' },
          { name: 'PF', value: 'PF' },
          { name: 'PG', value: 'PG' },
          { name: 'PH', value: 'PH' },
          { name: 'PK', value: 'PK' },
          { name: 'PL', value: 'PL' },
          { name: 'PM', value: 'PM' },
          { name: 'PN', value: 'PN' },
          { name: 'PR', value: 'PR' },
          { name: 'PS', value: 'PS' },
          { name: 'PT', value: 'PT' },
          { name: 'PW', value: 'PW' },
          { name: 'PY', value: 'PY' },
          { name: 'QA', value: 'QA' },
          { name: 'RE', value: 'RE' },
          { name: 'RO', value: 'RO' },
          { name: 'RW', value: 'RW' },
          { name: 'SA', value: 'SA' },
          { name: 'SB', value: 'SB' },
          { name: 'SC', value: 'SC' },
          { name: 'SE', value: 'SE' },
          { name: 'SG', value: 'SG' },
          { name: 'SH', value: 'SH' },
          { name: 'SI', value: 'SI' },
          { name: 'SJ', value: 'SJ' },
          { name: 'SK', value: 'SK' },
          { name: 'SL', value: 'SL' },
          { name: 'SM', value: 'SM' },
          { name: 'SN', value: 'SN' },
          { name: 'SO', value: 'SO' },
          { name: 'SR', value: 'SR' },
          { name: 'ST', value: 'ST' },
          { name: 'SV', value: 'SV' },
          { name: 'SX', value: 'SX' },
          { name: 'SZ', value: 'SZ' },
          { name: 'TC', value: 'TC' },
          { name: 'TD', value: 'TD' },
          { name: 'TF', value: 'TF' },
          { name: 'TG', value: 'TG' },
          { name: 'TH', value: 'TH' },
          { name: 'TJ', value: 'TJ' },
          { name: 'TK', value: 'TK' },
          { name: 'TL', value: 'TL' },
          { name: 'TM', value: 'TM' },
          { name: 'TN', value: 'TN' },
          { name: 'TO', value: 'TO' },
          { name: 'TR', value: 'TR' },
          { name: 'TT', value: 'TT' },
          { name: 'TV', value: 'TV' },
          { name: 'TW', value: 'TW' },
          { name: 'TZ', value: 'TZ' },
          { name: 'UA', value: 'UA' },
          { name: 'UG', value: 'UG' },
          { name: 'UM', value: 'UM' },
          { name: 'US', value: 'US' },
          { name: 'UY', value: 'UY' },
          { name: 'UZ', value: 'UZ' },
          { name: 'VA', value: 'VA' },
          { name: 'VC', value: 'VC' },
          { name: 'VE', value: 'VE' },
          { name: 'VG', value: 'VG' },
          { name: 'VI', value: 'VI' },
          { name: 'VN', value: 'VN' },
          { name: 'VU', value: 'VU' },
          { name: 'WF', value: 'WF' },
          { name: 'WS', value: 'WS' },
          { name: 'YE', value: 'YE' },
          { name: 'YT', value: 'YT' },
          { name: 'ZA', value: 'ZA' },
          { name: 'ZM', value: 'ZM' },
          { name: 'ZW', value: 'ZW' },
        ],
        default: '',
        description: 'Specifies the region for your search. The default parameter is anywhere.',
        routing: {
          request: {
            qs: {
              region: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Last 30 days', value: 'last_30_days' },
          { name: 'Last 7 days', value: 'last_7_days' },
          { name: 'Today', value: 'today' },
          { name: 'Yesterday', value: 'yesterday' },
        ],
        default: '',
        description: 'Limits the results to a specific time range. Alternatively, specify a custom range using YYYY-MM-DD..YYYY-MM-DD.',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Next Page Token (next_page_token)',
        name: 'next_page_token',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        description: 'A token for fetching the next set of results. You can obtain this token from the next_page_token field in the previous response.',
        routing: {
          request: {
            qs: {
              next_page_token: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Results Per Page (num)',
        name: 'num',
        type: 'number',
        typeOptions: {
          minValue: 1,
          maxValue: 100,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Specifies the number of results to return. Default is 40. The maximum is 100.',
        routing: {
          request: {
            qs: {
              num: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_ads_transparency_center = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-ads-transparency-center-api',
};
