import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_shopping_filters'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Shopping Filters',
  value: 'google_shopping_filters'
};

const properties: INodeProperties[] = [
  {
    displayName: 'All Filters Token (all_filters_token)',
    name: 'all_filters_token',
    type: 'string',
    required: true,
    typeOptions: { password: true },
    default: '',
    description: 'A token that will be used to retrieve all filters data. The token is generated by the Google Shopping API.',
    displayOptions,
    routing: {
      request: {
        qs: {
          all_filters_token: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_shopping_filters = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-shopping-filters',
};
