import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_hotels_property'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Hotels Property',
  value: 'google_hotels_property'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Property Token (property_token)',
    name: 'property_token',
    type: 'string',
    required: true,
    typeOptions: { password: true },
    default: '',
    description: 'Parameter defines the property you want to search. You can find property_token values using Google Hotels API.',
    displayOptions,
    routing: {
      request: {
        qs: {
          property_token: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Check In Date (check_in_date)',
    name: 'check_in_date',
    type: 'string',
    required: true,
    default: '',
    description: 'Defines the check-in date for the hotel stay in the format YYYY-MM-DD. This date marks the beginning of the reservation.',
    displayOptions,
    routing: {
      request: {
        qs: {
          check_in_date: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Check Out Date (check_out_date)',
    name: 'check_out_date',
    type: 'string',
    required: true,
    default: '',
    description: 'The check-out date for the hotel stay in the format YYYY-MM-DD. This date marks the end of the reservation.',
    displayOptions,
    routing: {
      request: {
        qs: {
          check_out_date: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Currency (currency)',
        name: 'currency',
        type: 'options',
        options: [
          { name: 'Albanian Lek', value: 'ALL' },
          { name: 'Algerian Dinar', value: 'DZD' },
          { name: 'Argentine Peso', value: 'ARS' },
          { name: 'Armenian Dram', value: 'AMD' },
          { name: 'Aruban Florin', value: 'AWG' },
          { name: 'Australian Dollar', value: 'AUD' },
          { name: 'Azerbaijani Manat', value: 'AZN' },
          { name: 'Bahamian Dollar', value: 'BSD' },
          { name: 'Bahraini Dinar', value: 'BHD' },
          { name: 'Belarusian Ruble', value: 'BYN' },
          { name: 'Bermudan Dollar', value: 'BMD' },
          { name: 'Bosnia-Herzegovina Convertible Mark', value: 'BAM' },
          { name: 'Brazilian Real', value: 'BRL' },
          { name: 'British Pound', value: 'GBP' },
          { name: 'Bulgarian Lev', value: 'BGN' },
          { name: 'Canadian Dollar', value: 'CAD' },
          { name: 'CFP Franc', value: 'XPF' },
          { name: 'Chilean Peso', value: 'CLP' },
          { name: 'Chinese Yuan', value: 'CNY' },
          { name: 'Colombian Peso', value: 'COP' },
          { name: 'Costa Rican Colón', value: 'CRC' },
          { name: 'Cuban Peso', value: 'CUP' },
          { name: 'Czech Koruna', value: 'CZK' },
          { name: 'Danish Krone', value: 'DKK' },
          { name: 'Dominican Peso', value: 'DOP' },
          { name: 'Egyptian Pound', value: 'EGP' },
          { name: 'Euro', value: 'EUR' },
          { name: 'Georgian Lari', value: 'GEL' },
          { name: 'Hong Kong Dollar', value: 'HKD' },
          { name: 'Hungarian Forint', value: 'HUF' },
          { name: 'Icelandic Króna', value: 'ISK' },
          { name: 'Indian Rupee', value: 'INR' },
          { name: 'Indonesian Rupiah', value: 'IDR' },
          { name: 'Iranian Rial', value: 'IRR' },
          { name: 'Israeli New Shekel', value: 'ILS' },
          { name: 'Jamaican Dollar', value: 'JMD' },
          { name: 'Japanese Yen', value: 'JPY' },
          { name: 'Jordanian Dinar', value: 'JOD' },
          { name: 'Kazakhstani Tenge', value: 'KZT' },
          { name: 'Kuwaiti Dinar', value: 'KWD' },
          { name: 'Lebanese Pound', value: 'LBP' },
          { name: 'Macedonian Denar', value: 'MKD' },
          { name: 'Malaysian Ringgit', value: 'MYR' },
          { name: 'Mexican Peso', value: 'MXN' },
          { name: 'Moldovan Leu', value: 'MDL' },
          { name: 'Moroccan Dirham', value: 'MAD' },
          { name: 'New Taiwan Dollar', value: 'TWD' },
          { name: 'New Zealand Dollar', value: 'NZD' },
          { name: 'Norwegian Krone', value: 'NOK' },
          { name: 'Omani Rial', value: 'OMR' },
          { name: 'Pakistani Rupee', value: 'PKR' },
          { name: 'Panamanian Balboa', value: 'PAB' },
          { name: 'Peruvian Sol', value: 'PEN' },
          { name: 'Philippine Peso', value: 'PHP' },
          { name: 'Polish Zloty', value: 'PLN' },
          { name: 'Qatari Riyal', value: 'QAR' },
          { name: 'Romanian Leu', value: 'RON' },
          { name: 'Russian Ruble', value: 'RUB' },
          { name: 'Saudi Riyal', value: 'SAR' },
          { name: 'Serbian Dinar', value: 'RSD' },
          { name: 'Singapore Dollar', value: 'SGD' },
          { name: 'South African Rand', value: 'ZAR' },
          { name: 'South Korean Won', value: 'KRW' },
          { name: 'Swedish Krona', value: 'SEK' },
          { name: 'Swiss Franc', value: 'CHF' },
          { name: 'Thai Baht', value: 'THB' },
          { name: 'Turkish Lira', value: 'TRY' },
          { name: 'Ukrainian Hryvnia', value: 'UAH' },
          { name: 'United Arab Emirates Dirham', value: 'AED' },
          { name: 'US Dollar', value: 'USD' },
          { name: 'Vietnamese Dong', value: 'VND' },
        ],
        default: 'USD',
        description: 'Defines the currency of the returned prices. Default is USD. Check the full list of supported Google Travel currency values.',
        routing: {
          request: {
            qs: {
              currency: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'AF' },
          { name: 'Albania', value: 'AL' },
          { name: 'Algeria', value: 'DZ' },
          { name: 'American Samoa', value: 'AS' },
          { name: 'Andorra', value: 'AD' },
          { name: 'Angola', value: 'AO' },
          { name: 'Anguilla', value: 'AI' },
          { name: 'Antigua & Barbuda', value: 'AG' },
          { name: 'Any', value: '' },
          { name: 'Argentina', value: 'AR' },
          { name: 'Armenia', value: 'AM' },
          { name: 'Australia', value: 'AU' },
          { name: 'Austria', value: 'AT' },
          { name: 'Azerbaijan', value: 'AZ' },
          { name: 'Bahamas', value: 'BS' },
          { name: 'Bahrain', value: 'BH' },
          { name: 'Bangladesh', value: 'BD' },
          { name: 'Belarus', value: 'BY' },
          { name: 'Belgium', value: 'BE' },
          { name: 'Belize', value: 'BZ' },
          { name: 'Benin', value: 'BJ' },
          { name: 'Bhutan', value: 'BT' },
          { name: 'Bolivia', value: 'BO' },
          { name: 'Bosnia & Herzegovina', value: 'BA' },
          { name: 'Botswana', value: 'BW' },
          { name: 'Brazil', value: 'BR' },
          { name: 'British Virgin Islands', value: 'VG' },
          { name: 'Brunei', value: 'BN' },
          { name: 'Bulgaria', value: 'BG' },
          { name: 'Burkina Faso', value: 'BF' },
          { name: 'Burundi', value: 'BI' },
          { name: 'Cambodia', value: 'KH' },
          { name: 'Cameroon', value: 'CM' },
          { name: 'Canada', value: 'CA' },
          { name: 'Cape Verde', value: 'CV' },
          { name: 'Central African Republic', value: 'CF' },
          { name: 'Chad', value: 'TD' },
          { name: 'Chile', value: 'CL' },
          { name: 'China', value: 'CN' },
          { name: 'Colombia', value: 'CO' },
          { name: 'Congo - Brazzaville', value: 'CG' },
          { name: 'Congo - Kinshasa', value: 'CD' },
          { name: 'Cook Islands', value: 'CK' },
          { name: 'Costa Rica', value: 'CR' },
          { name: 'Côte d’Ivoire', value: 'CI' },
          { name: 'Croatia', value: 'HR' },
          { name: 'Cuba', value: 'CU' },
          { name: 'Cyprus', value: 'CY' },
          { name: 'Czechia', value: 'CZ' },
          { name: 'Denmark', value: 'DK' },
          { name: 'Djibouti', value: 'DJ' },
          { name: 'Dominica', value: 'DM' },
          { name: 'Dominican Republic', value: 'DO' },
          { name: 'Ecuador', value: 'EC' },
          { name: 'Egypt', value: 'EG' },
          { name: 'El Salvador', value: 'SV' },
          { name: 'Estonia', value: 'EE' },
          { name: 'Ethiopia', value: 'ET' },
          { name: 'Fiji', value: 'FJ' },
          { name: 'Finland', value: 'FI' },
          { name: 'France', value: 'FR' },
          { name: 'Gabon', value: 'GA' },
          { name: 'Gambia', value: 'GM' },
          { name: 'Georgia', value: 'GE' },
          { name: 'Germany', value: 'DE' },
          { name: 'Ghana', value: 'GH' },
          { name: 'Gibraltar', value: 'GI' },
          { name: 'Greece', value: 'GR' },
          { name: 'Greenland', value: 'GL' },
          { name: 'Guatemala', value: 'GT' },
          { name: 'Guernsey', value: 'GG' },
          { name: 'Guyana', value: 'GY' },
          { name: 'Haiti', value: 'HT' },
          { name: 'Honduras', value: 'HN' },
          { name: 'Hong Kong', value: 'HK' },
          { name: 'Hungary', value: 'HU' },
          { name: 'Iceland', value: 'IS' },
          { name: 'India', value: 'IN' },
          { name: 'Indonesia', value: 'ID' },
          { name: 'Iran', value: 'IR' },
          { name: 'Iraq', value: 'IQ' },
          { name: 'Ireland', value: 'IE' },
          { name: 'Isle of Man', value: 'IM' },
          { name: 'Israel', value: 'IL' },
          { name: 'Italy', value: 'IT' },
          { name: 'Jamaica', value: 'JM' },
          { name: 'Japan', value: 'JP' },
          { name: 'Jersey', value: 'JE' },
          { name: 'Jordan', value: 'JO' },
          { name: 'Kazakhstan', value: 'KZ' },
          { name: 'Kenya', value: 'KE' },
          { name: 'Kiribati', value: 'KI' },
          { name: 'Kuwait', value: 'KW' },
          { name: 'Kyrgyzstan', value: 'KG' },
          { name: 'Laos', value: 'LA' },
          { name: 'Latvia', value: 'LV' },
          { name: 'Lebanon', value: 'LB' },
          { name: 'Lesotho', value: 'LS' },
          { name: 'Libya', value: 'LY' },
          { name: 'Liechtenstein', value: 'LI' },
          { name: 'Lithuania', value: 'LT' },
          { name: 'Luxembourg', value: 'LU' },
          { name: 'Madagascar', value: 'MG' },
          { name: 'Malawi', value: 'MW' },
          { name: 'Malaysia', value: 'MY' },
          { name: 'Maldives', value: 'MV' },
          { name: 'Mali', value: 'ML' },
          { name: 'Malta', value: 'MT' },
          { name: 'Mauritius', value: 'MU' },
          { name: 'Mexico', value: 'MX' },
          { name: 'Micronesia', value: 'FM' },
          { name: 'Moldova', value: 'MD' },
          { name: 'Mongolia', value: 'MN' },
          { name: 'Montenegro', value: 'ME' },
          { name: 'Montserrat', value: 'MS' },
          { name: 'Morocco', value: 'MA' },
          { name: 'Mozambique', value: 'MZ' },
          { name: 'Myanmar (Burma)', value: 'MM' },
          { name: 'Namibia', value: 'NA' },
          { name: 'Nauru', value: 'NR' },
          { name: 'Nepal', value: 'NP' },
          { name: 'Netherlands', value: 'NL' },
          { name: 'New Zealand', value: 'NZ' },
          { name: 'Nicaragua', value: 'NI' },
          { name: 'Niger', value: 'NE' },
          { name: 'Nigeria', value: 'NG' },
          { name: 'Niue', value: 'NU' },
          { name: 'North Macedonia', value: 'MK' },
          { name: 'Norway', value: 'NO' },
          { name: 'Oman', value: 'OM' },
          { name: 'Pakistan', value: 'PK' },
          { name: 'Palestine', value: 'PS' },
          { name: 'Panama', value: 'PA' },
          { name: 'Papua New Guinea', value: 'PG' },
          { name: 'Paraguay', value: 'PY' },
          { name: 'Peru', value: 'PE' },
          { name: 'Philippines', value: 'PH' },
          { name: 'Pitcairn Islands', value: 'PN' },
          { name: 'Poland', value: 'PL' },
          { name: 'Portugal', value: 'PT' },
          { name: 'Puerto Rico', value: 'PR' },
          { name: 'Qatar', value: 'QA' },
          { name: 'Romania', value: 'RO' },
          { name: 'Russia', value: 'RU' },
          { name: 'Rwanda', value: 'RW' },
          { name: 'Samoa', value: 'WS' },
          { name: 'San Marino', value: 'SM' },
          { name: 'São Tomé & Príncipe', value: 'ST' },
          { name: 'Saudi Arabia', value: 'SA' },
          { name: 'Senegal', value: 'SN' },
          { name: 'Serbia', value: 'RS' },
          { name: 'Seychelles', value: 'SC' },
          { name: 'Sierra Leone', value: 'SL' },
          { name: 'Singapore', value: 'SG' },
          { name: 'Slovakia', value: 'SK' },
          { name: 'Slovenia', value: 'SI' },
          { name: 'Solomon Islands', value: 'SB' },
          { name: 'Somalia', value: 'SO' },
          { name: 'South Africa', value: 'ZA' },
          { name: 'South Korea', value: 'KR' },
          { name: 'Spain', value: 'ES' },
          { name: 'Sri Lanka', value: 'LK' },
          { name: 'St. Helena', value: 'SH' },
          { name: 'St. Vincent & Grenadines', value: 'VC' },
          { name: 'Suriname', value: 'SR' },
          { name: 'Sweden', value: 'SE' },
          { name: 'Switzerland', value: 'CH' },
          { name: 'Taiwan', value: 'TW' },
          { name: 'Tajikistan', value: 'TJ' },
          { name: 'Tanzania', value: 'TZ' },
          { name: 'Thailand', value: 'TH' },
          { name: 'Timor-Leste', value: 'TL' },
          { name: 'Togo', value: 'TG' },
          { name: 'Tonga', value: 'TO' },
          { name: 'Trinidad & Tobago', value: 'TT' },
          { name: 'Tunisia', value: 'TN' },
          { name: 'Türkiye', value: 'TR' },
          { name: 'Turkmenistan', value: 'TM' },
          { name: 'Uganda', value: 'UG' },
          { name: 'Ukraine', value: 'UA' },
          { name: 'United Arab Emirates', value: 'AE' },
          { name: 'United Kingdom', value: 'GB' },
          { name: 'United States', value: 'US' },
          { name: 'Uruguay', value: 'UY' },
          { name: 'Uzbekistan', value: 'UZ' },
          { name: 'Vanuatu', value: 'VU' },
          { name: 'Venezuela', value: 'VE' },
          { name: 'Vietnam', value: 'VN' },
          { name: 'Zambia', value: 'ZM' },
          { name: 'Zimbabwe', value: 'ZW' },
        ],
        default: '',
        description: 'Defines the country of the search. Check the full list of supported Google Travel gl countries.',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'am', value: 'am' },
          { name: 'Any', value: '' },
          { name: 'ar', value: 'ar' },
          { name: 'bg', value: 'bg' },
          { name: 'bn', value: 'bn' },
          { name: 'Bosanski', value: 'bs' },
          { name: 'Català', value: 'ca' },
          { name: 'cs', value: 'cs' },
          { name: 'Dansk', value: 'da' },
          { name: 'Deutsch', value: 'de' },
          { name: 'Eesti', value: 'et' },
          { name: 'el', value: 'el' },
          { name: 'English (United Kingdom)', value: 'en-GB' },
          { name: 'English (United States)', value: 'en-US' },
          { name: 'Español (España)', value: 'es' },
          { name: 'Español (Latinoamérica)', value: 'es-419' },
          { name: 'Euskara', value: 'eu' },
          { name: 'fa', value: 'fa' },
          { name: 'Filipino', value: 'fil' },
          { name: 'Français', value: 'fr' },
          { name: 'Galego', value: 'gl' },
          { name: 'gu', value: 'gu' },
          { name: 'hi', value: 'hi' },
          { name: 'Hrvatski', value: 'hr' },
          { name: 'Indonesia', value: 'id' },
          { name: 'is', value: 'is' },
          { name: 'Italiano', value: 'it' },
          { name: 'iw', value: 'iw' },
          { name: 'ja', value: 'ja' },
          { name: 'ka', value: 'ka' },
          { name: 'Kiswahili', value: 'sw' },
          { name: 'km', value: 'km' },
          { name: 'kn', value: 'kn' },
          { name: 'ko', value: 'ko' },
          { name: 'Latviešu', value: 'lv' },
          { name: 'Lietuvių', value: 'lt' },
          { name: 'lo', value: 'lo' },
          { name: 'Magyar', value: 'hu' },
          { name: 'Melayu', value: 'ms' },
          { name: 'mk', value: 'mk' },
          { name: 'ml', value: 'ml' },
          { name: 'mn', value: 'mn' },
          { name: 'mr', value: 'mr' },
          { name: 'ne', value: 'ne' },
          { name: 'Nederlands', value: 'nl' },
          { name: 'Norsk', value: 'no' },
          { name: 'pa', value: 'pa' },
          { name: 'Polski', value: 'pl' },
          { name: 'Português (Brasil)', value: 'pt-BR' },
          { name: 'Português (Portugal)', value: 'pt-PT' },
          { name: 'Română', value: 'ro' },
          { name: 'ru', value: 'ru' },
          { name: 'Shqip', value: 'sq' },
          { name: 'si', value: 'si' },
          { name: 'Slovenčina', value: 'sk' },
          { name: 'Slovenščina', value: 'sl' },
          { name: 'sr', value: 'sr' },
          { name: 'Srpski (latinica)', value: 'sr-Latn' },
          { name: 'Suomi', value: 'fi' },
          { name: 'Svenska', value: 'sv' },
          { name: 'ta', value: 'ta' },
          { name: 'te', value: 'te' },
          { name: 'th', value: 'th' },
          { name: 'Tiếng Việt', value: 'vi' },
          { name: 'Türkçe', value: 'tr' },
          { name: 'uk', value: 'uk' },
          { name: 'ur', value: 'ur' },
          { name: 'zh-CN', value: 'zh-CN' },
          { name: 'zh-TW', value: 'zh-TW' },
        ],
        default: '',
        description: 'Defines the interface language of the search. Check the full list of supported Google Travel hl languages.',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Hotel Filters',
    name: 'hotel_filters',
    type: 'collection',
    placeholder: 'Add Hotel Filters',
    default: {},
    options: [
      {
        displayName: 'Expanded Search (expanded_search)',
        name: 'expanded_search',
        type: 'boolean',
        default: false,
        description: 'Whether to fetch per-OTA pricing for vacation rental properties. When a property is classified as vacation_rental, the default response only includes limited booking offers. With this parameter enabled, full OTA price comparison (e.g., Booking.com, Expedia, Hotels.com, Agoda, etc.) is returned in featured_offers and all_offers.',
        routing: {
          request: {
            qs: {
              expanded_search: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Free Cancellation (free_cancellation)',
        name: 'free_cancellation',
        type: 'boolean',
        default: false,
        description: 'Whether to display only hotels that offer free cancellation on bookings',
        routing: {
          request: {
            qs: {
              free_cancellation: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Number of Guests',
    name: 'number_of_guests',
    type: 'collection',
    placeholder: 'Add Number of Guests',
    default: {},
    options: [
      {
        displayName: 'Adults (adults)',
        name: 'adults',
        type: 'number',
        typeOptions: {
          minValue: 1,
          maxValue: 10,
          numberPrecision: 0,
        },
        default: 2,
        description: 'The number of adults staying in the apartment. Default is 2. For type=hotels, the maximum number of guests is 6 (including children). For type=vacation_rental, the maximum number is 10.',
        routing: {
          request: {
            qs: {
              adults: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Children Ages (children_ages)',
        name: 'children_ages',
        type: 'string',
        default: '',
        description: 'Defines the ages of children as a comma-separated list, e.g., 2,5 for two children aged 2 and 5. Available age range is 1–17. Note: This parameter is only applicable for hotels and will be ignored for other property types.',
        routing: {
          request: {
            qs: {
              children_ages: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_hotels_property = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-hotels-property-api',
};
