import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';
import { ADS_TRANSPARENCY_COUNTRIES } from '../shared/lists';
import { countryOptions } from '../shared/options';
import { nextPageToken, numParam, zeroDataRetention } from '../shared/params';

const displayOptions = {
  show: {
    resource: ['google_ads_transparency_center'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Ads Transparency Center',
  value: 'google_ads_transparency_center'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Params',
    name: 'search_params',
    type: 'collection',
    placeholder: 'Add Search Params',
    default: {},
    options: [
      {
        displayName: 'Advertiser ID (advertiser_id)',
        name: 'advertiser_id',
        type: 'string',
        default: '',
        description: 'Specifies the advertiser\'s unique ID. Multiple IDs can be provided, separated by commas. Required if domain is not provided.',
        routing: {
          request: {
            qs: {
              advertiser_id: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Domain (domain)',
        name: 'domain',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Google.ad', value: 'google.ad' },
          { name: 'Google.ae', value: 'google.ae' },
          { name: 'Google.al', value: 'google.al' },
          { name: 'Google.am', value: 'google.am' },
          { name: 'Google.as', value: 'google.as' },
          { name: 'Google.at', value: 'google.at' },
          { name: 'Google.az', value: 'google.az' },
          { name: 'Google.ba', value: 'google.ba' },
          { name: 'Google.be', value: 'google.be' },
          { name: 'Google.bf', value: 'google.bf' },
          { name: 'Google.bg', value: 'google.bg' },
          { name: 'Google.bi', value: 'google.bi' },
          { name: 'Google.bj', value: 'google.bj' },
          { name: 'Google.bs', value: 'google.bs' },
          { name: 'Google.bt', value: 'google.bt' },
          { name: 'Google.by', value: 'google.by' },
          { name: 'Google.ca', value: 'google.ca' },
          { name: 'Google.cat', value: 'google.cat' },
          { name: 'Google.cd', value: 'google.cd' },
          { name: 'Google.cf', value: 'google.cf' },
          { name: 'Google.cg', value: 'google.cg' },
          { name: 'Google.ch', value: 'google.ch' },
          { name: 'Google.ci', value: 'google.ci' },
          { name: 'Google.cl', value: 'google.cl' },
          { name: 'Google.cm', value: 'google.cm' },
          { name: 'Google.co.ao', value: 'google.co.ao' },
          { name: 'Google.co.bw', value: 'google.co.bw' },
          { name: 'Google.co.ck', value: 'google.co.ck' },
          { name: 'Google.co.cr', value: 'google.co.cr' },
          { name: 'Google.co.id', value: 'google.co.id' },
          { name: 'Google.co.il', value: 'google.co.il' },
          { name: 'Google.co.in', value: 'google.co.in' },
          { name: 'Google.co.jp', value: 'google.co.jp' },
          { name: 'Google.co.ke', value: 'google.co.ke' },
          { name: 'Google.co.kr', value: 'google.co.kr' },
          { name: 'Google.co.ls', value: 'google.co.ls' },
          { name: 'Google.co.ma', value: 'google.co.ma' },
          { name: 'Google.co.mz', value: 'google.co.mz' },
          { name: 'Google.co.nz', value: 'google.co.nz' },
          { name: 'Google.co.th', value: 'google.co.th' },
          { name: 'Google.co.tz', value: 'google.co.tz' },
          { name: 'Google.co.ug', value: 'google.co.ug' },
          { name: 'Google.co.uk', value: 'google.co.uk' },
          { name: 'Google.co.uz', value: 'google.co.uz' },
          { name: 'Google.co.ve', value: 'google.co.ve' },
          { name: 'Google.co.vi', value: 'google.co.vi' },
          { name: 'Google.co.za', value: 'google.co.za' },
          { name: 'Google.co.zm', value: 'google.co.zm' },
          { name: 'Google.co.zw', value: 'google.co.zw' },
          { name: 'Google.com', value: 'google.com' },
          { name: 'Google.com.af', value: 'google.com.af' },
          { name: 'Google.com.ag', value: 'google.com.ag' },
          { name: 'Google.com.ai', value: 'google.com.ai' },
          { name: 'Google.com.ar', value: 'google.com.ar' },
          { name: 'Google.com.au', value: 'google.com.au' },
          { name: 'Google.com.bd', value: 'google.com.bd' },
          { name: 'Google.com.bh', value: 'google.com.bh' },
          { name: 'Google.com.bn', value: 'google.com.bn' },
          { name: 'Google.com.bo', value: 'google.com.bo' },
          { name: 'Google.com.br', value: 'google.com.br' },
          { name: 'Google.com.bz', value: 'google.com.bz' },
          { name: 'Google.com.co', value: 'google.com.co' },
          { name: 'Google.com.cu', value: 'google.com.cu' },
          { name: 'Google.com.cy', value: 'google.com.cy' },
          { name: 'Google.com.do', value: 'google.com.do' },
          { name: 'Google.com.ec', value: 'google.com.ec' },
          { name: 'Google.com.eg', value: 'google.com.eg' },
          { name: 'Google.com.et', value: 'google.com.et' },
          { name: 'Google.com.fj', value: 'google.com.fj' },
          { name: 'Google.com.gh', value: 'google.com.gh' },
          { name: 'Google.com.gi', value: 'google.com.gi' },
          { name: 'Google.com.gt', value: 'google.com.gt' },
          { name: 'Google.com.hk', value: 'google.com.hk' },
          { name: 'Google.com.jm', value: 'google.com.jm' },
          { name: 'Google.com.kh', value: 'google.com.kh' },
          { name: 'Google.com.kw', value: 'google.com.kw' },
          { name: 'Google.com.lb', value: 'google.com.lb' },
          { name: 'Google.com.ly', value: 'google.com.ly' },
          { name: 'Google.com.mm', value: 'google.com.mm' },
          { name: 'Google.com.mt', value: 'google.com.mt' },
          { name: 'Google.com.mx', value: 'google.com.mx' },
          { name: 'Google.com.my', value: 'google.com.my' },
          { name: 'Google.com.na', value: 'google.com.na' },
          { name: 'Google.com.ng', value: 'google.com.ng' },
          { name: 'Google.com.ni', value: 'google.com.ni' },
          { name: 'Google.com.np', value: 'google.com.np' },
          { name: 'Google.com.om', value: 'google.com.om' },
          { name: 'Google.com.pa', value: 'google.com.pa' },
          { name: 'Google.com.pe', value: 'google.com.pe' },
          { name: 'Google.com.pg', value: 'google.com.pg' },
          { name: 'Google.com.ph', value: 'google.com.ph' },
          { name: 'Google.com.pk', value: 'google.com.pk' },
          { name: 'Google.com.pr', value: 'google.com.pr' },
          { name: 'Google.com.py', value: 'google.com.py' },
          { name: 'Google.com.qa', value: 'google.com.qa' },
          { name: 'Google.com.sa', value: 'google.com.sa' },
          { name: 'Google.com.sb', value: 'google.com.sb' },
          { name: 'Google.com.sg', value: 'google.com.sg' },
          { name: 'Google.com.sl', value: 'google.com.sl' },
          { name: 'Google.com.sv', value: 'google.com.sv' },
          { name: 'Google.com.tj', value: 'google.com.tj' },
          { name: 'Google.com.tr', value: 'google.com.tr' },
          { name: 'Google.com.tw', value: 'google.com.tw' },
          { name: 'Google.com.ua', value: 'google.com.ua' },
          { name: 'Google.com.uy', value: 'google.com.uy' },
          { name: 'Google.com.vc', value: 'google.com.vc' },
          { name: 'Google.com.vn', value: 'google.com.vn' },
          { name: 'Google.cv', value: 'google.cv' },
          { name: 'Google.cz', value: 'google.cz' },
          { name: 'Google.de', value: 'google.de' },
          { name: 'Google.dj', value: 'google.dj' },
          { name: 'Google.dk', value: 'google.dk' },
          { name: 'Google.dm', value: 'google.dm' },
          { name: 'Google.dz', value: 'google.dz' },
          { name: 'Google.ee', value: 'google.ee' },
          { name: 'Google.es', value: 'google.es' },
          { name: 'Google.fi', value: 'google.fi' },
          { name: 'Google.fm', value: 'google.fm' },
          { name: 'Google.fr', value: 'google.fr' },
          { name: 'Google.ga', value: 'google.ga' },
          { name: 'Google.ge', value: 'google.ge' },
          { name: 'Google.gg', value: 'google.gg' },
          { name: 'Google.gl', value: 'google.gl' },
          { name: 'Google.gm', value: 'google.gm' },
          { name: 'Google.gp', value: 'google.gp' },
          { name: 'Google.gr', value: 'google.gr' },
          { name: 'Google.gy', value: 'google.gy' },
          { name: 'Google.hn', value: 'google.hn' },
          { name: 'Google.hr', value: 'google.hr' },
          { name: 'Google.ht', value: 'google.ht' },
          { name: 'Google.hu', value: 'google.hu' },
          { name: 'Google.ie', value: 'google.ie' },
          { name: 'Google.im', value: 'google.im' },
          { name: 'Google.iq', value: 'google.iq' },
          { name: 'Google.is', value: 'google.is' },
          { name: 'Google.it', value: 'google.it' },
          { name: 'Google.je', value: 'google.je' },
          { name: 'Google.jo', value: 'google.jo' },
          { name: 'Google.kg', value: 'google.kg' },
          { name: 'Google.ki', value: 'google.ki' },
          { name: 'Google.kz', value: 'google.kz' },
          { name: 'Google.la', value: 'google.la' },
          { name: 'Google.li', value: 'google.li' },
          { name: 'Google.lk', value: 'google.lk' },
          { name: 'Google.lt', value: 'google.lt' },
          { name: 'Google.lu', value: 'google.lu' },
          { name: 'Google.lv', value: 'google.lv' },
          { name: 'Google.md', value: 'google.md' },
          { name: 'Google.me', value: 'google.me' },
          { name: 'Google.mg', value: 'google.mg' },
          { name: 'Google.mk', value: 'google.mk' },
          { name: 'Google.ml', value: 'google.ml' },
          { name: 'Google.mn', value: 'google.mn' },
          { name: 'Google.ms', value: 'google.ms' },
          { name: 'Google.mu', value: 'google.mu' },
          { name: 'Google.mv', value: 'google.mv' },
          { name: 'Google.mw', value: 'google.mw' },
          { name: 'Google.ne', value: 'google.ne' },
          { name: 'Google.nl', value: 'google.nl' },
          { name: 'Google.no', value: 'google.no' },
          { name: 'Google.nr', value: 'google.nr' },
          { name: 'Google.nu', value: 'google.nu' },
          { name: 'Google.pl', value: 'google.pl' },
          { name: 'Google.pn', value: 'google.pn' },
          { name: 'Google.ps', value: 'google.ps' },
          { name: 'Google.pt', value: 'google.pt' },
          { name: 'Google.ro', value: 'google.ro' },
          { name: 'Google.rs', value: 'google.rs' },
          { name: 'Google.ru', value: 'google.ru' },
          { name: 'Google.rw', value: 'google.rw' },
          { name: 'Google.sc', value: 'google.sc' },
          { name: 'Google.se', value: 'google.se' },
          { name: 'Google.sh', value: 'google.sh' },
          { name: 'Google.si', value: 'google.si' },
          { name: 'Google.sk', value: 'google.sk' },
          { name: 'Google.sm', value: 'google.sm' },
          { name: 'Google.sn', value: 'google.sn' },
          { name: 'Google.so', value: 'google.so' },
          { name: 'Google.sr', value: 'google.sr' },
          { name: 'Google.st', value: 'google.st' },
          { name: 'Google.td', value: 'google.td' },
          { name: 'Google.tg', value: 'google.tg' },
          { name: 'Google.tk', value: 'google.tk' },
          { name: 'Google.tl', value: 'google.tl' },
          { name: 'Google.tm', value: 'google.tm' },
          { name: 'Google.tn', value: 'google.tn' },
          { name: 'Google.to', value: 'google.to' },
          { name: 'Google.tt', value: 'google.tt' },
          { name: 'Google.vg', value: 'google.vg' },
          { name: 'Google.vu', value: 'google.vu' },
          { name: 'Google.ws', value: 'google.ws' },
        ],
        default: '',
        description: 'Defines the advertiser\'s verified domain (e.g., tesla.com). Required if advertiser_id is not provided.',
        routing: {
          request: {
            qs: {
              domain: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Ad Format (ad_format)',
        name: 'ad_format',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Image', value: 'image' },
          { name: 'Text', value: 'text' },
          { name: 'Video', value: 'video' },
        ],
        default: '',
        description: 'Filters results based on ad format',
        routing: {
          request: {
            qs: {
              ad_format: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Platform (platform)',
        name: 'platform',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Google maps', value: 'google_maps' },
          { name: 'Google play', value: 'google_play' },
          { name: 'Google search', value: 'google_search' },
          { name: 'Google shopping', value: 'google_shopping' },
          { name: 'Youtube', value: 'youtube' },
        ],
        default: '',
        description: 'Specifies the platform for which the ads are being retrieved',
        routing: {
          request: {
            qs: {
              platform: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Region (region)',
        name: 'region',
        type: 'options',
        options: countryOptions(ADS_TRANSPARENCY_COUNTRIES),
        default: '',
        description: 'Specifies the region for your search. The default parameter is anywhere.',
        routing: {
          request: {
            qs: {
              region: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Last 30 days', value: 'last_30_days' },
          { name: 'Last 7 days', value: 'last_7_days' },
          { name: 'Today', value: 'today' },
          { name: 'Yesterday', value: 'yesterday' },
        ],
        default: '',
        description: 'Limits the results to a specific time range. Alternatively, specify a custom range using YYYY-MM-DD..YYYY-MM-DD.',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      nextPageToken('A token for fetching the next set of results. You can obtain this token from the next_page_token field in the previous response.'),
      numParam('Specifies the number of results to return. Default is 40. The maximum is 100.', { maxValue: 100, defaultValue: 40 })
    ],
    displayOptions,
  },
  zeroDataRetention(displayOptions)
];

export const google_ads_transparency_center = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-ads-transparency-center-api',
};
