import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_news'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google News',
  value: 'google_news'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Query (q)',
    name: 'q',
    type: 'string',
    required: true,
    default: '',
    description: 'Terms to search on Google News. Queries can include operators and advanced filters like "climate change", site:, inurl:, intitle:, as_dt, or as_eq.',
    displayOptions,
    routing: {
      request: {
        qs: {
          q: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Device',
    name: 'device',
    type: 'collection',
    placeholder: 'Add Device',
    default: {},
    options: [
      {
        displayName: 'Device (device)',
        name: 'device',
        type: 'options',
        options: [
          { name: 'Desktop', value: 'desktop' },
          { name: 'Mobile', value: 'mobile' },
          { name: 'Tablet', value: 'tablet' },
        ],
        default: 'desktop',
        description: 'The default parameter desktop defines the search on a desktop device. The mobile parameter defines the search on a mobile device. The tablet parameter defines the search on a tablet device.',
        routing: {
          request: {
            qs: {
              device: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Geographic Location',
    name: 'geographic_location',
    type: 'collection',
    placeholder: 'Add Geographic Location',
    default: {},
    options: [
      {
        displayName: 'Location (location)',
        name: 'location',
        type: 'string',
        default: '',
        description: 'Specifies the canonical location of the search. For exact targeting or to see all available options, check out the Locations API. If multiple locations match your input, the most popular one will be selected.',
        routing: {
          request: {
            qs: {
              location: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'UULE (uule)',
        name: 'uule',
        type: 'string',
        default: '',
        description: 'Sets the exact Google-encoded location for the search. The uule and location parameters cannot be used at the same time. SearchApi builds it for you when you use the location parameter, but you can provide your own if you want precise control.',
        routing: {
          request: {
            qs: {
              uule: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo', value: 'cg' },
          { name: 'Congo, the Democratic Republic of the', value: 'cd' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote D\'ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cuba', value: 'cu' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guernsey', value: 'gg' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard Island and Mcdonald Islands', value: 'hm' },
          { name: 'Holy See (Vatican City State)', value: 'va' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iran, Islamic Republic of', value: 'ir' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Isle of Man', value: 'im' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jersey', value: 'je' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macao', value: 'mo' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia, Federated States of', value: 'fm' },
          { name: 'Moldova, Republic of', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montenegro', value: 'me' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Myanmar', value: 'mm' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'North Korea', value: 'kp' },
          { name: 'North Macedonia', value: 'mk' },
          { name: 'Northern Mariana Islands', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory, Occupied', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Helena', value: 'sh' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Pierre and Miquelon', value: 'pm' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'rs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and the South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'Sudan', value: 'sd' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Syrian Arab Republic', value: 'sy' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania, United Republic of', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Timor-Leste', value: 'tl' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands, British', value: 'vg' },
          { name: 'Virgin Islands, U.S.', value: 'vi' },
          { name: 'Wallis and Futuna', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: 'us',
        description: 'The default parameter us defines the country of the search. Check the full list of supported Google gl countries.',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'CR (cr)',
        name: 'cr',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Any', value: '' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo (cd)', value: 'cd' },
          { name: 'Congo (cg)', value: 'cg' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote d\'Ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'East Timor', value: 'tl' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard and McDonald Islands', value: 'hm' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macau', value: 'mo' },
          { name: 'Macedonia', value: 'mk' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia', value: 'fm' },
          { name: 'Moldova', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'Northern Maria', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'cs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and The South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'St. Helena', value: 'sh' },
          { name: 'St. Pierre and Miquelon', value: 'pm' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen Islands', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vatican', value: 'va' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands (British)', value: 'vg' },
          { name: 'Virgin Islands (U.S.)', value: 'vi' },
          { name: 'Wallis and Futuna Islands', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: '',
        description: 'Restricts search results to documents originating in a particular country. Google determines the country of a document by the top-level domain (TLD) of the document\'s URL or by Web server\'s IP address geographic location. Check the full list of supported Google cr countries.',
        routing: {
          request: {
            qs: {
              cr: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Google Domain (google_domain)',
        name: 'google_domain',
        type: 'string',
        default: 'google.com',
        description: 'As of Apr 15, 2025, Google began phasing out country code top-level domains (ccTLDs). Users using the search bar or visiting local domains like google.de or google.co.uk are now automatically redirected to google.com. For localized searches, use the gl (country), hl (language) or other localization parameters instead. Learn more in Google\'s official announcement. See the full list of supported Google domains.',
        routing: {
          request: {
            qs: {
              google_domain: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Arabic', value: 'ar' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Chinese (Simplified)', value: 'zh-cn' },
          { name: 'Chinese (Traditional)', value: 'zh-tw' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'English', value: 'en' },
          { name: 'French', value: 'fr' },
          { name: 'Galician', value: 'gl' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Greenlandic', value: 'kl' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jw' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Korean', value: 'ko' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maldivian', value: 'mv' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Montenegrin', value: 'sr-me' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Persian', value: 'fa' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt-br' },
          { name: 'Portuguese (Portugal)', value: 'pt-pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Russian', value: 'ru' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Spanish', value: 'es' },
          { name: 'Spanish (Latin America)', value: 'es-419' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vietnamese', value: 'vi' },
        ],
        default: 'en',
        description: 'The default parameter en defines the interface language of the search. Check the full list of supported Google News hl languages.',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'LR (lr)',
        name: 'lr',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Arabic', value: 'lang_ar' },
          { name: 'Armenian', value: 'lang_hy' },
          { name: 'Bulgarian', value: 'lang_bg' },
          { name: 'Catalan', value: 'lang_ca' },
          { name: 'Chinese (Simplified)', value: 'lang_zh-CN' },
          { name: 'Chinese (Traditional)', value: 'lang_zh-TW' },
          { name: 'Croatian', value: 'lang_hr' },
          { name: 'Czech', value: 'lang_cs' },
          { name: 'Danish', value: 'lang_da' },
          { name: 'Dutch', value: 'lang_nl' },
          { name: 'English', value: 'lang_en' },
          { name: 'Estonian', value: 'lang_et' },
          { name: 'Filipino', value: 'lang_tl' },
          { name: 'Finnish', value: 'lang_fi' },
          { name: 'French', value: 'lang_fr' },
          { name: 'German', value: 'lang_de' },
          { name: 'Greek', value: 'lang_el' },
          { name: 'Hebrew', value: 'lang_iw' },
          { name: 'Hindi', value: 'lang_hi' },
          { name: 'Hungarian', value: 'lang_hu' },
          { name: 'Icelandic', value: 'lang_is' },
          { name: 'Indonesian', value: 'lang_id' },
          { name: 'Italian', value: 'lang_it' },
          { name: 'Japanese', value: 'lang_ja' },
          { name: 'Korean', value: 'lang_ko' },
          { name: 'Latvian', value: 'lang_lv' },
          { name: 'Lithuanian', value: 'lang_lt' },
          { name: 'Norwegian', value: 'lang_no' },
          { name: 'Persian', value: 'lang_fa' },
          { name: 'Polish', value: 'lang_pl' },
          { name: 'Portuguese', value: 'lang_pt' },
          { name: 'Romanian', value: 'lang_ro' },
          { name: 'Russian', value: 'lang_ru' },
          { name: 'Serbian', value: 'lang_sr' },
          { name: 'Slovak', value: 'lang_sk' },
          { name: 'Slovenian', value: 'lang_sl' },
          { name: 'Spanish', value: 'lang_es' },
          { name: 'Swedish', value: 'lang_sv' },
          { name: 'Thai', value: 'lang_th' },
          { name: 'Turkish', value: 'lang_tr' },
          { name: 'Ukrainian', value: 'lang_uk' },
          { name: 'Vietnamese', value: 'lang_vi' },
        ],
        default: '',
        description: 'Restricts search results to documents written in a particular language or a set of languages. The accepted format is lang_{2-letter country code}. For instance, to filter documents written in Japanese, the value should be set to lang_jp. To incorporate multiple languages, a value like lang_it|lang_de restricts the search to documents written in either Italian or German. Google identifies the document language based on the top-level domain (TLD) of the document\'s URL, any language meta tags present, or the language utilized within the document\'s body text. Check the full list of supported Google lr languages.',
        routing: {
          request: {
            qs: {
              lr: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Filter (filter)',
        name: 'filter',
        type: 'options',
        options: [
          { name: 'Disable "Duplicate Content" and "Host Crowding" filters', value: '0' },
          { name: 'Enable "Duplicate Content" and "Host Crowding" filters', value: '1' },
        ],
        default: '1',
        description: 'Controls whether the "Duplicate Content" and "Host Crowding" filters are enabled. Set the value to 1 to enable these filters, which is the default setting. To disable these filters, set the value to 0.',
        routing: {
          request: {
            qs: {
              filter: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'NFPR (nfpr)',
        name: 'nfpr',
        type: 'options',
        options: [
          { name: 'Exclude auto-corrected results', value: '1' },
          { name: 'Include auto-corrected results', value: '0' },
        ],
        default: '0',
        description: 'Controls whether results from queries that have been auto-corrected for spelling errors are included. To exclude these auto-corrected results, set the value to 1. By default, the value is 0, meaning auto-corrected results are included.',
        routing: {
          request: {
            qs: {
              nfpr: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Sort By (sort_by)',
        name: 'sort_by',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Most recent', value: 'most_recent' },
        ],
        default: '',
        description: 'By default, news results are sorted by relevance. To get the most recent articles, set it to most_recent.',
        routing: {
          request: {
            qs: {
              sort_by: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Last 1 minute', value: 'last_1_minute' },
          { name: 'Last 15 minutes', value: 'last_15_minutes' },
          { name: 'Last 30 minutes', value: 'last_30_minutes' },
          { name: 'Last 5 minutes', value: 'last_5_minutes' },
          { name: 'Last day', value: 'last_day' },
          { name: 'Last hour', value: 'last_hour' },
          { name: 'Last month', value: 'last_month' },
          { name: 'Last week', value: 'last_week' },
          { name: 'Last year', value: 'last_year' },
        ],
        default: '',
        description: 'Restricts results to URLs based on date. Supported values are: last_hour - data from the past hour. last_day - data from the past 24 hours. last_week - data from the past week. last_month - data from the past month. last_year - data from the past year. Using time_period_min or time_period_max parameters, you can specify a custom time period. Note, that the time_period_min and time_period_max parameters could be used separately as well.',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period Max (time_period_max)',
        name: 'time_period_max',
        type: 'string',
        default: '',
        description: 'Specifies the end of the time period. It could be used in combination with the time_period_min parameter. The value should be in the format MM/DD/YYYY.',
        routing: {
          request: {
            qs: {
              time_period_max: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period Min (time_period_min)',
        name: 'time_period_min',
        type: 'string',
        default: '',
        description: 'Specifies the start of the time period. It could be used in combination with the time_period_max parameter. The value should be in the format MM/DD/YYYY.',
        routing: {
          request: {
            qs: {
              time_period_min: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Page (page)',
        name: 'page',
        type: 'number',
        typeOptions: {
          minValue: 1,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Indicates which page of results to return. By default, it is set to 1.',
        routing: {
          request: {
            qs: {
              page: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_news = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-news',
};
