import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_images'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Images',
  value: 'google_images'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Query (q)',
    name: 'q',
    type: 'string',
    required: true,
    default: '',
    description: 'Terms you want to search on Google Images. Queries can include operators and advanced filters like "cute cats", site:, inurl:, intitle:, as_dt, or as_eq.',
    displayOptions,
    routing: {
      request: {
        qs: {
          q: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Device',
    name: 'device',
    type: 'collection',
    placeholder: 'Add Device',
    default: {},
    options: [
      {
        displayName: 'Device (device)',
        name: 'device',
        type: 'options',
        options: [
          { name: 'Desktop', value: 'desktop' },
          { name: 'Mobile', value: 'mobile' },
          { name: 'Tablet', value: 'tablet' },
        ],
        default: 'desktop',
        description: 'The default parameter desktop defines the search on a desktop device. The mobile parameter defines the search on a mobile device. The tablet parameter defines the search on a tablet device.',
        routing: {
          request: {
            qs: {
              device: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Geographic Location',
    name: 'geographic_location',
    type: 'collection',
    placeholder: 'Add Geographic Location',
    default: {},
    options: [
      {
        displayName: 'Location (location)',
        name: 'location',
        type: 'string',
        default: '',
        description: 'Canonical location of the search. If multiple locations match your input, the most popular one will be selected.',
        routing: {
          request: {
            qs: {
              location: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Encoded Location (uule)',
        name: 'uule',
        type: 'string',
        default: '',
        description: 'Exact Google-encoded location for the search; uule and location cannot be used at the same time. SearchApi builds it for you when you use the location parameter, but you can provide your own if you want precise control.',
        routing: {
          request: {
            qs: {
              uule: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo', value: 'cg' },
          { name: 'Congo, the Democratic Republic of the', value: 'cd' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote D\'ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cuba', value: 'cu' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guernsey', value: 'gg' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard Island and Mcdonald Islands', value: 'hm' },
          { name: 'Holy See (Vatican City State)', value: 'va' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iran, Islamic Republic of', value: 'ir' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Isle of Man', value: 'im' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jersey', value: 'je' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macao', value: 'mo' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia, Federated States of', value: 'fm' },
          { name: 'Moldova, Republic of', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montenegro', value: 'me' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Myanmar', value: 'mm' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'North Korea', value: 'kp' },
          { name: 'North Macedonia', value: 'mk' },
          { name: 'Northern Mariana Islands', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory, Occupied', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Helena', value: 'sh' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Pierre and Miquelon', value: 'pm' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'rs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and the South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'Sudan', value: 'sd' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Syrian Arab Republic', value: 'sy' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania, United Republic of', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Timor-Leste', value: 'tl' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands, British', value: 'vg' },
          { name: 'Virgin Islands, U.S.', value: 'vi' },
          { name: 'Wallis and Futuna', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: 'us',
        description: 'The default parameter us defines the country of the search',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country Restrict (cr)',
        name: 'cr',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'countryAF' },
          { name: 'Albania', value: 'countryAL' },
          { name: 'Algeria', value: 'countryDZ' },
          { name: 'American Samoa', value: 'countryAS' },
          { name: 'Andorra', value: 'countryAD' },
          { name: 'Angola', value: 'countryAO' },
          { name: 'Anguilla', value: 'countryAI' },
          { name: 'Antarctica', value: 'countryAQ' },
          { name: 'Antigua and Barbuda', value: 'countryAG' },
          { name: 'Any', value: '' },
          { name: 'Argentina', value: 'countryAR' },
          { name: 'Armenia', value: 'countryAM' },
          { name: 'Aruba', value: 'countryAW' },
          { name: 'Australia', value: 'countryAU' },
          { name: 'Austria', value: 'countryAT' },
          { name: 'Azerbaijan', value: 'countryAZ' },
          { name: 'Bahamas', value: 'countryBS' },
          { name: 'Bahrain', value: 'countryBH' },
          { name: 'Bangladesh', value: 'countryBD' },
          { name: 'Barbados', value: 'countryBB' },
          { name: 'Belarus', value: 'countryBY' },
          { name: 'Belgium', value: 'countryBE' },
          { name: 'Belize', value: 'countryBZ' },
          { name: 'Benin', value: 'countryBJ' },
          { name: 'Bermuda', value: 'countryBM' },
          { name: 'Bhutan', value: 'countryBT' },
          { name: 'Bolivia', value: 'countryBO' },
          { name: 'Bosnia and Herzegovina', value: 'countryBA' },
          { name: 'Botswana', value: 'countryBW' },
          { name: 'Bouvet Island', value: 'countryBV' },
          { name: 'Brazil', value: 'countryBR' },
          { name: 'British Indian Ocean Territory', value: 'countryIO' },
          { name: 'Brunei Darussalam', value: 'countryBN' },
          { name: 'Bulgaria', value: 'countryBG' },
          { name: 'Burkina Faso', value: 'countryBF' },
          { name: 'Burundi', value: 'countryBI' },
          { name: 'Cambodia', value: 'countryKH' },
          { name: 'Cameroon', value: 'countryCM' },
          { name: 'Canada', value: 'countryCA' },
          { name: 'Cape Verde', value: 'countryCV' },
          { name: 'Cayman Islands', value: 'countryKY' },
          { name: 'Central African Republic', value: 'countryCF' },
          { name: 'Chad', value: 'countryTD' },
          { name: 'Chile', value: 'countryCL' },
          { name: 'China', value: 'countryCN' },
          { name: 'Christmas Island', value: 'countryCX' },
          { name: 'Cocos (Keeling) Islands', value: 'countryCC' },
          { name: 'Colombia', value: 'countryCO' },
          { name: 'Comoros', value: 'countryKM' },
          { name: 'Congo (cd)', value: 'countryCD' },
          { name: 'Congo (cg)', value: 'countryCG' },
          { name: 'Cook Islands', value: 'countryCK' },
          { name: 'Costa Rica', value: 'countryCR' },
          { name: 'Cote d\'Ivoire', value: 'ci' },
          { name: 'Croatia', value: 'countryHR' },
          { name: 'Cyprus', value: 'countryCY' },
          { name: 'Czech Republic', value: 'countryCZ' },
          { name: 'Denmark', value: 'countryDK' },
          { name: 'Djibouti', value: 'countryDJ' },
          { name: 'Dominica', value: 'countryDM' },
          { name: 'Dominican Republic', value: 'countryDO' },
          { name: 'East Timor', value: 'countryTL' },
          { name: 'Ecuador', value: 'countryEC' },
          { name: 'Egypt', value: 'countryEG' },
          { name: 'El Salvador', value: 'countrySV' },
          { name: 'Equatorial Guinea', value: 'countryGQ' },
          { name: 'Eritrea', value: 'countryER' },
          { name: 'Estonia', value: 'countryEE' },
          { name: 'Ethiopia', value: 'countryET' },
          { name: 'Falkland Islands (Malvinas)', value: 'countryFK' },
          { name: 'Faroe Islands', value: 'countryFO' },
          { name: 'Fiji', value: 'countryFJ' },
          { name: 'Finland', value: 'countryFI' },
          { name: 'France', value: 'countryFR' },
          { name: 'French Guiana', value: 'countryGF' },
          { name: 'French Polynesia', value: 'countryPF' },
          { name: 'French Southern Territories', value: 'countryTF' },
          { name: 'Gabon', value: 'countryGA' },
          { name: 'Gambia', value: 'countryGM' },
          { name: 'Georgia', value: 'countryGE' },
          { name: 'Germany', value: 'countryDE' },
          { name: 'Ghana', value: 'countryGH' },
          { name: 'Gibraltar', value: 'countryGI' },
          { name: 'Greece', value: 'countryGR' },
          { name: 'Greenland', value: 'countryGL' },
          { name: 'Grenada', value: 'countryGD' },
          { name: 'Guadeloupe', value: 'countryGP' },
          { name: 'Guam', value: 'countryGU' },
          { name: 'Guatemala', value: 'countryGT' },
          { name: 'Guinea', value: 'countryGN' },
          { name: 'Guinea-Bissau', value: 'countryGW' },
          { name: 'Guyana', value: 'countryGY' },
          { name: 'Haiti', value: 'countryHT' },
          { name: 'Heard and McDonald Islands', value: 'countryHM' },
          { name: 'Honduras', value: 'countryHN' },
          { name: 'Hong Kong', value: 'countryHK' },
          { name: 'Hungary', value: 'countryHU' },
          { name: 'Iceland', value: 'countryIS' },
          { name: 'India', value: 'countryIN' },
          { name: 'Indonesia', value: 'countryID' },
          { name: 'Iraq', value: 'countryIQ' },
          { name: 'Ireland', value: 'countryIE' },
          { name: 'Israel', value: 'countryIL' },
          { name: 'Italy', value: 'countryIT' },
          { name: 'Jamaica', value: 'countryJM' },
          { name: 'Japan', value: 'countryJP' },
          { name: 'Jordan', value: 'countryJO' },
          { name: 'Kazakhstan', value: 'countryKZ' },
          { name: 'Kenya', value: 'countryKE' },
          { name: 'Kiribati', value: 'countryKI' },
          { name: 'Kuwait', value: 'countryKW' },
          { name: 'Kyrgyzstan', value: 'countryKG' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'countryLV' },
          { name: 'Lebanon', value: 'countryLB' },
          { name: 'Lesotho', value: 'countryLS' },
          { name: 'Liberia', value: 'countryLR' },
          { name: 'Libya', value: 'countryLY' },
          { name: 'Liechtenstein', value: 'countryLI' },
          { name: 'Lithuania', value: 'countryLT' },
          { name: 'Luxembourg', value: 'countryLU' },
          { name: 'Macau', value: 'countryMO' },
          { name: 'Macedonia', value: 'countryMK' },
          { name: 'Madagascar', value: 'countryMG' },
          { name: 'Malawi', value: 'countryMW' },
          { name: 'Malaysia', value: 'countryMY' },
          { name: 'Maldives', value: 'countryMV' },
          { name: 'Mali', value: 'countryML' },
          { name: 'Malta', value: 'countryMT' },
          { name: 'Marshall Islands', value: 'countryMH' },
          { name: 'Martinique', value: 'countryMQ' },
          { name: 'Mauritania', value: 'countryMR' },
          { name: 'Mauritius', value: 'countryMU' },
          { name: 'Mayotte', value: 'countryYT' },
          { name: 'Mexico', value: 'countryMX' },
          { name: 'Micronesia', value: 'countryFM' },
          { name: 'Moldova', value: 'countryMD' },
          { name: 'Monaco', value: 'countryMC' },
          { name: 'Mongolia', value: 'countryMN' },
          { name: 'Montserrat', value: 'countryMS' },
          { name: 'Morocco', value: 'countryMA' },
          { name: 'Mozambique', value: 'countryMZ' },
          { name: 'Namibia', value: 'countryNA' },
          { name: 'Nauru', value: 'countryNR' },
          { name: 'Nepal', value: 'countryNP' },
          { name: 'Netherlands', value: 'countryNL' },
          { name: 'New Caledonia', value: 'countryNC' },
          { name: 'New Zealand', value: 'countryNZ' },
          { name: 'Nicaragua', value: 'countryNI' },
          { name: 'Niger', value: 'countryNE' },
          { name: 'Nigeria', value: 'countryNG' },
          { name: 'Niue', value: 'countryNU' },
          { name: 'Norfolk Island', value: 'countryNF' },
          { name: 'Northern Maria', value: 'countryMP' },
          { name: 'Norway', value: 'countryNO' },
          { name: 'Oman', value: 'countryOM' },
          { name: 'Pakistan', value: 'countryPK' },
          { name: 'Palau', value: 'countryPW' },
          { name: 'Palestinian Territory', value: 'countryPS' },
          { name: 'Panama', value: 'countryPA' },
          { name: 'Papua New Guinea', value: 'countryPG' },
          { name: 'Paraguay', value: 'countryPY' },
          { name: 'Peru', value: 'countryPE' },
          { name: 'Philippines', value: 'countryPH' },
          { name: 'Pitcairn', value: 'countryPN' },
          { name: 'Poland', value: 'countryPL' },
          { name: 'Portugal', value: 'countryPT' },
          { name: 'Puerto Rico', value: 'countryPR' },
          { name: 'Qatar', value: 'countryQA' },
          { name: 'Reunion', value: 'countryRE' },
          { name: 'Romania', value: 'countryRO' },
          { name: 'Russian Federation', value: 'countryRU' },
          { name: 'Rwanda', value: 'countryRW' },
          { name: 'Saint Kitts and Nevis', value: 'countryKN' },
          { name: 'Saint Lucia', value: 'countryLC' },
          { name: 'Saint Vincent and the Grenadines', value: 'countryVC' },
          { name: 'Samoa', value: 'countryWS' },
          { name: 'San Marino', value: 'countrySM' },
          { name: 'Sao Tome and Principe', value: 'countryST' },
          { name: 'Saudi Arabia', value: 'countrySA' },
          { name: 'Senegal', value: 'countrySN' },
          { name: 'Serbia and Montenegro', value: 'countryCS' },
          { name: 'Seychelles', value: 'countrySC' },
          { name: 'Sierra Leone', value: 'countrySL' },
          { name: 'Singapore', value: 'countrySG' },
          { name: 'Slovakia', value: 'countrySK' },
          { name: 'Slovenia', value: 'countrySI' },
          { name: 'Solomon Islands', value: 'countrySB' },
          { name: 'Somalia', value: 'countrySO' },
          { name: 'South Africa', value: 'countryZA' },
          { name: 'South Georgia and The South Sandwich Islands', value: 'countryGS' },
          { name: 'South Korea', value: 'countryKR' },
          { name: 'Spain', value: 'countryES' },
          { name: 'Sri Lanka', value: 'countryLK' },
          { name: 'St. Helena', value: 'countrySH' },
          { name: 'St. Pierre and Miquelon', value: 'countryPM' },
          { name: 'Suriname', value: 'countrySR' },
          { name: 'Svalbard and Jan Mayen Islands', value: 'countrySJ' },
          { name: 'Swaziland', value: 'countrySZ' },
          { name: 'Sweden', value: 'countrySE' },
          { name: 'Switzerland', value: 'countryCH' },
          { name: 'Taiwan', value: 'countryTW' },
          { name: 'Tajikistan', value: 'countryTJ' },
          { name: 'Tanzania', value: 'countryTZ' },
          { name: 'Thailand', value: 'countryTH' },
          { name: 'Togo', value: 'countryTG' },
          { name: 'Tokelau', value: 'countryTK' },
          { name: 'Tonga', value: 'countryTO' },
          { name: 'Trinidad and Tobago', value: 'countryTT' },
          { name: 'Tunisia', value: 'countryTN' },
          { name: 'Turkey', value: 'countryTR' },
          { name: 'Turkmenistan', value: 'countryTM' },
          { name: 'Turks and Caicos Islands', value: 'countryTC' },
          { name: 'Tuvalu', value: 'countryTV' },
          { name: 'Uganda', value: 'countryUG' },
          { name: 'Ukraine', value: 'countryUA' },
          { name: 'United Arab Emirates', value: 'countryAE' },
          { name: 'United Kingdom (gb)', value: 'countryGB' },
          { name: 'United Kingdom (uk)', value: 'countryUK' },
          { name: 'United States', value: 'countryUS' },
          { name: 'United States Minor Outlying Islands', value: 'countryUM' },
          { name: 'Uruguay', value: 'countryUY' },
          { name: 'Uzbekistan', value: 'countryUZ' },
          { name: 'Vanuatu', value: 'countryVU' },
          { name: 'Vatican', value: 'countryVA' },
          { name: 'Venezuela', value: 'countryVE' },
          { name: 'Viet Nam', value: 'countryVN' },
          { name: 'Virgin Islands (British)', value: 'countryVG' },
          { name: 'Virgin Islands (U.S.)', value: 'countryVI' },
          { name: 'Wallis and Futuna Islands', value: 'countryWF' },
          { name: 'Western Sahara', value: 'countryEH' },
          { name: 'Yemen', value: 'countryYE' },
          { name: 'Zambia', value: 'countryZM' },
          { name: 'Zimbabwe', value: 'countryZW' },
        ],
        default: '',
        description: 'Restricts search results to documents originating in a particular country. Google determines the country of a document by the top-level domain (TLD) of the document\'s URL or by Web server\'s IP address geographic location.',
        routing: {
          request: {
            qs: {
              cr: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Google Domain (google_domain)',
        name: 'google_domain',
        type: 'string',
        default: 'google.com',
        description: 'As of Apr 15, 2025, Google began phasing out country code top-level domains (ccTLDs). Users using the search bar or visiting local domains like google.de or google.co.uk are now automatically redirected to google.com. For localized searches, use the gl (country), hl (language) or other localization parameters instead.',
        routing: {
          request: {
            qs: {
              google_domain: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bemba', value: 'bem' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bork, bork, bork!', value: 'xx-bork' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Breton', value: 'br' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Cambodian', value: 'km' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cherokee', value: 'chr' },
          { name: 'Chichewa', value: 'ny' },
          { name: 'Chinese (Simplified)', value: 'zh-cn' },
          { name: 'Chinese (Traditional)', value: 'zh-tw' },
          { name: 'Corsican', value: 'co' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'Elmer Fudd', value: 'xx-elmer' },
          { name: 'English', value: 'en' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Faroese', value: 'fo' },
          { name: 'Filipino', value: 'tl' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Frisian', value: 'fy' },
          { name: 'Ga', value: 'gaa' },
          { name: 'Galician', value: 'gl' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Greenlandic', value: 'kl' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Hacker', value: 'xx-hacker' },
          { name: 'Haitian Creole', value: 'ht' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hawaiian', value: 'haw' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Interlingua', value: 'ia' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jw' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Kirundi', value: 'rn' },
          { name: 'Klingon', value: 'xx-klingon' },
          { name: 'Kongo', value: 'kg' },
          { name: 'Korean', value: 'ko' },
          { name: 'Krio (Sierra Leone)', value: 'kri' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kurdish (Soranî)', value: 'ckb' },
          { name: 'Kyrgyz', value: 'ky' },
          { name: 'Laothian', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Lozi', value: 'loz' },
          { name: 'Luganda', value: 'lg' },
          { name: 'Luo', value: 'ach' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Maori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Mauritian Creole', value: 'mfe' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Montenegrin', value: 'sr-me' },
          { name: 'Nepali', value: 'ne' },
          { name: 'Nigerian Pidgin', value: 'pcm' },
          { name: 'Northern Sotho', value: 'nso' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Norwegian (Nynorsk)', value: 'nn' },
          { name: 'Occitan', value: 'oc' },
          { name: 'Oriya', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Persian', value: 'fa' },
          { name: 'Pirate', value: 'xx-pirate' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt-br' },
          { name: 'Portuguese (Portugal)', value: 'pt-pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Romansh', value: 'rm' },
          { name: 'Runyakitara', value: 'nyn' },
          { name: 'Russian', value: 'ru' },
          { name: 'Scots Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Sesotho', value: 'st' },
          { name: 'Setswana', value: 'tn' },
          { name: 'Seychellois Creole', value: 'crs' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhalese', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Spanish', value: 'es' },
          { name: 'Spanish (Latin American)', value: 'es-419' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tonga', value: 'to' },
          { name: 'Tshiluba', value: 'lua' },
          { name: 'Tumbuka', value: 'tum' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Twi', value: 'tw' },
          { name: 'Uighur', value: 'ug' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Wolof', value: 'wo' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: 'en',
        description: 'The default parameter en defines the interface language of the search',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language Restrict (lr)',
        name: 'lr',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Arabic', value: 'lang_ar' },
          { name: 'Armenian', value: 'lang_hy' },
          { name: 'Bulgarian', value: 'lang_bg' },
          { name: 'Catalan', value: 'lang_ca' },
          { name: 'Chinese (Simplified)', value: 'lang_zh-CN' },
          { name: 'Chinese (Traditional)', value: 'lang_zh-TW' },
          { name: 'Croatian', value: 'lang_hr' },
          { name: 'Czech', value: 'lang_cs' },
          { name: 'Danish', value: 'lang_da' },
          { name: 'Dutch', value: 'lang_nl' },
          { name: 'English', value: 'lang_en' },
          { name: 'Estonian', value: 'lang_et' },
          { name: 'Filipino', value: 'lang_tl' },
          { name: 'Finnish', value: 'lang_fi' },
          { name: 'French', value: 'lang_fr' },
          { name: 'German', value: 'lang_de' },
          { name: 'Greek', value: 'lang_el' },
          { name: 'Hebrew', value: 'lang_iw' },
          { name: 'Hindi', value: 'lang_hi' },
          { name: 'Hungarian', value: 'lang_hu' },
          { name: 'Icelandic', value: 'lang_is' },
          { name: 'Indonesian', value: 'lang_id' },
          { name: 'Italian', value: 'lang_it' },
          { name: 'Japanese', value: 'lang_ja' },
          { name: 'Korean', value: 'lang_ko' },
          { name: 'Latvian', value: 'lang_lv' },
          { name: 'Lithuanian', value: 'lang_lt' },
          { name: 'Norwegian', value: 'lang_no' },
          { name: 'Persian', value: 'lang_fa' },
          { name: 'Polish', value: 'lang_pl' },
          { name: 'Portuguese', value: 'lang_pt' },
          { name: 'Romanian', value: 'lang_ro' },
          { name: 'Russian', value: 'lang_ru' },
          { name: 'Serbian', value: 'lang_sr' },
          { name: 'Slovak', value: 'lang_sk' },
          { name: 'Slovenian', value: 'lang_sl' },
          { name: 'Spanish', value: 'lang_es' },
          { name: 'Swedish', value: 'lang_sv' },
          { name: 'Thai', value: 'lang_th' },
          { name: 'Turkish', value: 'lang_tr' },
          { name: 'Ukrainian', value: 'lang_uk' },
          { name: 'Vietnamese', value: 'lang_vi' },
        ],
        default: '',
        description: 'Restricts search results to documents written in a particular language or a set of languages. The accepted format for this parameter is lang_{2-letter country code}. For instance, to filter documents written in Japanese, the value should be set to lang_jp. To incorporate multiple languages, a value like lang_it|lang_de restricts the search to documents written in either Italian or German. Google identifies the document language based on the top-level domain (TLD) of the document\'s URL, any language meta tags present, or the language utilized within the document\'s body text.',
        routing: {
          request: {
            qs: {
              lr: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Advanced Search Filter (tbs)',
        name: 'tbs',
        type: 'string',
        default: '',
        description: 'Restricts results to URLs based on encoded values. Normally constructed using size, color, image_type, time_period, usage_rights values. For instance, isz:l would return only results that has large image size.',
        routing: {
          request: {
            qs: {
              tbs: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Aspect Ratio (aspect_ratio)',
        name: 'aspect_ratio',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Panoramic', value: 'panoramic' },
          { name: 'Square', value: 'square' },
          { name: 'Tall', value: 'tall' },
          { name: 'Wide', value: 'wide' },
        ],
        default: '',
        description: 'Filters images based on aspect ratio',
        routing: {
          request: {
            qs: {
              aspect_ratio: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Auto-Correction Filter (nfpr)',
        name: 'nfpr',
        type: 'options',
        options: [
          { name: 'Exclude auto-corrected results', value: '1' },
          { name: 'Include auto-corrected results', value: '0' },
        ],
        default: '0',
        description: 'Controls whether results from queries that have been auto-corrected for spelling errors are included. To exclude these auto-corrected results, set the value to 1. By default, the value is 0, meaning auto-corrected results are included.',
        routing: {
          request: {
            qs: {
              nfpr: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Color (color)',
        name: 'color',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Black', value: 'black' },
          { name: 'Black and white', value: 'black_and_white' },
          { name: 'Blue', value: 'blue' },
          { name: 'Brown', value: 'brown' },
          { name: 'Color', value: 'color' },
          { name: 'Gray', value: 'gray' },
          { name: 'Green', value: 'green' },
          { name: 'Orange', value: 'orange' },
          { name: 'Pink', value: 'pink' },
          { name: 'Purple', value: 'purple' },
          { name: 'Red', value: 'red' },
          { name: 'Teal', value: 'teal' },
          { name: 'Transparent', value: 'transparent' },
          { name: 'White', value: 'white' },
          { name: 'Yellow', value: 'yellow' },
        ],
        default: '',
        description: 'Controls the color of your search results',
        routing: {
          request: {
            qs: {
              color: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Filter (filter)',
        name: 'filter',
        type: 'options',
        options: [
          { name: 'Disable "Duplicate Content" and "Host Crowding" filters', value: '0' },
          { name: 'Enable "Duplicate Content" and "Host Crowding" filters', value: '1' },
        ],
        default: '1',
        description: 'Controls whether the "Duplicate Content" and "Host Crowding" filters are enabled. Set the value to 1 to enable these filters, which is the default setting. To disable these filters, set the value to 0.',
        routing: {
          request: {
            qs: {
              filter: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Image Type (image_type)',
        name: 'image_type',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Clipart', value: 'clipart' },
          { name: 'Face', value: 'face' },
          { name: 'Gif', value: 'gif' },
          { name: 'Line drawing', value: 'line_drawing' },
          { name: 'Photo', value: 'photo' },
        ],
        default: '',
        description: 'Controls the type of your search results',
        routing: {
          request: {
            qs: {
              image_type: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Safe Search (safe)',
        name: 'safe',
        type: 'options',
        options: [
          { name: 'Blur explicit images', value: 'blur' },
          { name: 'Disable SafeSearch', value: 'off' },
          { name: 'Enable strict SafeSearch', value: 'active' },
        ],
        default: 'blur',
        description: 'Toggles the SafeSearch feature for the results. SafeSearch operates by filtering out adult content from your search results. Google\'s filters use proprietary technology to check keywords, phrases and URLs. While no filters are 100 percent accurate, SafeSearch will remove the overwhelming majority of adult content from your search results.',
        routing: {
          request: {
            qs: {
              safe: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Size (size)',
        name: 'size',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Icon', value: 'icon' },
          { name: 'Large', value: 'large' },
          { name: 'Larger than 1024x768', value: 'larger_than_1024x768' },
          { name: 'Larger than 12mp', value: 'larger_than_12mp' },
          { name: 'Larger than 15mp', value: 'larger_than_15mp' },
          { name: 'Larger than 20mp', value: 'larger_than_20mp' },
          { name: 'Larger than 2mp', value: 'larger_than_2mp' },
          { name: 'Larger than 400x300', value: 'larger_than_400x300' },
          { name: 'Larger than 40mp', value: 'larger_than_40mp' },
          { name: 'Larger than 4mp', value: 'larger_than_4mp' },
          { name: 'Larger than 640x480', value: 'larger_than_640x480' },
          { name: 'Larger than 6mp', value: 'larger_than_6mp' },
          { name: 'Larger than 70mp', value: 'larger_than_70mp' },
          { name: 'Larger than 800x600', value: 'larger_than_800x600' },
          { name: 'Larger than 8mp', value: 'larger_than_8mp' },
          { name: 'Medium', value: 'medium' },
        ],
        default: '',
        description: 'Controls the size of your search results',
        routing: {
          request: {
            qs: {
              size: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Last 1 minute', value: 'last_1_minute' },
          { name: 'Last 15 minutes', value: 'last_15_minutes' },
          { name: 'Last 30 minutes', value: 'last_30_minutes' },
          { name: 'Last 5 minutes', value: 'last_5_minutes' },
          { name: 'Last day', value: 'last_day' },
          { name: 'Last hour', value: 'last_hour' },
          { name: 'Last month', value: 'last_month' },
          { name: 'Last week', value: 'last_week' },
          { name: 'Last year', value: 'last_year' },
        ],
        default: '',
        description: 'Restricts results to URLs based on date',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Usage Rights (usage_rights)',
        name: 'usage_rights',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Commercial or other licenses', value: 'commercial_or_other_licenses' },
          { name: 'Creative commons licenses', value: 'creative_commons_licenses' },
        ],
        default: '',
        description: 'Controls the usage rights of your search results',
        routing: {
          request: {
            qs: {
              usage_rights: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Page Number (page)',
        name: 'page',
        type: 'number',
        typeOptions: {
          minValue: 1,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Indicates which page of results to return. By default, it is set to 1.',
        routing: {
          request: {
            qs: {
              page: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_images = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-images',
};
