import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';
import { zeroDataRetention } from '../shared/params';

const displayOptions = {
  show: {
    resource: ['google_shopping_filters'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Shopping Filters',
  value: 'google_shopping_filters'
};

const properties: INodeProperties[] = [
  {
    displayName: 'All Filters Token (all_filters_token)',
    name: 'all_filters_token',
    type: 'string',
    required: true,
    typeOptions: { password: true },
    default: '',
    description: 'A token that will be used to retrieve all filters data. The token is generated by the Google Shopping API.',
    displayOptions,
    routing: {
      request: {
        qs: {
          all_filters_token: '={{$value}}',
        },
      },
    },
  },
  zeroDataRetention(displayOptions)
];

export const google_shopping_filters = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-shopping-filters',
};
