import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_jobs'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Jobs',
  value: 'google_jobs'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Query (q)',
    name: 'q',
    type: 'string',
    required: true,
    default: '',
    description: 'Terms to search on Google Jobs. Queries can include terms like "software engineer" or "marketing manager in New York".',
    displayOptions,
    routing: {
      request: {
        qs: {
          q: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Geographic Location',
    name: 'geographic_location',
    type: 'collection',
    placeholder: 'Add Geographic Location',
    default: {},
    options: [
      {
        displayName: 'Location (location)',
        name: 'location',
        type: 'string',
        default: '',
        description: 'This parameter is used to specify the canonical location of the search. For exact targeting or to see all available options, check out the Locations API. If multiple locations match your input, the most popular one will be selected.',
        routing: {
          request: {
            qs: {
              location: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Google-Encoded Location (uule)',
        name: 'uule',
        type: 'string',
        default: '',
        description: 'This parameter sets the exact Google-encoded location for the search, and uule and location cannot be used at the same time. SearchApi builds it for you when you use the location parameter, but you can provide your own if you want precise control.',
        routing: {
          request: {
            qs: {
              uule: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Austria', value: 'at' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'Colombia', value: 'co' },
          { name: 'Congo, the Democratic Republic of the', value: 'cd' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote D\'ivoire', value: 'ci' },
          { name: 'Cuba', value: 'cu' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Greece', value: 'gr' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Libyan Arab Jamahiriya', value: 'ly' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Mali', value: 'ml' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Namibia', value: 'na' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palestinian Territory, Occupied', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Helena', value: 'sh' },
          { name: 'Saint Pierre and Miquelon', value: 'pm' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and the South Sandwich Islands', value: 'gs' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Taiwan, Province of China', value: 'tw' },
          { name: 'Tanzania, United Republic of', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Togo', value: 'tg' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Uganda', value: 'ug' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands, British', value: 'vg' },
          { name: 'Virgin Islands, U.S.', value: 'vi' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: 'us',
        description: 'Country of the search. Check the full list of supported Google Jobs gl countries.',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Google Domain (google_domain)',
        name: 'google_domain',
        type: 'string',
        default: 'google.com',
        description: 'As of Apr 15, 2025, Google began phasing out country code top-level domains (ccTLDs). Users using the search bar or visiting local domains like google.de or google.co.uk are now automatically redirected to google.com. For localized searches, use the gl (country), hl (language) or other localization parameters instead. Learn more in Google\'s official announcement. See the full list of supported Google domains.',
        routing: {
          request: {
            qs: {
              google_domain: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Interface Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bemba', value: 'bem' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bork, bork, bork!', value: 'xx-bork' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Breton', value: 'br' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Cambodian', value: 'km' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cherokee', value: 'chr' },
          { name: 'Chichewa', value: 'ny' },
          { name: 'Chinese (Simplified)', value: 'zh-cn' },
          { name: 'Chinese (Traditional)', value: 'zh-tw' },
          { name: 'Corsican', value: 'co' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'Elmer Fudd', value: 'xx-elmer' },
          { name: 'English', value: 'en' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Faroese', value: 'fo' },
          { name: 'Filipino', value: 'tl' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Frisian', value: 'fy' },
          { name: 'Ga', value: 'gaa' },
          { name: 'Galician', value: 'gl' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Greenlandic', value: 'kl' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Hacker', value: 'xx-hacker' },
          { name: 'Haitian Creole', value: 'ht' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hawaiian', value: 'haw' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Interlingua', value: 'ia' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jw' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Kirundi', value: 'rn' },
          { name: 'Klingon', value: 'xx-klingon' },
          { name: 'Kongo', value: 'kg' },
          { name: 'Korean', value: 'ko' },
          { name: 'Krio (Sierra Leone)', value: 'kri' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kurdish (Soranî)', value: 'ckb' },
          { name: 'Kyrgyz', value: 'ky' },
          { name: 'Laothian', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Lozi', value: 'loz' },
          { name: 'Luganda', value: 'lg' },
          { name: 'Luo', value: 'ach' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Maori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Mauritian Creole', value: 'mfe' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Montenegrin', value: 'sr-me' },
          { name: 'Nepali', value: 'ne' },
          { name: 'Nigerian Pidgin', value: 'pcm' },
          { name: 'Northern Sotho', value: 'nso' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Norwegian (Nynorsk)', value: 'nn' },
          { name: 'Occitan', value: 'oc' },
          { name: 'Oriya', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Persian', value: 'fa' },
          { name: 'Pirate', value: 'xx-pirate' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt-br' },
          { name: 'Portuguese (Portugal)', value: 'pt-pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Romansh', value: 'rm' },
          { name: 'Runyakitara', value: 'nyn' },
          { name: 'Russian', value: 'ru' },
          { name: 'Scots Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Sesotho', value: 'st' },
          { name: 'Setswana', value: 'tn' },
          { name: 'Seychellois Creole', value: 'crs' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhalese', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Spanish', value: 'es' },
          { name: 'Spanish (Latin American)', value: 'es-419' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tonga', value: 'to' },
          { name: 'Tshiluba', value: 'lua' },
          { name: 'Tumbuka', value: 'tum' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Twi', value: 'tw' },
          { name: 'Uighur', value: 'ug' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Wolof', value: 'wo' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: 'en',
        description: 'Interface language of the search. Check the full list of supported Google hl languages.',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Next Page Token (next_page_token)',
        name: 'next_page_token',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        description: 'This parameter is used to retrieve the next page of results. It is returned in the response when there are more results to display. The next_page_token is a unique identifier for the next page of results. It is used to retrieve the next page of results.',
        routing: {
          request: {
            qs: {
              next_page_token: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_jobs = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-jobs',
};
