import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_flights_calendar'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Flights Calendar',
  value: 'google_flights_calendar'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Departure Id (departure_id)',
    name: 'departure_id',
    type: 'string',
    required: true,
    default: '',
    description: 'Specifies the code for the departure airport or a location identifier. Airport Code: A 3-letter uppercase code representing the departure airport (e.g., MAD for Madrid-Barajas Airport or JFK for John F. Kennedy International Airport). You can find these codes using resources like Google Flights or IATA. Location Identifier (kgmid): A string that begins with /m/, used to represent a specific location. You can find this identifier on Wikidata by looking for the "Freebase ID" while searching for location. For example, /m/02_286 is the identifier for New York,United States. Multiple Airports/Locations: You can specify more than one airport or location by separating them with commas. For example: SEA, MIA, /m/02_286.',
    displayOptions,
    routing: {
      request: {
        qs: {
          departure_id: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Arrival Id (arrival_id)',
    name: 'arrival_id',
    type: 'string',
    required: true,
    default: '',
    description: 'Specifies the code for the arrival airport or a location identifier. Airport Code: A 3-letter uppercase code representing the arrival airport (e.g., MAD for Madrid-Barajas Airport or JFK for John F. Kennedy International Airport). You can find these codes using resources like Google Flights or IATA. Location Identifier (kgmid): A string that begins with /m/, used to represent a specific location. You can find this identifier on Wikidata by looking for the "Freebase ID" while searching for location. For example, /m/02_286 is the identifier for New York,United States. Multiple Airports/Locations: You can specify more than one airport or location by separating them with commas. For example: SEA, MIA, /m/02_286.',
    displayOptions,
    routing: {
      request: {
        qs: {
          arrival_id: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Outbound Date (outbound_date)',
    name: 'outbound_date',
    type: 'string',
    required: true,
    default: '',
    description: 'Defines the outbound date. The date format is YYYY-MM-DD.',
    displayOptions,
    routing: {
      request: {
        qs: {
          outbound_date: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Return Date (return_date)',
    name: 'return_date',
    type: 'string',
    default: '',
    description: 'Defines the return date. The date format is YYYY-MM-DD.',
    displayOptions,
    routing: {
      request: {
        qs: {
          return_date: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Date Range',
    name: 'date_range',
    type: 'collection',
    placeholder: 'Add Date Range',
    default: {},
    options: [
      {
        displayName: 'Outbound Date End (outbound_date_end)',
        name: 'outbound_date_end',
        type: 'string',
        default: '',
        description: 'Defines the end date for the outbound flight search. Default value is equal to outbound_date_start + 7 days. Using flight_type=one_way, the response includes all outbound dates between these two values.',
        routing: {
          request: {
            qs: {
              outbound_date_end: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Outbound Date Start (outbound_date_start)',
        name: 'outbound_date_start',
        type: 'string',
        default: '',
        description: 'Defines the start date for the outbound flight search. Default value is equal to outbound_date. When used, it specifies the earliest departure date to consider. Combined with outbound_date_end, it returns flight prices for all outbound dates within the given range.',
        routing: {
          request: {
            qs: {
              outbound_date_start: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Return Date End (return_date_end)',
        name: 'return_date_end',
        type: 'string',
        default: '',
        description: 'Defines the end date for the return flight search. Default value is equal to return_date_start + 7 days. Using both outbound_date_start and return_date_start parameters will return all possible outbound-return date combinations within the specified ranges.',
        routing: {
          request: {
            qs: {
              return_date_end: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Return Date Start (return_date_start)',
        name: 'return_date_start',
        type: 'string',
        default: '',
        description: 'Defines the start date for the return flight search. Default value is equal to return_date. This parameter is only usable when flight_type=round_trip. When provided, it specifies the earliest possible return date in the search results.',
        routing: {
          request: {
            qs: {
              return_date_start: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Carry On Bags (carry_on_bags)',
        name: 'carry_on_bags',
        type: 'number',
        typeOptions: {
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the number of carry-on bags. Default is 0. Note: number can\'t be higher than amount of passengers.',
        routing: {
          request: {
            qs: {
              carry_on_bags: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Checked Bags (checked_bags)',
        name: 'checked_bags',
        type: 'number',
        typeOptions: {
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the number of checked bags. Default is 0. Note: number can\'t be higher than amount of passengers.',
        routing: {
          request: {
            qs: {
              checked_bags: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Emissions (emissions)',
        name: 'emissions',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Less emisions only', value: '1' },
        ],
        default: '',
        description: 'Defines the emission level of the flight. Use 1 to show only flights with lower than typical emissions for that route.',
        routing: {
          request: {
            qs: {
              emissions: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Excluded Airlines (excluded_airlines)',
        name: 'excluded_airlines',
        type: 'string',
        default: '',
        description: 'Defines the airline or alliance codes to be excluded from available airlines. An airline ID is an uppercase code (e.g., AC for Air Canada airline or ONEWORLD for oneworld alliance). Airline codes can be found on IATA. Multiple airlines can be combined by joining them with a comma. For example: AC,ONEWORLD. Note: if included_airlines and excluded_airlines are used together, included_airlines takes priority.',
        routing: {
          request: {
            qs: {
              excluded_airlines: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Excluded Connecting Airports (excluded_connecting_airports)',
        name: 'excluded_connecting_airports',
        type: 'string',
        default: '',
        description: 'Defines connecting airports to be excluded from available airports. An airport ID is an uppercase 3-letter code (e.g., CDG for Paris Charles de Gaulle Airport). Multiple airports can be combined by joining them with a comma.',
        routing: {
          request: {
            qs: {
              excluded_connecting_airports: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Flight Type (flight_type)',
        name: 'flight_type',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Multi city', value: 'multi_city' },
          { name: 'One way', value: 'one_way' },
          { name: 'Round trip', value: 'round_trip' },
        ],
        default: '',
        description: 'Defines the type of the flights',
        routing: {
          request: {
            qs: {
              flight_type: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Included Airlines (included_airlines)',
        name: 'included_airlines',
        type: 'string',
        default: '',
        description: 'Defines the airline or alliance codes to be selected. An airline or alliance ID is an uppercase code (e.g., AC for Air Canada airline or ONEWORLD for oneworld alliance). Airline codes can be found on IATA. Multiple airlines can be combined by joining them with a comma. For example: AC,ONEWORLD.',
        routing: {
          request: {
            qs: {
              included_airlines: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Included Connecting Airports (included_connecting_airports)',
        name: 'included_connecting_airports',
        type: 'string',
        default: '',
        description: 'Defines connecting airports to be included. By default all connecting_airports are included. An airport ID is an uppercase 3-letter code (e.g., CDG for Paris Charles de Gaulle Airport). Multiple airports can be combined by joining them with a comma.',
        routing: {
          request: {
            qs: {
              included_connecting_airports: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Layover Duration Max (layover_duration_max)',
        name: 'layover_duration_max',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 2147483647,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the maximum layover duration in minutes (e.g., 240 for 4 hours). Max value is 1800 minutes (30 hours).',
        routing: {
          request: {
            qs: {
              layover_duration_max: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Layover Duration Min (layover_duration_min)',
        name: 'layover_duration_min',
        type: 'number',
        typeOptions: {
          minValue: 0,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the minimum layover duration in minutes (e.g., 60 for 1 hour)',
        routing: {
          request: {
            qs: {
              layover_duration_min: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Max Flight Duration (max_flight_duration)',
        name: 'max_flight_duration',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 2147483647,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the maximum flight duration in minutes (e.g., 240 for 4 hours)',
        routing: {
          request: {
            qs: {
              max_flight_duration: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Max Price (max_price)',
        name: 'max_price',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 2147483647,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the maximum ticket price. Default is unlimited.',
        routing: {
          request: {
            qs: {
              max_price: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Outbound Times (outbound_times)',
        name: 'outbound_times',
        type: 'string',
        default: '',
        description: 'Defines the outbound departure and arrival times range. This parameter accepts a string containing up to 4 comma-separated numbers, where the first two numbers specify the departure time range and the last two numbers specify the arrival time range. Each number represents the beginning of an hour (e.g., 4,18,2,18 for a 4:00 AM - 7:00 PM departure and a 2:00 AM - 7:00 PM arrival). Default values are: 0,23,0,23.',
        routing: {
          request: {
            qs: {
              outbound_times: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Return Times (return_times)',
        name: 'return_times',
        type: 'string',
        default: '',
        description: 'Defines the return departure and arrival times range. This parameter also accepts up to 4 comma-separated numbers, where the first two specify the departure time range and the last two specify the arrival time range, following the same format as outbound_times (e.g., 4,18,2,18 for a 4:00 AM - 7:00 PM departure and a 2:00 AM - 7:00 PM arrival). Default values are: 0,23,0,23. Note: available only if flight_type set to round_trip.',
        routing: {
          request: {
            qs: {
              return_times: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Separate Tickets (separate_tickets)',
        name: 'separate_tickets',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Hide separate & self-transfer tickets', value: '1' },
          { name: 'Show separate tickets', value: '0' },
        ],
        default: '',
        description: 'Defines whether to display separate tickets. The default value is 0. Set to 1 to hide separate and self-transfer tickets, or 0 to show them.',
        routing: {
          request: {
            qs: {
              separate_tickets: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Stops (stops)',
        name: 'stops',
        type: 'options',
        options: [
          { name: 'Any', value: 'any' },
          { name: 'Nonstop', value: 'nonstop' },
          { name: 'One stop or fewer', value: 'one_stop_or_fewer' },
          { name: 'Two stops or fewer', value: 'two_stops_or_fewer' },
        ],
        default: 'any',
        description: 'Defines the number of stops during the flight',
        routing: {
          request: {
            qs: {
              stops: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Travel Class (travel_class)',
        name: 'travel_class',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Business', value: 'business' },
          { name: 'Economy', value: 'economy' },
          { name: 'First class', value: 'first_class' },
          { name: 'Premium economy', value: 'premium_economy' },
        ],
        default: '',
        description: 'Defines the travel class',
        routing: {
          request: {
            qs: {
              travel_class: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Number of Passengers',
    name: 'number_of_passengers',
    type: 'collection',
    placeholder: 'Add Number of Passengers',
    default: {},
    options: [
      {
        displayName: 'Adults (adults)',
        name: 'adults',
        type: 'number',
        typeOptions: {
          minValue: 1,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Defines the number of adults. Default is 1. Note: Maximum number of passengers is 9.',
        routing: {
          request: {
            qs: {
              adults: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Children (children)',
        name: 'children',
        type: 'number',
        typeOptions: {
          minValue: 0,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the number of children. Default is 0.',
        routing: {
          request: {
            qs: {
              children: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Infants In Seat (infants_in_seat)',
        name: 'infants_in_seat',
        type: 'number',
        typeOptions: {
          minValue: 0,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the number of infants in seat. Default is 0.',
        routing: {
          request: {
            qs: {
              infants_in_seat: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Infants On Lap (infants_on_lap)',
        name: 'infants_on_lap',
        type: 'number',
        typeOptions: {
          minValue: 0,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the number of infants on lap. Default is 0.',
        routing: {
          request: {
            qs: {
              infants_on_lap: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Currency (currency)',
        name: 'currency',
        type: 'options',
        options: [
          { name: 'Albanian Lek', value: 'ALL' },
          { name: 'Algerian Dinar', value: 'DZD' },
          { name: 'Argentine Peso', value: 'ARS' },
          { name: 'Armenian Dram', value: 'AMD' },
          { name: 'Aruban Florin', value: 'AWG' },
          { name: 'Australian Dollar', value: 'AUD' },
          { name: 'Azerbaijani Manat', value: 'AZN' },
          { name: 'Bahamian Dollar', value: 'BSD' },
          { name: 'Bahraini Dinar', value: 'BHD' },
          { name: 'Belarusian Ruble', value: 'BYN' },
          { name: 'Bermudan Dollar', value: 'BMD' },
          { name: 'Bosnia-Herzegovina Convertible Mark', value: 'BAM' },
          { name: 'Brazilian Real', value: 'BRL' },
          { name: 'British Pound', value: 'GBP' },
          { name: 'Bulgarian Lev', value: 'BGN' },
          { name: 'Canadian Dollar', value: 'CAD' },
          { name: 'CFP Franc', value: 'XPF' },
          { name: 'Chilean Peso', value: 'CLP' },
          { name: 'Chinese Yuan', value: 'CNY' },
          { name: 'Colombian Peso', value: 'COP' },
          { name: 'Costa Rican Colón', value: 'CRC' },
          { name: 'Cuban Peso', value: 'CUP' },
          { name: 'Czech Koruna', value: 'CZK' },
          { name: 'Danish Krone', value: 'DKK' },
          { name: 'Dominican Peso', value: 'DOP' },
          { name: 'Egyptian Pound', value: 'EGP' },
          { name: 'Euro', value: 'EUR' },
          { name: 'Georgian Lari', value: 'GEL' },
          { name: 'Hong Kong Dollar', value: 'HKD' },
          { name: 'Hungarian Forint', value: 'HUF' },
          { name: 'Icelandic Króna', value: 'ISK' },
          { name: 'Indian Rupee', value: 'INR' },
          { name: 'Indonesian Rupiah', value: 'IDR' },
          { name: 'Iranian Rial', value: 'IRR' },
          { name: 'Israeli New Shekel', value: 'ILS' },
          { name: 'Jamaican Dollar', value: 'JMD' },
          { name: 'Japanese Yen', value: 'JPY' },
          { name: 'Jordanian Dinar', value: 'JOD' },
          { name: 'Kazakhstani Tenge', value: 'KZT' },
          { name: 'Kuwaiti Dinar', value: 'KWD' },
          { name: 'Lebanese Pound', value: 'LBP' },
          { name: 'Macedonian Denar', value: 'MKD' },
          { name: 'Malaysian Ringgit', value: 'MYR' },
          { name: 'Mexican Peso', value: 'MXN' },
          { name: 'Moldovan Leu', value: 'MDL' },
          { name: 'Moroccan Dirham', value: 'MAD' },
          { name: 'New Taiwan Dollar', value: 'TWD' },
          { name: 'New Zealand Dollar', value: 'NZD' },
          { name: 'Norwegian Krone', value: 'NOK' },
          { name: 'Omani Rial', value: 'OMR' },
          { name: 'Pakistani Rupee', value: 'PKR' },
          { name: 'Panamanian Balboa', value: 'PAB' },
          { name: 'Peruvian Sol', value: 'PEN' },
          { name: 'Philippine Peso', value: 'PHP' },
          { name: 'Polish Zloty', value: 'PLN' },
          { name: 'Qatari Riyal', value: 'QAR' },
          { name: 'Romanian Leu', value: 'RON' },
          { name: 'Russian Ruble', value: 'RUB' },
          { name: 'Saudi Riyal', value: 'SAR' },
          { name: 'Serbian Dinar', value: 'RSD' },
          { name: 'Singapore Dollar', value: 'SGD' },
          { name: 'South African Rand', value: 'ZAR' },
          { name: 'South Korean Won', value: 'KRW' },
          { name: 'Swedish Krona', value: 'SEK' },
          { name: 'Swiss Franc', value: 'CHF' },
          { name: 'Thai Baht', value: 'THB' },
          { name: 'Turkish Lira', value: 'TRY' },
          { name: 'Ukrainian Hryvnia', value: 'UAH' },
          { name: 'United Arab Emirates Dirham', value: 'AED' },
          { name: 'US Dollar', value: 'USD' },
          { name: 'Vietnamese Dong', value: 'VND' },
        ],
        default: 'USD',
        description: 'Defines the currency of the returned prices. Default is USD. Check the full list of supported Google Travel currency values.',
        routing: {
          request: {
            qs: {
              currency: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo', value: 'cg' },
          { name: 'Congo, the Democratic Republic of the', value: 'cd' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote D\'ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cuba', value: 'cu' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guernsey', value: 'gg' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard Island and Mcdonald Islands', value: 'hm' },
          { name: 'Holy See (Vatican City State)', value: 'va' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iran, Islamic Republic of', value: 'ir' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Isle of Man', value: 'im' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jersey', value: 'je' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macao', value: 'mo' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia, Federated States of', value: 'fm' },
          { name: 'Moldova, Republic of', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montenegro', value: 'me' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Myanmar', value: 'mm' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'North Korea', value: 'kp' },
          { name: 'North Macedonia', value: 'mk' },
          { name: 'Northern Mariana Islands', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory, Occupied', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Helena', value: 'sh' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Pierre and Miquelon', value: 'pm' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'rs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and the South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'Sudan', value: 'sd' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Syrian Arab Republic', value: 'sy' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania, United Republic of', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Timor-Leste', value: 'tl' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands, British', value: 'vg' },
          { name: 'Virgin Islands, U.S.', value: 'vi' },
          { name: 'Wallis and Futuna', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: 'us',
        description: 'Defines the country of the search. Check the full list of supported Google Travel gl countries.',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bemba', value: 'bem' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bork, bork, bork!', value: 'xx-bork' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Breton', value: 'br' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Cambodian', value: 'km' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cherokee', value: 'chr' },
          { name: 'Chichewa', value: 'ny' },
          { name: 'Chinese (Simplified)', value: 'zh-cn' },
          { name: 'Chinese (Traditional)', value: 'zh-tw' },
          { name: 'Corsican', value: 'co' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'Elmer Fudd', value: 'xx-elmer' },
          { name: 'English', value: 'en' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Faroese', value: 'fo' },
          { name: 'Filipino', value: 'tl' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Frisian', value: 'fy' },
          { name: 'Ga', value: 'gaa' },
          { name: 'Galician', value: 'gl' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Greenlandic', value: 'kl' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Hacker', value: 'xx-hacker' },
          { name: 'Haitian Creole', value: 'ht' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hawaiian', value: 'haw' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Interlingua', value: 'ia' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jw' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Kirundi', value: 'rn' },
          { name: 'Klingon', value: 'xx-klingon' },
          { name: 'Kongo', value: 'kg' },
          { name: 'Korean', value: 'ko' },
          { name: 'Krio (Sierra Leone)', value: 'kri' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kurdish (Soranî)', value: 'ckb' },
          { name: 'Kyrgyz', value: 'ky' },
          { name: 'Laothian', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Lozi', value: 'loz' },
          { name: 'Luganda', value: 'lg' },
          { name: 'Luo', value: 'ach' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Maori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Mauritian Creole', value: 'mfe' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Montenegrin', value: 'sr-me' },
          { name: 'Nepali', value: 'ne' },
          { name: 'Nigerian Pidgin', value: 'pcm' },
          { name: 'Northern Sotho', value: 'nso' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Norwegian (Nynorsk)', value: 'nn' },
          { name: 'Occitan', value: 'oc' },
          { name: 'Oriya', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Persian', value: 'fa' },
          { name: 'Pirate', value: 'xx-pirate' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt-br' },
          { name: 'Portuguese (Portugal)', value: 'pt-pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Romansh', value: 'rm' },
          { name: 'Runyakitara', value: 'nyn' },
          { name: 'Russian', value: 'ru' },
          { name: 'Scots Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Sesotho', value: 'st' },
          { name: 'Setswana', value: 'tn' },
          { name: 'Seychellois Creole', value: 'crs' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhalese', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Spanish', value: 'es' },
          { name: 'Spanish (Latin American)', value: 'es-419' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tonga', value: 'to' },
          { name: 'Tshiluba', value: 'lua' },
          { name: 'Tumbuka', value: 'tum' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Twi', value: 'tw' },
          { name: 'Uighur', value: 'ug' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Wolof', value: 'wo' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: 'en',
        description: 'Defines the interface language of the search. Check the full list of supported Google Travel hl languages.',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_flights_calendar = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-flights-calendar-api',
};
