import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google_hotels'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google Hotels',
  value: 'google_hotels'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Check In Date (check_in_date)',
    name: 'check_in_date',
    type: 'string',
    required: true,
    default: '',
    description: 'Defines the check-in date for the hotel stay in the format YYYY-MM-DD. This date marks the beginning of the reservation.',
    displayOptions,
    routing: {
      request: {
        qs: {
          check_in_date: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Check Out Date (check_out_date)',
    name: 'check_out_date',
    type: 'string',
    required: true,
    default: '',
    description: 'The check-out date for the hotel stay in the format YYYY-MM-DD. This date marks the end of the reservation.',
    displayOptions,
    routing: {
      request: {
        qs: {
          check_out_date: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Search Query',
    name: 'search_query',
    type: 'collection',
    placeholder: 'Add Search Query',
    default: {},
    options: [
      {
        displayName: 'Bounding Box (bounding_box)',
        name: 'bounding_box',
        type: 'string',
        default: '',
        description: 'Defines the bounding box for the search. The format is [min_longitude, min_latitude, max_longitude, max_latitude]. For example, for USA: [-125.0, 25.0, -66.96, 49.5]. Note: This parameter cannot be combined with the q parameter.',
        routing: {
          request: {
            qs: {
              bounding_box: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Search Query (q)',
        name: 'q',
        type: 'string',
        default: '',
        description: 'Terms to search for on Google Hotels.',
        routing: {
          request: {
            qs: {
              q: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Currency (currency)',
        name: 'currency',
        type: 'options',
        options: [
          { name: 'Albanian Lek', value: 'ALL' },
          { name: 'Algerian Dinar', value: 'DZD' },
          { name: 'Argentine Peso', value: 'ARS' },
          { name: 'Armenian Dram', value: 'AMD' },
          { name: 'Aruban Florin', value: 'AWG' },
          { name: 'Australian Dollar', value: 'AUD' },
          { name: 'Azerbaijani Manat', value: 'AZN' },
          { name: 'Bahamian Dollar', value: 'BSD' },
          { name: 'Bahraini Dinar', value: 'BHD' },
          { name: 'Belarusian Ruble', value: 'BYN' },
          { name: 'Bermudan Dollar', value: 'BMD' },
          { name: 'Bosnia-Herzegovina Convertible Mark', value: 'BAM' },
          { name: 'Brazilian Real', value: 'BRL' },
          { name: 'British Pound', value: 'GBP' },
          { name: 'Bulgarian Lev', value: 'BGN' },
          { name: 'Canadian Dollar', value: 'CAD' },
          { name: 'CFP Franc', value: 'XPF' },
          { name: 'Chilean Peso', value: 'CLP' },
          { name: 'Chinese Yuan', value: 'CNY' },
          { name: 'Colombian Peso', value: 'COP' },
          { name: 'Costa Rican Colón', value: 'CRC' },
          { name: 'Cuban Peso', value: 'CUP' },
          { name: 'Czech Koruna', value: 'CZK' },
          { name: 'Danish Krone', value: 'DKK' },
          { name: 'Dominican Peso', value: 'DOP' },
          { name: 'Egyptian Pound', value: 'EGP' },
          { name: 'Euro', value: 'EUR' },
          { name: 'Georgian Lari', value: 'GEL' },
          { name: 'Hong Kong Dollar', value: 'HKD' },
          { name: 'Hungarian Forint', value: 'HUF' },
          { name: 'Icelandic Króna', value: 'ISK' },
          { name: 'Indian Rupee', value: 'INR' },
          { name: 'Indonesian Rupiah', value: 'IDR' },
          { name: 'Iranian Rial', value: 'IRR' },
          { name: 'Israeli New Shekel', value: 'ILS' },
          { name: 'Jamaican Dollar', value: 'JMD' },
          { name: 'Japanese Yen', value: 'JPY' },
          { name: 'Jordanian Dinar', value: 'JOD' },
          { name: 'Kazakhstani Tenge', value: 'KZT' },
          { name: 'Kuwaiti Dinar', value: 'KWD' },
          { name: 'Lebanese Pound', value: 'LBP' },
          { name: 'Macedonian Denar', value: 'MKD' },
          { name: 'Malaysian Ringgit', value: 'MYR' },
          { name: 'Mexican Peso', value: 'MXN' },
          { name: 'Moldovan Leu', value: 'MDL' },
          { name: 'Moroccan Dirham', value: 'MAD' },
          { name: 'New Taiwan Dollar', value: 'TWD' },
          { name: 'New Zealand Dollar', value: 'NZD' },
          { name: 'Norwegian Krone', value: 'NOK' },
          { name: 'Omani Rial', value: 'OMR' },
          { name: 'Pakistani Rupee', value: 'PKR' },
          { name: 'Panamanian Balboa', value: 'PAB' },
          { name: 'Peruvian Sol', value: 'PEN' },
          { name: 'Philippine Peso', value: 'PHP' },
          { name: 'Polish Zloty', value: 'PLN' },
          { name: 'Qatari Riyal', value: 'QAR' },
          { name: 'Romanian Leu', value: 'RON' },
          { name: 'Russian Ruble', value: 'RUB' },
          { name: 'Saudi Riyal', value: 'SAR' },
          { name: 'Serbian Dinar', value: 'RSD' },
          { name: 'Singapore Dollar', value: 'SGD' },
          { name: 'South African Rand', value: 'ZAR' },
          { name: 'South Korean Won', value: 'KRW' },
          { name: 'Swedish Krona', value: 'SEK' },
          { name: 'Swiss Franc', value: 'CHF' },
          { name: 'Thai Baht', value: 'THB' },
          { name: 'Turkish Lira', value: 'TRY' },
          { name: 'Ukrainian Hryvnia', value: 'UAH' },
          { name: 'United Arab Emirates Dirham', value: 'AED' },
          { name: 'US Dollar', value: 'USD' },
          { name: 'Vietnamese Dong', value: 'VND' },
        ],
        default: 'USD',
        description: 'Defines the currency of the returned prices. Default is USD. Check the full list of supported Google Travel currency values.',
        routing: {
          request: {
            qs: {
              currency: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo', value: 'cg' },
          { name: 'Congo, the Democratic Republic of the', value: 'cd' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote D\'ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cuba', value: 'cu' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guernsey', value: 'gg' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard Island and Mcdonald Islands', value: 'hm' },
          { name: 'Holy See (Vatican City State)', value: 'va' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iran, Islamic Republic of', value: 'ir' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Isle of Man', value: 'im' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jersey', value: 'je' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macao', value: 'mo' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia, Federated States of', value: 'fm' },
          { name: 'Moldova, Republic of', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montenegro', value: 'me' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Myanmar', value: 'mm' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'North Korea', value: 'kp' },
          { name: 'North Macedonia', value: 'mk' },
          { name: 'Northern Mariana Islands', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory, Occupied', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Helena', value: 'sh' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Pierre and Miquelon', value: 'pm' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'rs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and the South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'Sudan', value: 'sd' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Syrian Arab Republic', value: 'sy' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania, United Republic of', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Timor-Leste', value: 'tl' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands, British', value: 'vg' },
          { name: 'Virgin Islands, U.S.', value: 'vi' },
          { name: 'Wallis and Futuna', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: 'us',
        description: 'Defines the country of the search. Default is us.',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bemba', value: 'bem' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bork, bork, bork!', value: 'xx-bork' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Breton', value: 'br' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Cambodian', value: 'km' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cherokee', value: 'chr' },
          { name: 'Chichewa', value: 'ny' },
          { name: 'Chinese (Simplified)', value: 'zh-cn' },
          { name: 'Chinese (Traditional)', value: 'zh-tw' },
          { name: 'Corsican', value: 'co' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'Elmer Fudd', value: 'xx-elmer' },
          { name: 'English', value: 'en' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Faroese', value: 'fo' },
          { name: 'Filipino', value: 'tl' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Frisian', value: 'fy' },
          { name: 'Ga', value: 'gaa' },
          { name: 'Galician', value: 'gl' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Greenlandic', value: 'kl' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Hacker', value: 'xx-hacker' },
          { name: 'Haitian Creole', value: 'ht' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hawaiian', value: 'haw' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Interlingua', value: 'ia' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jw' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Kirundi', value: 'rn' },
          { name: 'Klingon', value: 'xx-klingon' },
          { name: 'Kongo', value: 'kg' },
          { name: 'Korean', value: 'ko' },
          { name: 'Krio (Sierra Leone)', value: 'kri' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kurdish (Soranî)', value: 'ckb' },
          { name: 'Kyrgyz', value: 'ky' },
          { name: 'Laothian', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Lozi', value: 'loz' },
          { name: 'Luganda', value: 'lg' },
          { name: 'Luo', value: 'ach' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Maori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Mauritian Creole', value: 'mfe' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Montenegrin', value: 'sr-me' },
          { name: 'Nepali', value: 'ne' },
          { name: 'Nigerian Pidgin', value: 'pcm' },
          { name: 'Northern Sotho', value: 'nso' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Norwegian (Nynorsk)', value: 'nn' },
          { name: 'Occitan', value: 'oc' },
          { name: 'Oriya', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Persian', value: 'fa' },
          { name: 'Pirate', value: 'xx-pirate' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt-br' },
          { name: 'Portuguese (Portugal)', value: 'pt-pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Romansh', value: 'rm' },
          { name: 'Runyakitara', value: 'nyn' },
          { name: 'Russian', value: 'ru' },
          { name: 'Scots Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Sesotho', value: 'st' },
          { name: 'Setswana', value: 'tn' },
          { name: 'Seychellois Creole', value: 'crs' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhalese', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Spanish', value: 'es' },
          { name: 'Spanish (Latin American)', value: 'es-419' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tonga', value: 'to' },
          { name: 'Tshiluba', value: 'lua' },
          { name: 'Tumbuka', value: 'tum' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Twi', value: 'tw' },
          { name: 'Uighur', value: 'ug' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Wolof', value: 'wo' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: 'en',
        description: 'Defines the interface language of the search. Default is en.',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Amenities (amenities)',
        name: 'amenities',
        type: 'options',
        options: [
          { name: 'Air-conditioned (16)', value: '16' },
          { name: 'Air-conditioned (40)', value: '40' },
          { name: 'All-inclusive available', value: '52' },
          { name: 'Any', value: '' },
          { name: 'Bar', value: '15' },
          { name: 'Beach access (11)', value: '11' },
          { name: 'Beach access (20)', value: '20' },
          { name: 'Crib', value: '18' },
          { name: 'EV charger', value: '61' },
          { name: 'Fitness centre', value: '7' },
          { name: 'Free breakfast', value: '9' },
          { name: 'Free parking', value: '1' },
          { name: 'Free Wi-Fi (29)', value: '29' },
          { name: 'Free Wi-Fi (35)', value: '35' },
          { name: 'Hot tub', value: '2' },
          { name: 'Indoor pool', value: '4' },
          { name: 'Kid-friendly (12)', value: '12' },
          { name: 'Kid-friendly (21)', value: '21' },
          { name: 'Outdoor pool', value: '5' },
          { name: 'Parking', value: '3' },
          { name: 'Pet-friendly (19)', value: '19' },
          { name: 'Pet-friendly (24)', value: '24' },
          { name: 'Pool (32)', value: '32' },
          { name: 'Pool (6)', value: '6' },
          { name: 'Restaurant', value: '8' },
          { name: 'Room service', value: '22' },
          { name: 'Spa', value: '10' },
          { name: 'Wheelchair accessible', value: '53' },
        ],
        default: '',
        description: 'Defines a list of amenities that allows multiple categories that are separated by a comma. For example: 1,2. Check the full list of supported Google Hotels amenities values.',
        routing: {
          request: {
            qs: {
              amenities: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Price Max (price_max)',
        name: 'price_max',
        type: 'number',
        typeOptions: {
          minValue: 0,
        },
        default: 0,
        description: 'Defines the maximum price. Default is unlimited.',
        routing: {
          request: {
            qs: {
              price_max: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Price Min (price_min)',
        name: 'price_min',
        type: 'number',
        typeOptions: {
          minValue: 0,
        },
        default: 0,
        description: 'Defines the minimum price. Default is 0.',
        routing: {
          request: {
            qs: {
              price_min: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Property Type (property_type)',
        name: 'property_type',
        type: 'options',
        options: [
          { name: 'Hotel', value: 'hotel' },
          { name: 'Vacation rental', value: 'vacation_rental' },
        ],
        default: 'hotel',
        description: 'Defines the category of accommodation to search for. The hotel option also includes vacation rentals.',
        routing: {
          request: {
            qs: {
              property_type: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Property Types (property_types)',
        name: 'property_types',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Apartment Hotels', value: '21' },
          { name: 'Apartments', value: '1' },
          { name: 'Beach Hotels', value: '12' },
          { name: 'Bed and Breakfasts', value: '19' },
          { name: 'Boutique Hotels', value: '13' },
          { name: 'Bungalows', value: '2' },
          { name: 'Cabins', value: '3' },
          { name: 'Chalets', value: '4' },
          { name: 'Cottages', value: '5' },
          { name: 'Gîtes', value: '6' },
          { name: 'Holiday villages', value: '7' },
          { name: 'Hostels', value: '14' },
          { name: 'Houseboats', value: '9' },
          { name: 'Houses', value: '8' },
          { name: 'Inns', value: '15' },
          { name: 'Japanese-style Business Hotels', value: '23' },
          { name: 'Minshuku', value: '22' },
          { name: 'Motels', value: '16' },
          { name: 'Other (11)', value: '11' },
          { name: 'Other (20)', value: '20' },
          { name: 'Resorts', value: '17' },
          { name: 'Ryokan', value: '24' },
          { name: 'Spa Hotels', value: '18' },
          { name: 'Villas', value: '10' },
        ],
        default: '',
        description: 'Defines a list of property types that allows multiple categories that are separated by a comma. For example: 1,2. Check the full list of supported Google Hotels property_types values.',
        routing: {
          request: {
            qs: {
              property_types: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Rating (rating)',
        name: 'rating',
        type: 'options',
        options: [
          { name: '7', value: '7' },
          { name: '8', value: '8' },
          { name: '9', value: '9' },
          { name: 'Any', value: '' },
        ],
        default: '',
        description: 'Defines the minimum rating of results to return.',
        routing: {
          request: {
            qs: {
              rating: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Sort By (sort_by)',
        name: 'sort_by',
        type: 'options',
        options: [
          { name: 'Highest rating', value: 'highest_rating' },
          { name: 'Lowest price', value: 'lowest_price' },
          { name: 'Most reviewed', value: 'most_reviewed' },
          { name: 'Relevance', value: 'relevance' },
        ],
        default: 'relevance',
        description: 'Defines the sorting order of the results.',
        routing: {
          request: {
            qs: {
              sort_by: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Hotel Filters',
    name: 'hotel_filters',
    type: 'collection',
    placeholder: 'Add Hotel Filters',
    default: {},
    options: [
      {
        displayName: 'Brands (brands)',
        name: 'brands',
        type: 'string',
        default: '',
        description: 'A comma-separated list of hotel brands to include in the search results, allowing users to filter by preferred hotel chains. The possible values can be obtained from the initial request response under the brands[0].id key.',
        routing: {
          request: {
            qs: {
              brands: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Eco Certified (eco_certified)',
        name: 'eco_certified',
        type: 'boolean',
        default: false,
        description: 'Whether to show only eco-certified hotels.',
        routing: {
          request: {
            qs: {
              eco_certified: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'For Displaced Individuals (for_displaced_individuals)',
        name: 'for_displaced_individuals',
        type: 'boolean',
        default: false,
        description: 'Whether to show only hotels available for displaced individuals.',
        routing: {
          request: {
            qs: {
              for_displaced_individuals: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Free Cancellation (free_cancellation)',
        name: 'free_cancellation',
        type: 'boolean',
        default: false,
        description: 'Whether to show only hotels that offer free cancellation on bookings.',
        routing: {
          request: {
            qs: {
              free_cancellation: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Hotel Class (hotel_class)',
        name: 'hotel_class',
        type: 'options',
        options: [
          { name: '2', value: '2' },
          { name: '3', value: '3' },
          { name: '4', value: '4' },
          { name: '5', value: '5' },
          { name: 'Any', value: '' },
        ],
        default: '',
        description: 'Defines the star rating of the hotel. Multiple ratings can be combined with a comma, for example: 4,5.',
        routing: {
          request: {
            qs: {
              hotel_class: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Special Offers (special_offers)',
        name: 'special_offers',
        type: 'boolean',
        default: false,
        description: 'Whether to show only hotels with special offers.',
        routing: {
          request: {
            qs: {
              special_offers: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Vacation Rentals Filters',
    name: 'vacation_rentals_filters',
    type: 'collection',
    placeholder: 'Add Vacation Rentals Filters',
    default: {},
    options: [
      {
        displayName: 'Bathrooms (bathrooms)',
        name: 'bathrooms',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 5,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the minimum number of bathrooms. Default is 0.',
        routing: {
          request: {
            qs: {
              bathrooms: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Bedrooms (bedrooms)',
        name: 'bedrooms',
        type: 'number',
        typeOptions: {
          minValue: 0,
          maxValue: 5,
          numberPrecision: 0,
        },
        default: 0,
        description: 'Defines the minimum number of bedrooms. Default is 0.',
        routing: {
          request: {
            qs: {
              bedrooms: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Number of Guests',
    name: 'number_of_guests',
    type: 'collection',
    placeholder: 'Add Number of Guests',
    default: {},
    options: [
      {
        displayName: 'Adults (adults)',
        name: 'adults',
        type: 'number',
        typeOptions: {
          minValue: 1,
          maxValue: 10,
          numberPrecision: 0,
        },
        default: 2,
        description: 'The number of adults staying in the apartment. Default is 2. For property_type=hotel, the maximum number of guests is 6 (including children). For property_type=vacation_rental, the maximum number is 10.',
        routing: {
          request: {
            qs: {
              adults: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Children Ages (children_ages)',
        name: 'children_ages',
        type: 'string',
        default: '',
        description: 'Defines the ages of children as a comma-separated list, e.g., 2,5 for two children aged 2 and 5. Available age range is 1–17. Note: This parameter is only applicable for property_type=hotel and will be ignored for other property types.',
        routing: {
          request: {
            qs: {
              children_ages: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Next Page Token (next_page_token)',
        name: 'next_page_token',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        description: 'Retrieves the next page of results. Returned in the response when there are more results to display.',
        routing: {
          request: {
            qs: {
              next_page_token: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google_hotels = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google-hotels-api',
};
