import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['google'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Google',
  value: 'google'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Query (q)',
    name: 'q',
    type: 'string',
    required: true,
    default: '',
    description: 'Search terms for Google. Queries can include operators and advanced filters like "machine learning models", site:, inurl:, intitle:, AND, or OR.',
    displayOptions,
    routing: {
      request: {
        qs: {
          q: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Search Query',
    name: 'search_query',
    type: 'collection',
    placeholder: 'Add Search Query',
    default: {},
    options: [
      {
        displayName: 'Kgmid (kgmid)',
        name: 'kgmid',
        type: 'string',
        default: '',
        description: 'Defines a Knowledge Graph identifier (kgmid), representing entities in Google\'s Knowledge Graph. Format: Location Identifier (/m/): Typically followed by 2 to 7 characters. Used primarily to represent specific locations. Find the identifier by searching for the "Freebase ID" on Wikidata. Example: kgmid=/m/02_286 refers to New York. Google Knowledge Graph Identifier (/g/): Typically followed by a longer alphanumeric string. Represents general entities in Google\'s Knowledge Graph. Find details on Wikidata. Example: kgmid=/g/11f555cn8l refers to TikTok.',
        routing: {
          request: {
            qs: {
              kgmid: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Device',
    name: 'device',
    type: 'collection',
    placeholder: 'Add Device',
    default: {},
    options: [
      {
        displayName: 'Device (device)',
        name: 'device',
        type: 'options',
        options: [
          { name: 'Desktop', value: 'desktop' },
          { name: 'Mobile', value: 'mobile' },
          { name: 'Tablet', value: 'tablet' },
        ],
        default: 'desktop',
        description: 'The default parameter desktop defines the search on a desktop device. The mobile parameter defines the search on a mobile device. The tablet parameter defines the search on a tablet device.',
        routing: {
          request: {
            qs: {
              device: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Geographic Location',
    name: 'geographic_location',
    type: 'collection',
    placeholder: 'Add Geographic Location',
    default: {},
    options: [
      {
        displayName: 'Location (location)',
        name: 'location',
        type: 'string',
        default: '',
        description: 'Specifies the canonical location of the search. If multiple locations match your input, the most popular one will be selected. For example, location=New York selects New York,United States, or location=London selects London TV Region,England,United Kingdom.',
        routing: {
          request: {
            qs: {
              location: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Encoded Location (uule)',
        name: 'uule',
        type: 'string',
        default: '',
        description: 'Sets the exact Google-encoded location for the search. Cannot be used together with the location parameter. SearchApi builds it for you when you use the location parameter, but you can provide your own if you want precise control.',
        routing: {
          request: {
            qs: {
              uule: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo', value: 'cg' },
          { name: 'Congo, the Democratic Republic of the', value: 'cd' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote D\'ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cuba', value: 'cu' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guernsey', value: 'gg' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard Island and Mcdonald Islands', value: 'hm' },
          { name: 'Holy See (Vatican City State)', value: 'va' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iran, Islamic Republic of', value: 'ir' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Isle of Man', value: 'im' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jersey', value: 'je' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macao', value: 'mo' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia, Federated States of', value: 'fm' },
          { name: 'Moldova, Republic of', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montenegro', value: 'me' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Myanmar', value: 'mm' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'North Korea', value: 'kp' },
          { name: 'North Macedonia', value: 'mk' },
          { name: 'Northern Mariana Islands', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory, Occupied', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Helena', value: 'sh' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Pierre and Miquelon', value: 'pm' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'rs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and the South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'Sudan', value: 'sd' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Syrian Arab Republic', value: 'sy' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania, United Republic of', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Timor-Leste', value: 'tl' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands, British', value: 'vg' },
          { name: 'Virgin Islands, U.S.', value: 'vi' },
          { name: 'Wallis and Futuna', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: 'us',
        description: 'Defines the country of the search. Defaults to us.',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country Restrict (cr)',
        name: 'cr',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'af' },
          { name: 'Albania', value: 'al' },
          { name: 'Algeria', value: 'dz' },
          { name: 'American Samoa', value: 'as' },
          { name: 'Andorra', value: 'ad' },
          { name: 'Angola', value: 'ao' },
          { name: 'Anguilla', value: 'ai' },
          { name: 'Antarctica', value: 'aq' },
          { name: 'Antigua and Barbuda', value: 'ag' },
          { name: 'Any', value: '' },
          { name: 'Argentina', value: 'ar' },
          { name: 'Armenia', value: 'am' },
          { name: 'Aruba', value: 'aw' },
          { name: 'Australia', value: 'au' },
          { name: 'Austria', value: 'at' },
          { name: 'Azerbaijan', value: 'az' },
          { name: 'Bahamas', value: 'bs' },
          { name: 'Bahrain', value: 'bh' },
          { name: 'Bangladesh', value: 'bd' },
          { name: 'Barbados', value: 'bb' },
          { name: 'Belarus', value: 'by' },
          { name: 'Belgium', value: 'be' },
          { name: 'Belize', value: 'bz' },
          { name: 'Benin', value: 'bj' },
          { name: 'Bermuda', value: 'bm' },
          { name: 'Bhutan', value: 'bt' },
          { name: 'Bolivia', value: 'bo' },
          { name: 'Bosnia and Herzegovina', value: 'ba' },
          { name: 'Botswana', value: 'bw' },
          { name: 'Bouvet Island', value: 'bv' },
          { name: 'Brazil', value: 'br' },
          { name: 'British Indian Ocean Territory', value: 'io' },
          { name: 'Brunei Darussalam', value: 'bn' },
          { name: 'Bulgaria', value: 'bg' },
          { name: 'Burkina Faso', value: 'bf' },
          { name: 'Burundi', value: 'bi' },
          { name: 'Cambodia', value: 'kh' },
          { name: 'Cameroon', value: 'cm' },
          { name: 'Canada', value: 'ca' },
          { name: 'Cape Verde', value: 'cv' },
          { name: 'Cayman Islands', value: 'ky' },
          { name: 'Central African Republic', value: 'cf' },
          { name: 'Chad', value: 'td' },
          { name: 'Chile', value: 'cl' },
          { name: 'China', value: 'cn' },
          { name: 'Christmas Island', value: 'cx' },
          { name: 'Cocos (Keeling) Islands', value: 'cc' },
          { name: 'Colombia', value: 'co' },
          { name: 'Comoros', value: 'km' },
          { name: 'Congo (cd)', value: 'cd' },
          { name: 'Congo (cg)', value: 'cg' },
          { name: 'Cook Islands', value: 'ck' },
          { name: 'Costa Rica', value: 'cr' },
          { name: 'Cote d\'Ivoire', value: 'ci' },
          { name: 'Croatia', value: 'hr' },
          { name: 'Cyprus', value: 'cy' },
          { name: 'Czech Republic', value: 'cz' },
          { name: 'Denmark', value: 'dk' },
          { name: 'Djibouti', value: 'dj' },
          { name: 'Dominica', value: 'dm' },
          { name: 'Dominican Republic', value: 'do' },
          { name: 'East Timor', value: 'tl' },
          { name: 'Ecuador', value: 'ec' },
          { name: 'Egypt', value: 'eg' },
          { name: 'El Salvador', value: 'sv' },
          { name: 'Equatorial Guinea', value: 'gq' },
          { name: 'Eritrea', value: 'er' },
          { name: 'Estonia', value: 'ee' },
          { name: 'Ethiopia', value: 'et' },
          { name: 'Falkland Islands (Malvinas)', value: 'fk' },
          { name: 'Faroe Islands', value: 'fo' },
          { name: 'Fiji', value: 'fj' },
          { name: 'Finland', value: 'fi' },
          { name: 'France', value: 'fr' },
          { name: 'French Guiana', value: 'gf' },
          { name: 'French Polynesia', value: 'pf' },
          { name: 'French Southern Territories', value: 'tf' },
          { name: 'Gabon', value: 'ga' },
          { name: 'Gambia', value: 'gm' },
          { name: 'Georgia', value: 'ge' },
          { name: 'Germany', value: 'de' },
          { name: 'Ghana', value: 'gh' },
          { name: 'Gibraltar', value: 'gi' },
          { name: 'Greece', value: 'gr' },
          { name: 'Greenland', value: 'gl' },
          { name: 'Grenada', value: 'gd' },
          { name: 'Guadeloupe', value: 'gp' },
          { name: 'Guam', value: 'gu' },
          { name: 'Guatemala', value: 'gt' },
          { name: 'Guinea', value: 'gn' },
          { name: 'Guinea-Bissau', value: 'gw' },
          { name: 'Guyana', value: 'gy' },
          { name: 'Haiti', value: 'ht' },
          { name: 'Heard and McDonald Islands', value: 'hm' },
          { name: 'Honduras', value: 'hn' },
          { name: 'Hong Kong', value: 'hk' },
          { name: 'Hungary', value: 'hu' },
          { name: 'Iceland', value: 'is' },
          { name: 'India', value: 'in' },
          { name: 'Indonesia', value: 'id' },
          { name: 'Iraq', value: 'iq' },
          { name: 'Ireland', value: 'ie' },
          { name: 'Israel', value: 'il' },
          { name: 'Italy', value: 'it' },
          { name: 'Jamaica', value: 'jm' },
          { name: 'Japan', value: 'jp' },
          { name: 'Jordan', value: 'jo' },
          { name: 'Kazakhstan', value: 'kz' },
          { name: 'Kenya', value: 'ke' },
          { name: 'Kiribati', value: 'ki' },
          { name: 'Kuwait', value: 'kw' },
          { name: 'Kyrgyzstan', value: 'kg' },
          { name: 'Lao People\'s Democratic Republic', value: 'la' },
          { name: 'Latvia', value: 'lv' },
          { name: 'Lebanon', value: 'lb' },
          { name: 'Lesotho', value: 'ls' },
          { name: 'Liberia', value: 'lr' },
          { name: 'Libya', value: 'ly' },
          { name: 'Liechtenstein', value: 'li' },
          { name: 'Lithuania', value: 'lt' },
          { name: 'Luxembourg', value: 'lu' },
          { name: 'Macau', value: 'mo' },
          { name: 'Macedonia', value: 'mk' },
          { name: 'Madagascar', value: 'mg' },
          { name: 'Malawi', value: 'mw' },
          { name: 'Malaysia', value: 'my' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Mali', value: 'ml' },
          { name: 'Malta', value: 'mt' },
          { name: 'Marshall Islands', value: 'mh' },
          { name: 'Martinique', value: 'mq' },
          { name: 'Mauritania', value: 'mr' },
          { name: 'Mauritius', value: 'mu' },
          { name: 'Mayotte', value: 'yt' },
          { name: 'Mexico', value: 'mx' },
          { name: 'Micronesia', value: 'fm' },
          { name: 'Moldova', value: 'md' },
          { name: 'Monaco', value: 'mc' },
          { name: 'Mongolia', value: 'mn' },
          { name: 'Montserrat', value: 'ms' },
          { name: 'Morocco', value: 'ma' },
          { name: 'Mozambique', value: 'mz' },
          { name: 'Namibia', value: 'na' },
          { name: 'Nauru', value: 'nr' },
          { name: 'Nepal', value: 'np' },
          { name: 'Netherlands', value: 'nl' },
          { name: 'New Caledonia', value: 'nc' },
          { name: 'New Zealand', value: 'nz' },
          { name: 'Nicaragua', value: 'ni' },
          { name: 'Niger', value: 'ne' },
          { name: 'Nigeria', value: 'ng' },
          { name: 'Niue', value: 'nu' },
          { name: 'Norfolk Island', value: 'nf' },
          { name: 'Northern Maria', value: 'mp' },
          { name: 'Norway', value: 'no' },
          { name: 'Oman', value: 'om' },
          { name: 'Pakistan', value: 'pk' },
          { name: 'Palau', value: 'pw' },
          { name: 'Palestinian Territory', value: 'ps' },
          { name: 'Panama', value: 'pa' },
          { name: 'Papua New Guinea', value: 'pg' },
          { name: 'Paraguay', value: 'py' },
          { name: 'Peru', value: 'pe' },
          { name: 'Philippines', value: 'ph' },
          { name: 'Pitcairn', value: 'pn' },
          { name: 'Poland', value: 'pl' },
          { name: 'Portugal', value: 'pt' },
          { name: 'Puerto Rico', value: 'pr' },
          { name: 'Qatar', value: 'qa' },
          { name: 'Reunion', value: 're' },
          { name: 'Romania', value: 'ro' },
          { name: 'Russian Federation', value: 'ru' },
          { name: 'Rwanda', value: 'rw' },
          { name: 'Saint Kitts and Nevis', value: 'kn' },
          { name: 'Saint Lucia', value: 'lc' },
          { name: 'Saint Vincent and the Grenadines', value: 'vc' },
          { name: 'Samoa', value: 'ws' },
          { name: 'San Marino', value: 'sm' },
          { name: 'Sao Tome and Principe', value: 'st' },
          { name: 'Saudi Arabia', value: 'sa' },
          { name: 'Senegal', value: 'sn' },
          { name: 'Serbia and Montenegro', value: 'cs' },
          { name: 'Seychelles', value: 'sc' },
          { name: 'Sierra Leone', value: 'sl' },
          { name: 'Singapore', value: 'sg' },
          { name: 'Slovakia', value: 'sk' },
          { name: 'Slovenia', value: 'si' },
          { name: 'Solomon Islands', value: 'sb' },
          { name: 'Somalia', value: 'so' },
          { name: 'South Africa', value: 'za' },
          { name: 'South Georgia and The South Sandwich Islands', value: 'gs' },
          { name: 'South Korea', value: 'kr' },
          { name: 'Spain', value: 'es' },
          { name: 'Sri Lanka', value: 'lk' },
          { name: 'St. Helena', value: 'sh' },
          { name: 'St. Pierre and Miquelon', value: 'pm' },
          { name: 'Suriname', value: 'sr' },
          { name: 'Svalbard and Jan Mayen Islands', value: 'sj' },
          { name: 'Swaziland', value: 'sz' },
          { name: 'Sweden', value: 'se' },
          { name: 'Switzerland', value: 'ch' },
          { name: 'Taiwan', value: 'tw' },
          { name: 'Tajikistan', value: 'tj' },
          { name: 'Tanzania', value: 'tz' },
          { name: 'Thailand', value: 'th' },
          { name: 'Togo', value: 'tg' },
          { name: 'Tokelau', value: 'tk' },
          { name: 'Tonga', value: 'to' },
          { name: 'Trinidad and Tobago', value: 'tt' },
          { name: 'Tunisia', value: 'tn' },
          { name: 'Turkey', value: 'tr' },
          { name: 'Turkmenistan', value: 'tm' },
          { name: 'Turks and Caicos Islands', value: 'tc' },
          { name: 'Tuvalu', value: 'tv' },
          { name: 'Uganda', value: 'ug' },
          { name: 'Ukraine', value: 'ua' },
          { name: 'United Arab Emirates', value: 'ae' },
          { name: 'United Kingdom (gb)', value: 'gb' },
          { name: 'United Kingdom (uk)', value: 'uk' },
          { name: 'United States', value: 'us' },
          { name: 'United States Minor Outlying Islands', value: 'um' },
          { name: 'Uruguay', value: 'uy' },
          { name: 'Uzbekistan', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vatican', value: 'va' },
          { name: 'Venezuela', value: 've' },
          { name: 'Viet Nam', value: 'vn' },
          { name: 'Virgin Islands (British)', value: 'vg' },
          { name: 'Virgin Islands (U.S.)', value: 'vi' },
          { name: 'Wallis and Futuna Islands', value: 'wf' },
          { name: 'Western Sahara', value: 'eh' },
          { name: 'Yemen', value: 'ye' },
          { name: 'Zambia', value: 'zm' },
          { name: 'Zimbabwe', value: 'zw' },
        ],
        default: '',
        description: 'Restricts search results to documents originating in a particular country. Google determines the country of a document by the top-level domain (TLD) of the document\'s URL or by the web server\'s IP address geographic location.',
        routing: {
          request: {
            qs: {
              cr: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Google Domain (google_domain)',
        name: 'google_domain',
        type: 'string',
        default: 'google.com',
        description: 'As of Apr 15, 2025, Google began phasing out country code top-level domains (ccTLDs). Users visiting local domains like google.de or google.co.uk are now automatically redirected to google.com. For localized searches, use the gl (country), hl (language) or other localization parameters instead.',
        routing: {
          request: {
            qs: {
              google_domain: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bemba', value: 'bem' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bork, bork, bork!', value: 'xx-bork' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Breton', value: 'br' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Cambodian', value: 'km' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cherokee', value: 'chr' },
          { name: 'Chichewa', value: 'ny' },
          { name: 'Chinese (Simplified)', value: 'zh-cn' },
          { name: 'Chinese (Traditional)', value: 'zh-tw' },
          { name: 'Corsican', value: 'co' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dutch', value: 'nl' },
          { name: 'Elmer Fudd', value: 'xx-elmer' },
          { name: 'English', value: 'en' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Faroese', value: 'fo' },
          { name: 'Filipino', value: 'tl' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Frisian', value: 'fy' },
          { name: 'Ga', value: 'gaa' },
          { name: 'Galician', value: 'gl' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Greenlandic', value: 'kl' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Hacker', value: 'xx-hacker' },
          { name: 'Haitian Creole', value: 'ht' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hawaiian', value: 'haw' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Interlingua', value: 'ia' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jw' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Kirundi', value: 'rn' },
          { name: 'Klingon', value: 'xx-klingon' },
          { name: 'Kongo', value: 'kg' },
          { name: 'Korean', value: 'ko' },
          { name: 'Krio (Sierra Leone)', value: 'kri' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kurdish (Soranî)', value: 'ckb' },
          { name: 'Kyrgyz', value: 'ky' },
          { name: 'Laothian', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Lozi', value: 'loz' },
          { name: 'Luganda', value: 'lg' },
          { name: 'Luo', value: 'ach' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maldives', value: 'mv' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Maori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Mauritian Creole', value: 'mfe' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Montenegrin', value: 'sr-me' },
          { name: 'Nepali', value: 'ne' },
          { name: 'Nigerian Pidgin', value: 'pcm' },
          { name: 'Northern Sotho', value: 'nso' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Norwegian (Nynorsk)', value: 'nn' },
          { name: 'Occitan', value: 'oc' },
          { name: 'Oriya', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Persian', value: 'fa' },
          { name: 'Pirate', value: 'xx-pirate' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Portuguese (Brazil)', value: 'pt-br' },
          { name: 'Portuguese (Portugal)', value: 'pt-pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Romansh', value: 'rm' },
          { name: 'Runyakitara', value: 'nyn' },
          { name: 'Russian', value: 'ru' },
          { name: 'Scots Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Sesotho', value: 'st' },
          { name: 'Setswana', value: 'tn' },
          { name: 'Seychellois Creole', value: 'crs' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhalese', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Spanish', value: 'es' },
          { name: 'Spanish (Latin American)', value: 'es-419' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tonga', value: 'to' },
          { name: 'Tshiluba', value: 'lua' },
          { name: 'Tumbuka', value: 'tum' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Twi', value: 'tw' },
          { name: 'Uighur', value: 'ug' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Vanuatu', value: 'vu' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Wolof', value: 'wo' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: 'en',
        description: 'Defines the interface language of the search. Defaults to en.',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language Restrict (lr)',
        name: 'lr',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Arabic', value: 'lang_ar' },
          { name: 'Armenian', value: 'lang_hy' },
          { name: 'Bulgarian', value: 'lang_bg' },
          { name: 'Catalan', value: 'lang_ca' },
          { name: 'Chinese (Simplified)', value: 'lang_zh-CN' },
          { name: 'Chinese (Traditional)', value: 'lang_zh-TW' },
          { name: 'Croatian', value: 'lang_hr' },
          { name: 'Czech', value: 'lang_cs' },
          { name: 'Danish', value: 'lang_da' },
          { name: 'Dutch', value: 'lang_nl' },
          { name: 'English', value: 'lang_en' },
          { name: 'Estonian', value: 'lang_et' },
          { name: 'Filipino', value: 'lang_tl' },
          { name: 'Finnish', value: 'lang_fi' },
          { name: 'French', value: 'lang_fr' },
          { name: 'German', value: 'lang_de' },
          { name: 'Greek', value: 'lang_el' },
          { name: 'Hebrew', value: 'lang_iw' },
          { name: 'Hindi', value: 'lang_hi' },
          { name: 'Hungarian', value: 'lang_hu' },
          { name: 'Icelandic', value: 'lang_is' },
          { name: 'Indonesian', value: 'lang_id' },
          { name: 'Italian', value: 'lang_it' },
          { name: 'Japanese', value: 'lang_ja' },
          { name: 'Korean', value: 'lang_ko' },
          { name: 'Latvian', value: 'lang_lv' },
          { name: 'Lithuanian', value: 'lang_lt' },
          { name: 'Norwegian', value: 'lang_no' },
          { name: 'Persian', value: 'lang_fa' },
          { name: 'Polish', value: 'lang_pl' },
          { name: 'Portuguese', value: 'lang_pt' },
          { name: 'Romanian', value: 'lang_ro' },
          { name: 'Russian', value: 'lang_ru' },
          { name: 'Serbian', value: 'lang_sr' },
          { name: 'Slovak', value: 'lang_sk' },
          { name: 'Slovenian', value: 'lang_sl' },
          { name: 'Spanish', value: 'lang_es' },
          { name: 'Swedish', value: 'lang_sv' },
          { name: 'Thai', value: 'lang_th' },
          { name: 'Turkish', value: 'lang_tr' },
          { name: 'Ukrainian', value: 'lang_uk' },
          { name: 'Vietnamese', value: 'lang_vi' },
        ],
        default: '',
        description: 'Restricts search results to documents written in a particular language or a set of languages. The accepted format is lang_{2-letter language code} — for example, lang_jp for Japanese. To restrict to multiple languages, combine with a pipe: lang_it|lang_de. Google identifies the document language from the URL\'s top-level domain, language meta tags, or the body text.',
        routing: {
          request: {
            qs: {
              lr: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Filter (filter)',
        name: 'filter',
        type: 'options',
        options: [
          { name: 'Disable "Duplicate Content" and "Host Crowding" filters', value: '0' },
          { name: 'Enable "Duplicate Content" and "Host Crowding" filters', value: '1' },
        ],
        default: '1',
        description: 'Controls whether the "Duplicate Content" and "Host Crowding" filters are enabled. Defaults to 1 (enabled).',
        routing: {
          request: {
            qs: {
              filter: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Nfpr (nfpr)',
        name: 'nfpr',
        type: 'options',
        options: [
          { name: 'Exclude auto-corrected results', value: '1' },
          { name: 'Include auto-corrected results', value: '0' },
        ],
        default: '0',
        description: 'Controls whether results from auto-corrected spelling queries are included. Set to 1 to exclude auto-corrected results. Defaults to 0 (auto-corrected results included).',
        routing: {
          request: {
            qs: {
              nfpr: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Safe (safe)',
        name: 'safe',
        type: 'options',
        options: [
          { name: 'Blur explicit images', value: 'blur' },
          { name: 'Disable SafeSearch', value: 'off' },
          { name: 'Enable strict SafeSearch', value: 'active' },
        ],
        default: 'blur',
        description: 'Toggles the SafeSearch feature, which filters adult content from search results using Google\'s proprietary keyword, phrase, and URL analysis. Defaults to blur.',
        routing: {
          request: {
            qs: {
              safe: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Last 1 minute', value: 'last_1_minute' },
          { name: 'Last 15 minutes', value: 'last_15_minutes' },
          { name: 'Last 30 minutes', value: 'last_30_minutes' },
          { name: 'Last 5 minutes', value: 'last_5_minutes' },
          { name: 'Last day', value: 'last_day' },
          { name: 'Last hour', value: 'last_hour' },
          { name: 'Last month', value: 'last_month' },
          { name: 'Last week', value: 'last_week' },
          { name: 'Last year', value: 'last_year' },
        ],
        default: '',
        description: 'Restricts results to URLs based on date. Use time_period_min or time_period_max for a custom date range.',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period Max (time_period_max)',
        name: 'time_period_max',
        type: 'string',
        default: '',
        description: 'Specifies the end of the custom time period. Can be used with time_period_min. Format: MM/DD/YYYY.',
        routing: {
          request: {
            qs: {
              time_period_max: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period Min (time_period_min)',
        name: 'time_period_min',
        type: 'string',
        default: '',
        description: 'Specifies the start of the custom time period. Can be used with time_period_max. Format: MM/DD/YYYY.',
        routing: {
          request: {
            qs: {
              time_period_min: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Verbatim (verbatim)',
        name: 'verbatim',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'True', value: 'true' },
        ],
        default: '',
        description: 'Forces Google to use your exact keywords, bypassing automatic spelling corrections, synonyms, and stemmed variations. Can be combined with time_period filters. Note: Verbatim mode is stricter than nfpr=1 — it disables all query modifications, not just spelling corrections.',
        routing: {
          request: {
            qs: {
              verbatim: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Results Per Page (num)',
        name: 'num',
        type: 'number',
        typeOptions: {
          minValue: 1,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Phased out by Google on September 2025. It is now constant 10.',
        routing: {
          request: {
            qs: {
              num: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Page Number (page)',
        name: 'page',
        type: 'number',
        typeOptions: {
          minValue: 1,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Indicates which page of results to return. Defaults to 1.',
        routing: {
          request: {
            qs: {
              page: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Optimization',
    name: 'optimization',
    type: 'collection',
    placeholder: 'Add Optimization',
    default: {},
    options: [
      {
        displayName: 'Optimization Strategy (optimization_strategy)',
        name: 'optimization_strategy',
        type: 'options',
        options: [
          { name: 'Ad Scraping Rate', value: 'ads' },
          { name: 'Performance', value: 'performance' },
        ],
        default: 'performance',
        description: 'Controls how the search request is optimized. The ads option prioritizes ad collection success rate at the cost of longer processing times.',
        routing: {
          request: {
            qs: {
              optimization_strategy: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const google = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/google',
};
