import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['linkedin_ad_library'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Linkedin Ad Library',
  value: 'linkedin_ad_library'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Params',
    name: 'search_params',
    type: 'collection',
    placeholder: 'Add Search Params',
    default: {},
    options: [
      {
        displayName: 'Advertiser (advertiser)',
        name: 'advertiser',
        type: 'string',
        default: '',
        description: 'Advertiser name or company to search for. Returns ads from that specific advertiser.',
        routing: {
          request: {
            qs: {
              advertiser: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country (country)',
        name: 'country',
        type: 'options',
        options: [
          { name: 'Afghanistan', value: 'AF' },
          { name: 'Aland Islands', value: 'AX' },
          { name: 'Albania', value: 'AL' },
          { name: 'Algeria', value: 'DZ' },
          { name: 'All', value: 'ALL' },
          { name: 'American Samoa', value: 'AS' },
          { name: 'Andorra', value: 'AD' },
          { name: 'Angola', value: 'AO' },
          { name: 'Anguilla', value: 'AI' },
          { name: 'Antarctica', value: 'AQ' },
          { name: 'Antigua and Barbuda', value: 'AG' },
          { name: 'Any', value: '' },
          { name: 'Argentina', value: 'AR' },
          { name: 'Armenia', value: 'AM' },
          { name: 'Aruba', value: 'AW' },
          { name: 'Australia', value: 'AU' },
          { name: 'Austria', value: 'AT' },
          { name: 'Azerbaijan', value: 'AZ' },
          { name: 'Bahamas', value: 'BS' },
          { name: 'Bahrain', value: 'BH' },
          { name: 'Bangladesh', value: 'BD' },
          { name: 'Barbados', value: 'BB' },
          { name: 'Belarus', value: 'BY' },
          { name: 'Belgium', value: 'BE' },
          { name: 'Belize', value: 'BZ' },
          { name: 'Benin', value: 'BJ' },
          { name: 'Bermuda', value: 'BM' },
          { name: 'Bhutan', value: 'BT' },
          { name: 'Bolivia', value: 'BO' },
          { name: 'Bosnia and Herzegovina', value: 'BA' },
          { name: 'Botswana', value: 'BW' },
          { name: 'Bouvet Island', value: 'BV' },
          { name: 'Brazil', value: 'BR' },
          { name: 'British Indian Ocean Territory', value: 'IO' },
          { name: 'Brunei Darussalam', value: 'BN' },
          { name: 'Bulgaria', value: 'BG' },
          { name: 'Burkina Faso', value: 'BF' },
          { name: 'Burundi', value: 'BI' },
          { name: 'Cambodia', value: 'KH' },
          { name: 'Cameroon', value: 'CM' },
          { name: 'Canada', value: 'CA' },
          { name: 'Cape Verde', value: 'CV' },
          { name: 'Caribbean Nations', value: 'CB' },
          { name: 'Cayman Islands', value: 'KY' },
          { name: 'Central African Republic', value: 'CF' },
          { name: 'Chad', value: 'TD' },
          { name: 'Chile', value: 'CL' },
          { name: 'China', value: 'CN' },
          { name: 'Christmas Island', value: 'CX' },
          { name: 'Cocos (Keeling) Islands', value: 'CC' },
          { name: 'Colombia', value: 'CO' },
          { name: 'Comoros', value: 'KM' },
          { name: 'Congo', value: 'CG' },
          { name: 'Cook Islands', value: 'CK' },
          { name: 'Costa Rica', value: 'CR' },
          { name: 'Cote D\'Ivoire (Ivory Coast)', value: 'CI' },
          { name: 'Croatia', value: 'HR' },
          { name: 'Cuba', value: 'CU' },
          { name: 'Cyprus', value: 'CY' },
          { name: 'Czech Republic', value: 'CZ' },
          { name: 'Democratic Republic of the Congo', value: 'CD' },
          { name: 'Denmark', value: 'DK' },
          { name: 'Djibouti', value: 'DJ' },
          { name: 'Dominica', value: 'DM' },
          { name: 'Dominican Republic', value: 'DO' },
          { name: 'East Timor', value: 'TP' },
          { name: 'Ecuador', value: 'EC' },
          { name: 'Egypt', value: 'EG' },
          { name: 'El Salvador', value: 'SV' },
          { name: 'Equatorial Guinea', value: 'GQ' },
          { name: 'Eritrea', value: 'ER' },
          { name: 'Estonia', value: 'EE' },
          { name: 'Ethiopia', value: 'ET' },
          { name: 'Falkland Islands (Malvinas)', value: 'FK' },
          { name: 'Faroe Islands', value: 'FO' },
          { name: 'Federated States of Micronesia', value: 'FM' },
          { name: 'Fiji', value: 'FJ' },
          { name: 'Finland', value: 'FI' },
          { name: 'France', value: 'FR' },
          { name: 'French Guiana', value: 'GF' },
          { name: 'French Polynesia', value: 'PF' },
          { name: 'French Southern Territories', value: 'TF' },
          { name: 'Gabon', value: 'GA' },
          { name: 'Gambia', value: 'GM' },
          { name: 'Georgia', value: 'GE' },
          { name: 'Germany', value: 'DE' },
          { name: 'Ghana', value: 'GH' },
          { name: 'Gibraltar', value: 'GI' },
          { name: 'Greece', value: 'GR' },
          { name: 'Greenland', value: 'GL' },
          { name: 'Grenada', value: 'GD' },
          { name: 'Guadeloupe', value: 'GP' },
          { name: 'Guam', value: 'GU' },
          { name: 'Guatemala', value: 'GT' },
          { name: 'Guernsey', value: 'GG' },
          { name: 'Guinea', value: 'GN' },
          { name: 'Guinea-Bissau', value: 'GW' },
          { name: 'Guyana', value: 'GY' },
          { name: 'Haiti', value: 'HT' },
          { name: 'Heard Island and McDonald Islands', value: 'HM' },
          { name: 'Honduras', value: 'HN' },
          { name: 'Hong Kong', value: 'HK' },
          { name: 'Hungary', value: 'HU' },
          { name: 'Iceland', value: 'IS' },
          { name: 'India', value: 'IN' },
          { name: 'Indonesia', value: 'ID' },
          { name: 'Iran', value: 'IR' },
          { name: 'Iraq', value: 'IQ' },
          { name: 'Ireland', value: 'IE' },
          { name: 'Isle of Man', value: 'IM' },
          { name: 'Israel', value: 'IL' },
          { name: 'Italy', value: 'IT' },
          { name: 'Jamaica', value: 'JM' },
          { name: 'Japan', value: 'JP' },
          { name: 'Jersey', value: 'JE' },
          { name: 'Jordan', value: 'JO' },
          { name: 'Kazakhstan', value: 'KZ' },
          { name: 'Kenya', value: 'KE' },
          { name: 'Kiribati', value: 'KI' },
          { name: 'Korea', value: 'KR' },
          { name: 'Korea (North)', value: 'KP' },
          { name: 'Kosovo', value: 'KO' },
          { name: 'Kuwait', value: 'KW' },
          { name: 'Kyrgyzstan', value: 'KG' },
          { name: 'Laos', value: 'LA' },
          { name: 'Latvia', value: 'LV' },
          { name: 'Lebanon', value: 'LB' },
          { name: 'Lesotho', value: 'LS' },
          { name: 'Liberia', value: 'LR' },
          { name: 'Libya', value: 'LY' },
          { name: 'Liechtenstein', value: 'LI' },
          { name: 'Lithuania', value: 'LT' },
          { name: 'Luxembourg', value: 'LU' },
          { name: 'Macao', value: 'MO' },
          { name: 'Macedonia', value: 'MK' },
          { name: 'Madagascar', value: 'MG' },
          { name: 'Malawi', value: 'MW' },
          { name: 'Malaysia', value: 'MY' },
          { name: 'Maldives', value: 'MV' },
          { name: 'Mali', value: 'ML' },
          { name: 'Malta', value: 'MT' },
          { name: 'Marshall Islands', value: 'MH' },
          { name: 'Martinique', value: 'MQ' },
          { name: 'Mauritania', value: 'MR' },
          { name: 'Mauritius', value: 'MU' },
          { name: 'Mayotte', value: 'YT' },
          { name: 'Mexico', value: 'MX' },
          { name: 'Moldova', value: 'MD' },
          { name: 'Monaco', value: 'MC' },
          { name: 'Mongolia', value: 'MN' },
          { name: 'Montenegro', value: 'ME' },
          { name: 'Montserrat', value: 'MS' },
          { name: 'Morocco', value: 'MA' },
          { name: 'Mozambique', value: 'MZ' },
          { name: 'Myanmar', value: 'MM' },
          { name: 'Namibia', value: 'NA' },
          { name: 'Nauru', value: 'NR' },
          { name: 'Nepal', value: 'NP' },
          { name: 'Netherlands', value: 'NL' },
          { name: 'Netherlands Antilles', value: 'AN' },
          { name: 'New Caledonia', value: 'NC' },
          { name: 'New Zealand', value: 'NZ' },
          { name: 'Nicaragua', value: 'NI' },
          { name: 'Niger', value: 'NE' },
          { name: 'Nigeria', value: 'NG' },
          { name: 'Niue', value: 'NU' },
          { name: 'Norfolk Island', value: 'NF' },
          { name: 'Northern Mariana Islands', value: 'MP' },
          { name: 'Norway', value: 'NO' },
          { name: 'Pakistan', value: 'PK' },
          { name: 'Palau', value: 'PW' },
          { name: 'Palestinian Territory', value: 'PS' },
          { name: 'Panama', value: 'PA' },
          { name: 'Papua New Guinea', value: 'PG' },
          { name: 'Paraguay', value: 'PY' },
          { name: 'Peru', value: 'PE' },
          { name: 'Philippines', value: 'PH' },
          { name: 'Pitcairn', value: 'PN' },
          { name: 'Poland', value: 'PL' },
          { name: 'Portugal', value: 'PT' },
          { name: 'Puerto Rico', value: 'PR' },
          { name: 'Qatar', value: 'QA' },
          { name: 'Reunion', value: 'RE' },
          { name: 'Romania', value: 'RO' },
          { name: 'Russian Federation', value: 'RU' },
          { name: 'Rwanda', value: 'RW' },
          { name: 'S. Georgia and S. Sandwich Islands', value: 'GS' },
          { name: 'Saint Helena', value: 'SH' },
          { name: 'Saint Kitts and Nevis', value: 'KN' },
          { name: 'Saint Lucia', value: 'LC' },
          { name: 'Saint Pierre and Miquelon', value: 'PM' },
          { name: 'Saint Vincent and the Grenadines', value: 'VC' },
          { name: 'Samoa', value: 'WS' },
          { name: 'San Marino', value: 'SM' },
          { name: 'Sao Tome and Principe', value: 'ST' },
          { name: 'Saudi Arabia', value: 'SA' },
          { name: 'Senegal', value: 'SN' },
          { name: 'Serbia', value: 'RS' },
          { name: 'Serbia and Montenegro', value: 'CS' },
          { name: 'Seychelles', value: 'SC' },
          { name: 'Sierra Leone', value: 'SL' },
          { name: 'Singapore', value: 'SG' },
          { name: 'Slovak Republic', value: 'SK' },
          { name: 'Slovenia', value: 'SI' },
          { name: 'Solomon Islands', value: 'SB' },
          { name: 'Somalia', value: 'SO' },
          { name: 'South Africa', value: 'ZA' },
          { name: 'South Sudan', value: 'SS' },
          { name: 'Spain', value: 'ES' },
          { name: 'Sri Lanka', value: 'LK' },
          { name: 'Sudan', value: 'SD' },
          { name: 'Sultanate of Oman', value: 'OM' },
          { name: 'Suriname', value: 'SR' },
          { name: 'Svalbard and Jan Mayen', value: 'SJ' },
          { name: 'Swaziland', value: 'SZ' },
          { name: 'Sweden', value: 'SE' },
          { name: 'Switzerland', value: 'CH' },
          { name: 'Syria', value: 'SY' },
          { name: 'Taiwan', value: 'TW' },
          { name: 'Tajikistan', value: 'TJ' },
          { name: 'Tanzania', value: 'TZ' },
          { name: 'Thailand', value: 'TH' },
          { name: 'Timor-Leste', value: 'TL' },
          { name: 'Togo', value: 'TG' },
          { name: 'Tokelau', value: 'TK' },
          { name: 'Tonga', value: 'TO' },
          { name: 'Trinidad and Tobago', value: 'TT' },
          { name: 'Tunisia', value: 'TN' },
          { name: 'Turkey', value: 'TR' },
          { name: 'Turkmenistan', value: 'TM' },
          { name: 'Turks and Caicos Islands', value: 'TC' },
          { name: 'Tuvalu', value: 'TV' },
          { name: 'Uganda', value: 'UG' },
          { name: 'Ukraine', value: 'UA' },
          { name: 'United Arab Emirates', value: 'AE' },
          { name: 'United Kingdom', value: 'GB' },
          { name: 'United States', value: 'US' },
          { name: 'Uruguay', value: 'UY' },
          { name: 'Uzbekistan', value: 'UZ' },
          { name: 'Vanuatu', value: 'VU' },
          { name: 'Vatican City State (Holy See)', value: 'VA' },
          { name: 'Venezuela', value: 'VE' },
          { name: 'Vietnam', value: 'VN' },
          { name: 'Virgin Islands (British)', value: 'VG' },
          { name: 'Virgin Islands (U.S.)', value: 'VI' },
          { name: 'Wallis and Futuna', value: 'WF' },
          { name: 'Western Sahara', value: 'EH' },
          { name: 'Yemen', value: 'YE' },
          { name: 'Yugoslavia', value: 'YU' },
          { name: 'Zambia', value: 'ZM' },
          { name: 'Zimbabwe', value: 'ZW' },
        ],
        default: '',
        description: 'Country to filter ads by. Use comma-separated values for multiple countries (e.g., \'US,CA,GB\').',
        routing: {
          request: {
            qs: {
              country: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Keyword (q)',
        name: 'q',
        type: 'string',
        default: '',
        description: 'Search for ads containing specific keywords or phrases',
        routing: {
          request: {
            qs: {
              q: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'string',
        default: '',
        description: 'Use predefined values like last_year, this_year, this_month, last_30_days, or a custom date range in format YYYY-MM-DD..YYYY-MM-DD',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Next Page Token (next_page_token)',
        name: 'next_page_token',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        description: 'A token for fetching the next set of results. Obtained from the next_page_token field in the previous response.',
        routing: {
          request: {
            qs: {
              next_page_token: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const linkedin_ad_library = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/linkedin-ad-library-api',
};
