import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['meta_ad_library'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Meta Ad Library',
  value: 'meta_ad_library'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Params',
    name: 'search_params',
    type: 'collection',
    placeholder: 'Add Search Params',
    default: {},
    options: [
      {
        displayName: 'Location ID (location_id)',
        name: 'location_id',
        type: 'string',
        default: '',
        description: 'Filters ads based on a specific geographic location using Meta Ad Library\'s location targeting feature. This parameter must be used together with location_name and location_type to define the targeted area. All three values can be obtained using our Page Search API, which supports location search aligned with Meta Ad Library\'s internal targeting system.',
        routing: {
          request: {
            qs: {
              location_id: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Page ID (page_id)',
        name: 'page_id',
        type: 'string',
        default: '',
        description: 'Specifies the page\'s unique ID. You can obtain the page_id in two ways: Use our Page Search API to retrieve the page ID directly from Meta Ad Library. Inspect the URL from the Meta Ad Library website and locate the view_all_page_id parameter. When present, in the response there are additional fields ad_library_page_info and page blocks.',
        routing: {
          request: {
            qs: {
              page_id: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Search Query (q)',
        name: 'q',
        type: 'string',
        default: '',
        description: 'Defines the keyword for your search. When present together with page_id or location_id, it will filter that page or location for the keyword. If you want to search for exact match, use "" to enclose the keyword.',
        routing: {
          request: {
            qs: {
              q: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Content Languages (content_languages)',
        name: 'content_languages',
        type: 'options',
        options: [
          { name: 'Abkhazian', value: 'ab' },
          { name: 'Afar', value: 'aa' },
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Any', value: '' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Aragonese', value: 'an' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Assamese', value: 'as' },
          { name: 'Avaric', value: 'av' },
          { name: 'Avestan', value: 'ae' },
          { name: 'Aymara', value: 'ay' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Bambara', value: 'bm' },
          { name: 'Bangla', value: 'bl' },
          { name: 'Bashkir', value: 'ba' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bengali', value: 'bn' },
          { name: 'Bihari', value: 'bh' },
          { name: 'Bislama', value: 'bi' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Breton', value: 'br' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cebuano', value: 'cx' },
          { name: 'Chamorro', value: 'ch' },
          { name: 'Chechen', value: 'ce' },
          { name: 'Cherokee', value: 'ck' },
          { name: 'Chichewa', value: 'ny' },
          { name: 'Chinese', value: 'zh' },
          { name: 'Chinese (Cantonese)', value: 'yue' },
          { name: 'Chinese (Mandarin)', value: 'cmn' },
          { name: 'Church Slavic', value: 'cu' },
          { name: 'Chuvash', value: 'cv' },
          { name: 'Cornish', value: 'kw' },
          { name: 'Corsican', value: 'co' },
          { name: 'Cree', value: 'cr' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Dari', value: 'dr' },
          { name: 'Divehi', value: 'dv' },
          { name: 'Dutch', value: 'nl' },
          { name: 'Dzongkha', value: 'dz' },
          { name: 'Egyptian/Sudanese Arabic', value: 'arz' },
          { name: 'English', value: 'en' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Faroese', value: 'fo' },
          { name: 'Fijian', value: 'fj' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Fulah', value: 'ff' },
          { name: 'Galician', value: 'gl' },
          { name: 'Ganda', value: 'lg' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Haitian', value: 'ht' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hebrew', value: 'he' },
          { name: 'Herero', value: 'hz' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hiri Motu', value: 'ho' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Ido', value: 'io' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Interlingua', value: 'ia' },
          { name: 'Interlingue', value: 'ie' },
          { name: 'Inuktitut', value: 'iu' },
          { name: 'Inupiaq', value: 'ik' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jv' },
          { name: 'Kalaallisut', value: 'kl' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kanuri', value: 'kr' },
          { name: 'Kashmiri', value: 'ks' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Khmer', value: 'km' },
          { name: 'Kikuyu', value: 'ki' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Kirghiz', value: 'ky' },
          { name: 'Kirundi', value: 'rn' },
          { name: 'Komi', value: 'kv' },
          { name: 'Kongo', value: 'kg' },
          { name: 'Korean', value: 'ko' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kwanyama', value: 'kj' },
          { name: 'Lao', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Levantine Arabic', value: 'apc' },
          { name: 'Limburgish', value: 'li' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Luba-Katanga', value: 'lu' },
          { name: 'Luxembourgish', value: 'lb' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Maghrebi Arabic', value: 'ary' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Manx', value: 'gv' },
          { name: 'Maori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Marshallese', value: 'mh' },
          { name: 'Mesopotamian Arabic', value: 'acm' },
          { name: 'Modern Standard Arabic', value: 'arb' },
          { name: 'Moldavian', value: 'mo' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Moore/Mossi', value: 'mos' },
          { name: 'Nauru', value: 'na' },
          { name: 'Navajo', value: 'nv' },
          { name: 'Ndonga', value: 'ng' },
          { name: 'Nepali', value: 'ne' },
          { name: 'North Ndebele', value: 'nd' },
          { name: 'Northern Sami', value: 'se' },
          { name: 'Northern Sotho', value: 'ns' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Norwegian (bokmal)', value: 'nb' },
          { name: 'Norwegian (nynorsk)', value: 'nn' },
          { name: 'Occitan', value: 'oc' },
          { name: 'Ojibwa', value: 'oj' },
          { name: 'Oriya', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Ossetian', value: 'os' },
          { name: 'Pali', value: 'pi' },
          { name: 'Panjabi', value: 'pa' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Peninsular Arabic (Gulf)', value: 'ars' },
          { name: 'Persian', value: 'fa' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Raeto-Romance', value: 'rm' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Russian', value: 'ru' },
          { name: 'Rusyn', value: 'ry' },
          { name: 'Samoan', value: 'sm' },
          { name: 'Sango', value: 'sg' },
          { name: 'Sanskrit', value: 'sa' },
          { name: 'Sardinian', value: 'sc' },
          { name: 'Scottish Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Serbo-Croatian', value: 'sh' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sichuan Yi', value: 'ii' },
          { name: 'Sicilian', value: 'ci' },
          { name: 'Silesian', value: 'sz' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhalese', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Sorani Kurdish', value: 'cb' },
          { name: 'Sotho', value: 'st' },
          { name: 'South Ndebele', value: 'nr' },
          { name: 'Spanish', value: 'es' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swati', value: 'ss' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Syriac', value: 'sy' },
          { name: 'Tagalog', value: 'tl' },
          { name: 'Tahitian', value: 'ty' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamazight', value: 'tz' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tibetan', value: 'bo' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tok Pisin', value: 'tpi' },
          { name: 'Tonga', value: 'to' },
          { name: 'Tsonga', value: 'ts' },
          { name: 'Tswana', value: 'tn' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Twi', value: 'tw' },
          { name: 'Uighur', value: 'ug' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Unknown', value: 'xx' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Venda', value: 've' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Volapuk', value: 'vo' },
          { name: 'Walloon', value: 'wa' },
          { name: 'Waray', value: 'wy' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Western Frisian', value: 'fy' },
          { name: 'Wolof', value: 'wo' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zazaki', value: 'zz' },
          { name: 'Zhuang', value: 'za' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: '',
        description: 'Comma-separated list of content languages to filter ads by. Check the full list of supported Meta Ad Library content languages.',
        routing: {
          request: {
            qs: {
              content_languages: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Country (country)',
        name: 'country',
        type: 'options',
        options: [
          { name: 'AD', value: 'AD' },
          { name: 'AE', value: 'AE' },
          { name: 'AF', value: 'AF' },
          { name: 'AG', value: 'AG' },
          { name: 'AI', value: 'AI' },
          { name: 'AL', value: 'AL' },
          { name: 'All', value: 'ALL' },
          { name: 'AM', value: 'AM' },
          { name: 'AN', value: 'AN' },
          { name: 'Any', value: '' },
          { name: 'AO', value: 'AO' },
          { name: 'AQ', value: 'AQ' },
          { name: 'AR', value: 'AR' },
          { name: 'AS', value: 'AS' },
          { name: 'AT', value: 'AT' },
          { name: 'AU', value: 'AU' },
          { name: 'AW', value: 'AW' },
          { name: 'AX', value: 'AX' },
          { name: 'AZ', value: 'AZ' },
          { name: 'BA', value: 'BA' },
          { name: 'BB', value: 'BB' },
          { name: 'BD', value: 'BD' },
          { name: 'BE', value: 'BE' },
          { name: 'BF', value: 'BF' },
          { name: 'BG', value: 'BG' },
          { name: 'BH', value: 'BH' },
          { name: 'BI', value: 'BI' },
          { name: 'BJ', value: 'BJ' },
          { name: 'BL', value: 'BL' },
          { name: 'BM', value: 'BM' },
          { name: 'BN', value: 'BN' },
          { name: 'BO', value: 'BO' },
          { name: 'BQ', value: 'BQ' },
          { name: 'BR', value: 'BR' },
          { name: 'BS', value: 'BS' },
          { name: 'BT', value: 'BT' },
          { name: 'BV', value: 'BV' },
          { name: 'BW', value: 'BW' },
          { name: 'BY', value: 'BY' },
          { name: 'BZ', value: 'BZ' },
          { name: 'CA', value: 'CA' },
          { name: 'CC', value: 'CC' },
          { name: 'CD', value: 'CD' },
          { name: 'CF', value: 'CF' },
          { name: 'CG', value: 'CG' },
          { name: 'CH', value: 'CH' },
          { name: 'CI', value: 'CI' },
          { name: 'CK', value: 'CK' },
          { name: 'CL', value: 'CL' },
          { name: 'CM', value: 'CM' },
          { name: 'CN', value: 'CN' },
          { name: 'CO', value: 'CO' },
          { name: 'CR', value: 'CR' },
          { name: 'CV', value: 'CV' },
          { name: 'CW', value: 'CW' },
          { name: 'CX', value: 'CX' },
          { name: 'CY', value: 'CY' },
          { name: 'CZ', value: 'CZ' },
          { name: 'DE', value: 'DE' },
          { name: 'DJ', value: 'DJ' },
          { name: 'DK', value: 'DK' },
          { name: 'DM', value: 'DM' },
          { name: 'DO', value: 'DO' },
          { name: 'DZ', value: 'DZ' },
          { name: 'EC', value: 'EC' },
          { name: 'EE', value: 'EE' },
          { name: 'EG', value: 'EG' },
          { name: 'EH', value: 'EH' },
          { name: 'ER', value: 'ER' },
          { name: 'ES', value: 'ES' },
          { name: 'ET', value: 'ET' },
          { name: 'FI', value: 'FI' },
          { name: 'FJ', value: 'FJ' },
          { name: 'FK', value: 'FK' },
          { name: 'FM', value: 'FM' },
          { name: 'FO', value: 'FO' },
          { name: 'FR', value: 'FR' },
          { name: 'GA', value: 'GA' },
          { name: 'GB', value: 'GB' },
          { name: 'GD', value: 'GD' },
          { name: 'GE', value: 'GE' },
          { name: 'GF', value: 'GF' },
          { name: 'GG', value: 'GG' },
          { name: 'GH', value: 'GH' },
          { name: 'GI', value: 'GI' },
          { name: 'GL', value: 'GL' },
          { name: 'GM', value: 'GM' },
          { name: 'GN', value: 'GN' },
          { name: 'GP', value: 'GP' },
          { name: 'GQ', value: 'GQ' },
          { name: 'GR', value: 'GR' },
          { name: 'GS', value: 'GS' },
          { name: 'GT', value: 'GT' },
          { name: 'GU', value: 'GU' },
          { name: 'GW', value: 'GW' },
          { name: 'GY', value: 'GY' },
          { name: 'HK', value: 'HK' },
          { name: 'HM', value: 'HM' },
          { name: 'HN', value: 'HN' },
          { name: 'HR', value: 'HR' },
          { name: 'HT', value: 'HT' },
          { name: 'HU', value: 'HU' },
          { name: 'ID', value: 'ID' },
          { name: 'IE', value: 'IE' },
          { name: 'IL', value: 'IL' },
          { name: 'IM', value: 'IM' },
          { name: 'IN', value: 'IN' },
          { name: 'IO', value: 'IO' },
          { name: 'IQ', value: 'IQ' },
          { name: 'IS', value: 'IS' },
          { name: 'IT', value: 'IT' },
          { name: 'JE', value: 'JE' },
          { name: 'JM', value: 'JM' },
          { name: 'JO', value: 'JO' },
          { name: 'JP', value: 'JP' },
          { name: 'KE', value: 'KE' },
          { name: 'KG', value: 'KG' },
          { name: 'KH', value: 'KH' },
          { name: 'KI', value: 'KI' },
          { name: 'KM', value: 'KM' },
          { name: 'KN', value: 'KN' },
          { name: 'KR', value: 'KR' },
          { name: 'KW', value: 'KW' },
          { name: 'KY', value: 'KY' },
          { name: 'KZ', value: 'KZ' },
          { name: 'LA', value: 'LA' },
          { name: 'LB', value: 'LB' },
          { name: 'LC', value: 'LC' },
          { name: 'LI', value: 'LI' },
          { name: 'LK', value: 'LK' },
          { name: 'LR', value: 'LR' },
          { name: 'LS', value: 'LS' },
          { name: 'LT', value: 'LT' },
          { name: 'LU', value: 'LU' },
          { name: 'LV', value: 'LV' },
          { name: 'LY', value: 'LY' },
          { name: 'MA', value: 'MA' },
          { name: 'MC', value: 'MC' },
          { name: 'MD', value: 'MD' },
          { name: 'ME', value: 'ME' },
          { name: 'MF', value: 'MF' },
          { name: 'MG', value: 'MG' },
          { name: 'MH', value: 'MH' },
          { name: 'MK', value: 'MK' },
          { name: 'ML', value: 'ML' },
          { name: 'MM', value: 'MM' },
          { name: 'MN', value: 'MN' },
          { name: 'MO', value: 'MO' },
          { name: 'MP', value: 'MP' },
          { name: 'MQ', value: 'MQ' },
          { name: 'MR', value: 'MR' },
          { name: 'MS', value: 'MS' },
          { name: 'MT', value: 'MT' },
          { name: 'MU', value: 'MU' },
          { name: 'MV', value: 'MV' },
          { name: 'MW', value: 'MW' },
          { name: 'MX', value: 'MX' },
          { name: 'MY', value: 'MY' },
          { name: 'MZ', value: 'MZ' },
          { name: 'NA', value: 'NA' },
          { name: 'NC', value: 'NC' },
          { name: 'NE', value: 'NE' },
          { name: 'NF', value: 'NF' },
          { name: 'NG', value: 'NG' },
          { name: 'NI', value: 'NI' },
          { name: 'NL', value: 'NL' },
          { name: 'NO', value: 'NO' },
          { name: 'NP', value: 'NP' },
          { name: 'NR', value: 'NR' },
          { name: 'NU', value: 'NU' },
          { name: 'NZ', value: 'NZ' },
          { name: 'OM', value: 'OM' },
          { name: 'PA', value: 'PA' },
          { name: 'PE', value: 'PE' },
          { name: 'PF', value: 'PF' },
          { name: 'PG', value: 'PG' },
          { name: 'PH', value: 'PH' },
          { name: 'PK', value: 'PK' },
          { name: 'PL', value: 'PL' },
          { name: 'PM', value: 'PM' },
          { name: 'PN', value: 'PN' },
          { name: 'PR', value: 'PR' },
          { name: 'PS', value: 'PS' },
          { name: 'PT', value: 'PT' },
          { name: 'PW', value: 'PW' },
          { name: 'PY', value: 'PY' },
          { name: 'QA', value: 'QA' },
          { name: 'RE', value: 'RE' },
          { name: 'RO', value: 'RO' },
          { name: 'RS', value: 'RS' },
          { name: 'RU', value: 'RU' },
          { name: 'RW', value: 'RW' },
          { name: 'SA', value: 'SA' },
          { name: 'SB', value: 'SB' },
          { name: 'SC', value: 'SC' },
          { name: 'SE', value: 'SE' },
          { name: 'SG', value: 'SG' },
          { name: 'SH', value: 'SH' },
          { name: 'SI', value: 'SI' },
          { name: 'SJ', value: 'SJ' },
          { name: 'SK', value: 'SK' },
          { name: 'SL', value: 'SL' },
          { name: 'SM', value: 'SM' },
          { name: 'SN', value: 'SN' },
          { name: 'SO', value: 'SO' },
          { name: 'SR', value: 'SR' },
          { name: 'SS', value: 'SS' },
          { name: 'ST', value: 'ST' },
          { name: 'SV', value: 'SV' },
          { name: 'SX', value: 'SX' },
          { name: 'SZ', value: 'SZ' },
          { name: 'TC', value: 'TC' },
          { name: 'TD', value: 'TD' },
          { name: 'TF', value: 'TF' },
          { name: 'TG', value: 'TG' },
          { name: 'TH', value: 'TH' },
          { name: 'TJ', value: 'TJ' },
          { name: 'TK', value: 'TK' },
          { name: 'TL', value: 'TL' },
          { name: 'TM', value: 'TM' },
          { name: 'TN', value: 'TN' },
          { name: 'TO', value: 'TO' },
          { name: 'TR', value: 'TR' },
          { name: 'TT', value: 'TT' },
          { name: 'TV', value: 'TV' },
          { name: 'TW', value: 'TW' },
          { name: 'TZ', value: 'TZ' },
          { name: 'UA', value: 'UA' },
          { name: 'UG', value: 'UG' },
          { name: 'UM', value: 'UM' },
          { name: 'US', value: 'US' },
          { name: 'UY', value: 'UY' },
          { name: 'UZ', value: 'UZ' },
          { name: 'VA', value: 'VA' },
          { name: 'VC', value: 'VC' },
          { name: 'VE', value: 'VE' },
          { name: 'VG', value: 'VG' },
          { name: 'VI', value: 'VI' },
          { name: 'VN', value: 'VN' },
          { name: 'VU', value: 'VU' },
          { name: 'WF', value: 'WF' },
          { name: 'WS', value: 'WS' },
          { name: 'XK', value: 'XK' },
          { name: 'YE', value: 'YE' },
          { name: 'YT', value: 'YT' },
          { name: 'ZA', value: 'ZA' },
          { name: 'ZM', value: 'ZM' },
          { name: 'ZW', value: 'ZW' },
        ],
        default: '',
        description: 'Specifies the country for your search. The default value is ALL. Check the full list of supported Meta Ad Library countries and their supported ad_type.',
        routing: {
          request: {
            qs: {
              country: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Active Status (active_status)',
        name: 'active_status',
        type: 'options',
        options: [
          { name: 'Active', value: 'active' },
          { name: 'All', value: 'all' },
          { name: 'Any', value: '' },
          { name: 'Inactive', value: 'inactive' },
        ],
        default: '',
        description: 'Filters ads by their status. Default is active. Supported values include: active, inactive, all.',
        routing: {
          request: {
            qs: {
              active_status: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Ad Type (ad_type)',
        name: 'ad_type',
        type: 'options',
        options: [
          { name: 'All', value: 'all' },
          { name: 'Any', value: '' },
          { name: 'Credit ads', value: 'credit_ads' },
          { name: 'Employment ads', value: 'employment_ads' },
          { name: 'Housing ads', value: 'housing_ads' },
          { name: 'Political and issue ads', value: 'political_and_issue_ads' },
        ],
        default: '',
        description: 'Specifies the type of ads to return. Default is all. Supported values include: all, political_and_issue_ads, housing_ads, employment_ads, credit_ads. Note: Availability may depend on the selected country. Check the full list of supported Meta Ad Library countries and their supported ad_type.',
        routing: {
          request: {
            qs: {
              ad_type: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'End Date (end_date)',
        name: 'end_date',
        type: 'string',
        default: '',
        description: 'The latest date to include ads from, in format YYYY-MM-DD',
        routing: {
          request: {
            qs: {
              end_date: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Media Type (media_type)',
        name: 'media_type',
        type: 'options',
        options: [
          { name: 'All', value: 'all' },
          { name: 'Any', value: '' },
          { name: 'Image', value: 'image' },
          { name: 'Image and meme', value: 'image_and_meme' },
          { name: 'Meme', value: 'meme' },
          { name: 'None', value: 'none' },
          { name: 'Video', value: 'video' },
        ],
        default: '',
        description: 'Filters results based on media type. Default is all. Supported values are: all, video, image, meme, image_and_meme, none.',
        routing: {
          request: {
            qs: {
              media_type: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Platforms (platforms)',
        name: 'platforms',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Audience network', value: 'audience_network' },
          { name: 'Facebook', value: 'facebook' },
          { name: 'Instagram', value: 'instagram' },
          { name: 'Messenger', value: 'messenger' },
          { name: 'Threads', value: 'threads' },
        ],
        default: '',
        description: 'Comma-separated list of platforms where the ads appear. Supported values include: facebook, instagram, audience_network, messenger, threads.',
        routing: {
          request: {
            qs: {
              platforms: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Sort By (sort_by)',
        name: 'sort_by',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Impressions high to low', value: 'impressions_high_to_low' },
          { name: 'Most recent', value: 'most_recent' },
        ],
        default: '',
        description: 'Specifies the sort order of results. Supported values are: most_recent, impressions_high_to_low. Default is impressions_high_to_low.',
        routing: {
          request: {
            qs: {
              sort_by: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Start Date (start_date)',
        name: 'start_date',
        type: 'string',
        default: '',
        description: 'The earliest date to include ads from, in format YYYY-MM-DD',
        routing: {
          request: {
            qs: {
              start_date: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Next Page Token (next_page_token)',
        name: 'next_page_token',
        type: 'string',
        typeOptions: { password: true },
        default: '',
        description: 'A token for fetching the next set of results. You can obtain this token from the next_page_token field in the previous response. Note: Tokens can grow large (8KB+) after several pages. If you encounter 413 or 414 errors, use a POST request with the token in the JSON body instead of the URL query string.',
        routing: {
          request: {
            qs: {
              next_page_token: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const meta_ad_library = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/meta-ad-library-api',
};
