import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['yandex'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Yandex',
  value: 'yandex'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Search Query (q)',
    name: 'q',
    type: 'string',
    required: true,
    default: '',
    description: 'Terms you want to search on Yandex. Queries can include operators and advanced filters like "machine learning models".',
    displayOptions,
    routing: {
      request: {
        qs: {
          q: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Language (lang)',
        name: 'lang',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Belarusian', value: 'be' },
          { name: 'English', value: 'en' },
          { name: 'Estonian', value: 'et' },
          { name: 'French', value: 'fr' },
          { name: 'German', value: 'de' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Russian', value: 'ru' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Uzbek', value: 'uz' },
        ],
        default: '',
        description: 'Interface language of the search',
        routing: {
          request: {
            qs: {
              lang: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Location (location)',
        name: 'location',
        type: 'options',
        options: [
          { name: 'Abakan', value: '1095' },
          { name: 'Abkhazia', value: '29386' },
          { name: 'Achinsk', value: '11302' },
          { name: 'Africa', value: '241' },
          { name: 'Akmola oblast', value: '29403' },
          { name: 'Akmola Province / Universal', value: '102515' },
          { name: 'Akmola region / Other', value: '102501' },
          { name: 'Aktobe', value: '20273' },
          { name: 'Aktobe oblast', value: '29404' },
          { name: 'Aktobe region / Other', value: '102508' },
          { name: 'Aktobe region / Universal', value: '102522' },
          { name: 'Alexandrov', value: '10656' },
          { name: 'Almaty', value: '162' },
          { name: 'Almaty Province / Universal', value: '102513' },
          { name: 'Almaty region', value: '29406' },
          { name: 'Almaty region / Other', value: '102499' },
          { name: 'Almetyevsk', value: '11121' },
          { name: 'Altai Republic / Other', value: '21809' },
          { name: 'Altai Republic / Universal', value: '21808' },
          { name: 'Altai Territory', value: '11235' },
          { name: 'Altay / Other', value: '21797' },
          { name: 'Altay / Universal', value: '21796' },
          { name: 'Alushta', value: '11471' },
          { name: 'Amur Region / Other', value: '21792' },
          { name: 'Amur Region / Universal', value: '21791' },
          { name: 'Amurskaya oblast', value: '11375' },
          { name: 'Anadyr', value: '11458' },
          { name: 'Anapa', value: '1107' },
          { name: 'Angarsk', value: '11256' },
          { name: 'Any', value: '' },
          { name: 'Apatity', value: '10894' },
          { name: 'Arctic and Antarctic', value: '245' },
          { name: 'Argentina', value: '93' },
          { name: 'Arkhangelsk Oblast', value: '10842' },
          { name: 'Arkhangelsk region / Other', value: '21895' },
          { name: 'Arkhangelskaya region / Universal', value: '21894' },
          { name: 'Armavir', value: '10987' },
          { name: 'Armenia', value: '168' },
          { name: 'Arzamas', value: '11080' },
          { name: 'Asia', value: '183' },
          { name: 'Asia / Others', value: '797' },
          { name: 'Asia / Universal', value: '798' },
          { name: 'Astana', value: '163' },
          { name: 'Astrakhan region / Other', value: '21867' },
          { name: 'Astrakhan region / Universal', value: '21866' },
          { name: 'Atlanta', value: '86' },
          { name: 'Atyrau region', value: '29407' },
          { name: 'Atyrau region / Other', value: '102509' },
          { name: 'Atyrau region / Universal', value: '102523' },
          { name: 'Australia', value: '211' },
          { name: 'Australia and Oceania', value: '138' },
          { name: 'Australia and Oceania / Others', value: '829' },
          { name: 'Australia and Oceania / Universal', value: '830' },
          { name: 'Austria', value: '113' },
          { name: 'Azerbaijan', value: '167' },
          { name: 'Balakovo', value: '11143' },
          { name: 'Balashikha', value: '10716' },
          { name: 'Balti', value: '10314' },
          { name: 'Baltic Countries / Other', value: '981' },
          { name: 'Baltic Countries / Universal', value: '982' },
          { name: 'Baltic States', value: '980' },
          { name: 'Barnaul', value: '197' },
          { name: 'Bashkortostan', value: '11111' },
          { name: 'Beer Sheva', value: '129' },
          { name: 'Belarus', value: '149' },
          { name: 'Belarus / Other', value: '893' },
          { name: 'Belarus / Universal', value: '894' },
          { name: 'Belgium', value: '114' },
          { name: 'Belgorod', value: '4' },
          { name: 'Belgorod region', value: '10645' },
          { name: 'Belgorod region / Other', value: '21911' },
          { name: 'Belgorod region / Universal', value: '21910' },
          { name: 'Belogorsk', value: '11374' },
          { name: 'Bender', value: '10315' },
          { name: 'Berdsk', value: '11314' },
          { name: 'Berlin', value: '177' },
          { name: 'Birobidzhan', value: '11393' },
          { name: 'Biysk', value: '975' },
          { name: 'Blagoveshchensk', value: '77' },
          { name: 'Bratsk', value: '976' },
          { name: 'Brazil', value: '94' },
          { name: 'Brest (153)', value: '153' },
          { name: 'Brest (29632)', value: '29632' },
          { name: 'Brest region / Others', value: '101859' },
          { name: 'Brest region / Universal', value: '101858' },
          { name: 'Bryansk', value: '191' },
          { name: 'Bryansk region', value: '10650' },
          { name: 'Bryansk region / Other', value: '21913' },
          { name: 'Bryansk region / Universal', value: '21912' },
          { name: 'Bugulma', value: '11122' },
          { name: 'Bulgaria', value: '115' },
          { name: 'Buryatia', value: '11330' },
          { name: 'Canada', value: '95' },
          { name: 'Canada / Other', value: '1048' },
          { name: 'Canada / Universal', value: '1049' },
          { name: 'Carpet', value: '10664' },
          { name: 'Center', value: '3' },
          { name: 'Center / Other cities in the region', value: '413' },
          { name: 'Center / Universal', value: '414' },
          { name: 'Chechen Republic', value: '11024' },
          { name: 'Chechen Republic / Other', value: '21891' },
          { name: 'Chechen Republic / Universal', value: '21890' },
          { name: 'Chekhov', value: '10761' },
          { name: 'Chelyabinsk region', value: '11225' },
          { name: 'Chelyabinsk Region / Others', value: '21834' },
          { name: 'Chelyabinsk Region / Universal', value: '21833' },
          { name: 'Cherepovets', value: '968' },
          { name: 'Cherkasy', value: '10363' },
          { name: 'Cherkasy oblast', value: '20546' },
          { name: 'Cherkasy region / Other', value: '102451' },
          { name: 'Cherkasy region / Universal', value: '102476' },
          { name: 'Cherkessk', value: '1104' },
          { name: 'Chernigov region', value: '20551' },
          { name: 'Chernigov region / Universal', value: '102498' },
          { name: 'Chernihiv', value: '966' },
          { name: 'Chernihiv region / Other', value: '102473' },
          { name: 'Chernivtsi', value: '10365' },
          { name: 'Chernivtsi region', value: '20533' },
          { name: 'Chernivtsi region / Other', value: '102468' },
          { name: 'Chernivtsi region / Universal', value: '102493' },
          { name: 'Chernogolovka', value: '219' },
          { name: 'China', value: '134' },
          { name: 'Chisinau', value: '10313' },
          { name: 'Chita', value: '68' },
          { name: 'Chrysostom', value: '11202' },
          { name: 'Chukotka Autonomous District', value: '10251' },
          { name: 'Chukotka Autonomous District / Universal', value: '21785' },
          { name: 'Chukotka Autonomous Okrug / Other', value: '21786' },
          { name: 'Chuvash Republic', value: '11156' },
          { name: 'Chuvash Republic / Other', value: '21865' },
          { name: 'Chuvash Republic / Universal', value: '21864' },
          { name: 'CIS', value: '166' },
          { name: 'CIS / Other', value: '957' },
          { name: 'CIS / Universal', value: '958' },
          { name: 'Cologne', value: '98' },
          { name: 'Comrat', value: '33883' },
          { name: 'Crimea', value: '977' },
          { name: 'Crimea / Other region of the city', value: '978' },
          { name: 'Crimea / Universal', value: '979' },
          { name: 'Crimean Federal District', value: '115092' },
          { name: 'Croatia', value: '10083' },
          { name: 'Cyprus', value: '20574' },
          { name: 'Czech Republic', value: '125' },
          { name: 'Dagestan', value: '11010' },
          { name: 'Denmark', value: '203' },
          { name: 'Detroit', value: '89' },
          { name: 'Dimitrovgrad', value: '11155' },
          { name: 'Dmitrov', value: '10723' },
          { name: 'Dnepropetrovsk', value: '141' },
          { name: 'Dnepropetrovsk region / Others', value: '102457' },
          { name: 'Dnepropetrovsk region / Universal', value: '102482' },
          { name: 'Dnipropetrovsk region', value: '20537' },
          { name: 'Dolgoprudnyi', value: '214' },
          { name: 'Domodedovo', value: '10725' },
          { name: 'Donetsk', value: '142' },
          { name: 'Donetsk region', value: '20536' },
          { name: 'Donetsk region / Other', value: '102456' },
          { name: 'Donetsk region / Universal', value: '102481' },
          { name: 'Dubna', value: '215' },
          { name: 'Dzerzhinsk', value: '972' },
          { name: 'East Kazakhstan region', value: '29408' },
          { name: 'East Kazakhstan region / Other', value: '102502' },
          { name: 'East-Kazakhstan region / Universal', value: '102516' },
          { name: 'Egypt', value: '1056' },
          { name: 'Elektrostal', value: '20523' },
          { name: 'Elista', value: '1094' },
          { name: 'Engels', value: '11147' },
          { name: 'Essentuki', value: '11057' },
          { name: 'Estonia', value: '179' },
          { name: 'Europe', value: '111' },
          { name: 'Europe / Others', value: '733' },
          { name: 'Europe / Universal', value: '734' },
          { name: 'Families', value: '165' },
          { name: 'Far East', value: '73' },
          { name: 'Far East / Other cities in the region', value: '605' },
          { name: 'Far East / Universal', value: '606' },
          { name: 'Feodosiya', value: '11469' },
          { name: 'Finland', value: '123' },
          { name: 'France', value: '124' },
          { name: 'Frankfurt am Main', value: '100' },
          { name: 'Gatchina', value: '10867' },
          { name: 'Gelendzhik', value: '10990' },
          { name: 'Georgia', value: '169' },
          { name: 'Germany', value: '96' },
          { name: 'Germany / Others', value: '701' },
          { name: 'Germany / Universal', value: '702' },
          { name: 'Glazov', value: '11150' },
          { name: 'Gomel', value: '155' },
          { name: 'Gomel oblast', value: '29631' },
          { name: 'Gomel region / Other', value: '101855' },
          { name: 'Gomel region / Universal', value: '101854' },
          { name: 'Goose-crystal', value: '10661' },
          { name: 'Gorno-Altaisk', value: '11319' },
          { name: 'Greece', value: '246' },
          { name: 'Grodno oblast', value: '29634' },
          { name: 'Grodno region / Other', value: '101861' },
          { name: 'Grodno region / Universal', value: '101860' },
          { name: 'Grozny', value: '1106' },
          { name: 'Haifa', value: '132' },
          { name: 'Hamburg', value: '178' },
          { name: 'Harabov', value: '11457' },
          { name: 'Heidelberg', value: '97' },
          { name: 'Hungary', value: '116' },
          { name: 'India', value: '994' },
          { name: 'Ingushetia', value: '11012' },
          { name: 'Irkutsk Region', value: '11266' },
          { name: 'Irkutsk Region / Other', value: '21799' },
          { name: 'Irkutsk Region / Universal', value: '21798' },
          { name: 'Ishim', value: '11173' },
          { name: 'Israel', value: '181' },
          { name: 'Israel / Others', value: '765' },
          { name: 'Israel / Universal', value: '766' },
          { name: 'Italy', value: '205' },
          { name: 'Ivano-Frankivsk region / Other', value: '102471' },
          { name: 'Ivano-Frankivsk region / Universal', value: '102496' },
          { name: 'Ivano-Frankovsk', value: '10345' },
          { name: 'Ivanovo', value: '5' },
          { name: 'Ivanovo region', value: '10687' },
          { name: 'Ivanovo region / Other', value: '21919' },
          { name: 'Ivanovo region / Universal', value: '21918' },
          { name: 'Japan', value: '137' },
          { name: 'Jerusalem', value: '130' },
          { name: 'Jewish Autonomous Region', value: '10243' },
          { name: 'Jewish Autonomous Region / Other', value: '21784' },
          { name: 'Jewish Autonomous Region / Universal', value: '21783' },
          { name: 'Kaliningrad Oblast', value: '10857' },
          { name: 'Kaliningrad region / Other', value: '21899' },
          { name: 'Kaliningrad region / Universal', value: '21898' },
          { name: 'Kalmykia', value: '11015' },
          { name: 'Kaluga', value: '6' },
          { name: 'Kaluga region', value: '10693' },
          { name: 'Kaluga region / Other', value: '21921' },
          { name: 'Kaluga region / Universal', value: '21920' },
          { name: 'Kamchatka Krai / Other', value: '21794' },
          { name: 'Kamchatka Territory', value: '11398' },
          { name: 'Kamchatka Territory / Universal', value: '21793' },
          { name: 'Kamensk', value: '11164' },
          { name: 'Kamensk-', value: '11043' },
          { name: 'Karachay-Cherkess Republic', value: '11020' },
          { name: 'Karachay-Cherkess Republic / Other', value: '21883' },
          { name: 'Karachay-Cherkess Republic / Universal', value: '21882' },
          { name: 'Karaganda', value: '164' },
          { name: 'Karaganda region', value: '29411' },
          { name: 'Karaganda region / Other', value: '102500' },
          { name: 'Karagandy / Universal', value: '102514' },
          { name: 'Kayerkan', value: '11306' },
          { name: 'Kazakhstan', value: '159' },
          { name: 'Kazakhstan / Other', value: '925' },
          { name: 'Kazakhstan / Universal', value: '926' },
          { name: 'Kemerovo Oblast / Universal', value: '21800' },
          { name: 'Kemerovo Region', value: '11282' },
          { name: 'Kemerovo region / Other', value: '21801' },
          { name: 'Kerch', value: '11464' },
          { name: 'Khabarovsk', value: '76' },
          { name: 'Khabarovsk Territory / Other', value: '21790' },
          { name: 'Khabarovsk Territory / Universal', value: '21789' },
          { name: 'Khakassia', value: '11340' },
          { name: 'Khanty-Mansi Autonomous Okrug / Other', value: '21832' },
          { name: 'Khanty-Mansi Autonomous Okrug / Universal', value: '21831' },
          { name: 'Khanty-Mansiysk', value: '11193' },
          { name: 'Kharkiv', value: '147' },
          { name: 'Kharkiv Oblast', value: '20538' },
          { name: 'Kharkiv region / Other', value: '102455' },
          { name: 'Kharkiv region / Universal', value: '102480' },
          { name: 'Kherson', value: '962' },
          { name: 'Kherson Oblast', value: '20542' },
          { name: 'Kherson region / Other', value: '102462' },
          { name: 'Kherson region / Universal', value: '102487' },
          { name: 'Khimki', value: '10758' },
          { name: 'Khmelnitsky', value: '961' },
          { name: 'Khmelnytsky region', value: '20535' },
          { name: 'Khmelnytsky region / Other', value: '102465' },
          { name: 'Khmelnytsky region / Universal', value: '102490' },
          { name: 'Kiev', value: '143' },
          { name: 'Kiev Oblast', value: '20544' },
          { name: 'Kiev region / Other', value: '101864' },
          { name: 'Kiev region / Universal', value: '101865' },
          { name: 'Kirov Region', value: '11070' },
          { name: 'Kirov Region / Other', value: '21838' },
          { name: 'Kirov Region / Universal', value: '21837' },
          { name: 'Kirovo-Chepetsk', value: '11071' },
          { name: 'Kirovograd region', value: '20548' },
          { name: 'Kirovograd region / Other', value: '102453' },
          { name: 'Kirovograd region / Universal', value: '102478' },
          { name: 'Kirovohrad', value: '20221' },
          { name: 'Kislovodsk', value: '11062' },
          { name: 'Kokshetau', value: '20809' },
          { name: 'Kolomna', value: '10734' },
          { name: 'Komi Republic / Other', value: '21909' },
          { name: 'Komi Republic / Universal', value: '21908' },
          { name: 'Komsomolsk-on-Amur', value: '11453' },
          { name: 'Korea', value: '135' },
          { name: 'Korolev', value: '20728' },
          { name: 'Kostanay / Universal', value: '102518' },
          { name: 'Kostanay region', value: '29412' },
          { name: 'Kostanay region / Other', value: '102504' },
          { name: 'Kostroma', value: '7' },
          { name: 'Kostroma region', value: '10699' },
          { name: 'Kostroma region / Other', value: '21923' },
          { name: 'Kostroma region / Universal', value: '21922' },
          { name: 'Kramatorsk', value: '20554' },
          { name: 'Krasnodar Territory', value: '10995' },
          { name: 'Krasnodar Territory / Other', value: '21871' },
          { name: 'Krasnodar Territory / Universal', value: '21870' },
          { name: 'Krasnogorsk', value: '10735' },
          { name: 'Krasnoyarsk Krai / Other', value: '21803' },
          { name: 'Krasnoyarsk Krai / Universal', value: '21802' },
          { name: 'Krasnoyarsk region', value: '11309' },
          { name: 'Kremenchuk', value: '21609' },
          { name: 'Kryvyi Rih', value: '10347' },
          { name: 'Kstovo', value: '20044' },
          { name: 'Kurgan oblast', value: '11158' },
          { name: 'Kurgan Region / Other', value: '21826' },
          { name: 'Kurgan Region / Universal', value: '21825' },
          { name: 'Kursk region', value: '10705' },
          { name: 'Kursk region / Other', value: '21925' },
          { name: 'Kursk region / Universal', value: '21924' },
          { name: 'Kyrgyzstan', value: '207' },
          { name: 'Kyzyl', value: '11333' },
          { name: 'Kyzylorda oblast', value: '29413' },
          { name: 'Kyzylorda Province / Miscellaneous', value: '102512' },
          { name: 'Kyzylorda region / Universal', value: '102526' },
          { name: 'Latvia', value: '206' },
          { name: 'Lipetsk region', value: '10712' },
          { name: 'Lipetsk region / Other', value: '21927' },
          { name: 'Lipetsk region / Universal', value: '21926' },
          { name: 'Lithuania', value: '117' },
          { name: 'Los Angeles', value: '200' },
          { name: 'Lugansk', value: '222' },
          { name: 'Luhansk Oblast', value: '20540' },
          { name: 'Luhansk region / Other', value: '102458' },
          { name: 'Luhansk region / Universal', value: '102483' },
          { name: 'Lutsk', value: '20222' },
          { name: 'Lviv', value: '144' },
          { name: 'Lviv region', value: '20529' },
          { name: 'Lviv region / Other', value: '102464' },
          { name: 'Lviv region / Universal', value: '102489' },
          { name: 'Lyubertsy', value: '10738' },
          { name: 'MA', value: '223' },
          { name: 'Macedonia', value: '10068' },
          { name: 'Magadan', value: '79' },
          { name: 'Magadan Region', value: '11403' },
          { name: 'Magadan Region / Other', value: '21782' },
          { name: 'Magadan Region / Universal', value: '21781' },
          { name: 'Magnitogorsk', value: '235' },
          { name: 'Makiyivka', value: '24876' },
          { name: 'Malta', value: '10069' },
          { name: 'Mangistau region / Other', value: '102510' },
          { name: 'Mangistau region / Universal', value: '102524' },
          { name: 'Mangystau', value: '29414' },
          { name: 'Mari El Republic / Other', value: '21840' },
          { name: 'Mari El Republic / Universal', value: '21839' },
          { name: 'Mariupol', value: '10366' },
          { name: 'Maykop', value: '1093' },
          { name: 'Melitopol', value: '10367' },
          { name: 'Mexico', value: '20271' },
          { name: 'Mezhdurechensk', value: '11287' },
          { name: 'Miass', value: '11212' },
          { name: 'Middle East', value: '1004' },
          { name: 'Middle East / Other', value: '1054' },
          { name: 'Middle East / Universal', value: '1055' },
          { name: 'Mineral waters', value: '11063' },
          { name: 'Mines', value: '11053' },
          { name: 'Minsk', value: '157' },
          { name: 'Minsk region', value: '29630' },
          { name: 'Minsk region / Other', value: '101853' },
          { name: 'Minsk Region / Universal', value: '101852' },
          { name: 'Mogilev', value: '158' },
          { name: 'Mogilev oblast', value: '29629' },
          { name: 'Mogilev region / Other', value: '101863' },
          { name: 'Mogilev region / Universal', value: '101862' },
          { name: 'Moldova', value: '208' },
          { name: 'Moldova / Other', value: '115674' },
          { name: 'Moldova / Universal', value: '115675' },
          { name: 'Montenegro', value: '21610' },
          { name: 'Moore', value: '10668' },
          { name: 'Mordovia', value: '11117' },
          { name: 'Moscow', value: '213' },
          { name: 'Moscow and the region', value: '1' },
          { name: 'Moscow and the region / Other cities in the region', value: '349' },
          { name: 'Moscow and the region / Universal', value: '350' },
          { name: 'Munich', value: '99' },
          { name: 'Murmansk Oblast', value: '10897' },
          { name: 'Murmansk region / Other', value: '21901' },
          { name: 'Murmansk region / Universal', value: '21900' },
          { name: 'Mykolaiv Oblast', value: '20543' },
          { name: 'Mykolaiv region / Other', value: '102461' },
          { name: 'Mytishchi', value: '10740' },
          { name: 'Naberezhnye Chelny', value: '236' },
          { name: 'Nakhodka', value: '974' },
          { name: 'Nazran', value: '1092' },
          { name: 'Neftekamsk', value: '11114' },
          { name: 'Nenets Autonomous Okrug', value: '10176' },
          { name: 'Netherlands', value: '118' },
          { name: 'Nevinnomyssk', value: '11064' },
          { name: 'New York', value: '202' },
          { name: 'New Zealand', value: '139' },
          { name: 'Nikolaev', value: '148' },
          { name: 'Nikolaev region / Universal', value: '102486' },
          { name: 'Nizhnekamsk', value: '11127' },
          { name: 'Nizhnevartovsk', value: '1091' },
          { name: 'Nizhniy Tagil', value: '11168' },
          { name: 'Nizhny Novgorod Region', value: '11079' },
          { name: 'Nizhny Novgorod Region / Other', value: '21842' },
          { name: 'Nizhny Novgorod Region / Universal', value: '21841' },
          { name: 'Noginsk', value: '10742' },
          { name: 'Norilsk', value: '11311' },
          { name: 'North America', value: '10002' },
          { name: 'North Caucasus', value: '102444' },
          { name: 'North Caucasus / Other cities in the region', value: '102445' },
          { name: 'North Caucasus / Universal', value: '102446' },
          { name: 'North Kazakhstan', value: '29416' },
          { name: 'North Kazakhstan region / Other', value: '102506' },
          { name: 'North Kazakhstan region / Universal', value: '102520' },
          { name: 'North-West / Other cities in the region', value: '445' },
          { name: 'North-West / Universal', value: '446' },
          { name: 'Norway', value: '119' },
          { name: 'Novgorod Oblast', value: '10904' },
          { name: 'Novgorod region / Other', value: '21903' },
          { name: 'Novgorod region / Universal', value: '21902' },
          { name: 'Novocherkassk', value: '238' },
          { name: 'Novokuznetsk', value: '237' },
          { name: 'Novomoskovsk', value: '10830' },
          { name: 'Novorossiysk', value: '970' },
          { name: 'Novosibirsk region', value: '11316' },
          { name: 'Novosibirsk region / Other', value: '21805' },
          { name: 'Novosibirsk Region / Universal', value: '21804' },
          { name: 'Novoural\'sk', value: '11170' },
          { name: 'Obninsk', value: '967' },
          { name: 'Odessa', value: '145' },
          { name: 'Odessa region', value: '20541' },
          { name: 'Odessa region / Other', value: '102460' },
          { name: 'Odessa region / Universal', value: '102485' },
          { name: 'Odintsovo', value: '10743' },
          { name: 'Omsk region', value: '11318' },
          { name: 'Omsk region / Other', value: '21807' },
          { name: 'Omsk region / Universal', value: '21806' },
          { name: 'Orekhovo-', value: '10745' },
          { name: 'Oren Universal', value: '21843' },
          { name: 'Orenburg region', value: '11084' },
          { name: 'Orenburg region / Other', value: '21844' },
          { name: 'Orsk', value: '11091' },
          { name: 'Oryol Oblast', value: '10772' },
          { name: 'Oryol region / Other (21928)', value: '21928' },
          { name: 'Oryol region / Other (21929)', value: '21929' },
          { name: 'Other (102469)', value: '102469' },
          { name: 'Other (21943)', value: '21943' },
          { name: 'Other (669)', value: '669' },
          { name: 'Ozersk', value: '11214' },
          { name: 'Pavlodar', value: '190' },
          { name: 'Pavlodar Province / Universal', value: '102517' },
          { name: 'Pavlodar region', value: '29415' },
          { name: 'Pavlodar region / Other', value: '102503' },
          { name: 'Pavlovsky Posad', value: '10746' },
          { name: 'Penza region', value: '11095' },
          { name: 'Penza region / Other', value: '21846' },
          { name: 'Penza region / Universal', value: '21845' },
          { name: 'Pereslavl', value: '10837' },
          { name: 'Perm', value: '11108' },
          { name: 'Perm region / Other', value: '21848' },
          { name: 'Perm region / Universal', value: '21847' },
          { name: 'Pervouralsk', value: '11171' },
          { name: 'Petropavlovsk-Kamchatsky', value: '78' },
          { name: 'Podolsk', value: '10747' },
          { name: 'Poland', value: '120' },
          { name: 'Poltava', value: '964' },
          { name: 'Poltava region', value: '20549' },
          { name: 'Poltava region / Others', value: '102450' },
          { name: 'Poltava region / Universal', value: '102475' },
          { name: 'Primor / Other', value: '21780' },
          { name: 'Primor / Universal', value: '21779' },
          { name: 'Primorsky Territory', value: '11409' },
          { name: 'Prokopevsk', value: '11291' },
          { name: 'Pskov Oblast', value: '10926' },
          { name: 'Pskov region / Other', value: '21905' },
          { name: 'Pskov region / Universal', value: '21904' },
          { name: 'Puschino', value: '217' },
          { name: 'Pushkino', value: '10748' },
          { name: 'Pyatigorsk', value: '11067' },
          { name: 'Railway', value: '21622' },
          { name: 'Ramenskoye', value: '10750' },
          { name: 'Republic of Adygea', value: '11004' },
          { name: 'Republic of Adygea / Other', value: '21873' },
          { name: 'Republic of Adygea / Universal', value: '21872' },
          { name: 'Republic of Altai', value: '10231' },
          { name: 'Republic of Bashkortostan / Other', value: '21850' },
          { name: 'Republic of Bashkortostan / Universal', value: '21849' },
          { name: 'Republic of Buryatia / Other', value: '21811' },
          { name: 'Republic of Buryatia / Universal', value: '21810' },
          { name: 'Republic of Dagestan / Other', value: '21875' },
          { name: 'Republic of Dagestan / Universal', value: '21874' },
          { name: 'Republic of Ingushetia / Other', value: '21877' },
          { name: 'Republic of Ingushetia / Universal', value: '21876' },
          { name: 'Republic of Kabardia', value: '21878' },
          { name: 'Republic of Kabardino-Balkaria', value: '11013' },
          { name: 'Republic of Kalmykia / Other', value: '21881' },
          { name: 'Republic of Kalmykia / Universal', value: '21880' },
          { name: 'Republic of Karelia', value: '10950' },
          { name: 'Republic of Karelia / Other', value: '21907' },
          { name: 'Republic of Karelia / Universal', value: '21906' },
          { name: 'Republic of Khakassia / Other', value: '21815' },
          { name: 'Republic of Khakassia / Universal', value: '21814' },
          { name: 'Republic of Mari El', value: '11077' },
          { name: 'Republic of Mordovia / Other', value: '21853' },
          { name: 'Republic of Mordovia / Universal', value: '21852' },
          { name: 'Republic of North Ossetia-Alania', value: '11021' },
          { name: 'Republic of North Ossetia-Alania / Others', value: '21885' },
          { name: 'Republic of North Ossetia-Alania / Universal', value: '21884' },
          { name: 'Republic of Tyva', value: '10233' },
          { name: 'Republic of Tyva / Other', value: '21813' },
          { name: 'Reutov', value: '21621' },
          { name: 'Rivne', value: '10355' },
          { name: 'Rivne region', value: '20534' },
          { name: 'Rivne region / Other', value: '102467' },
          { name: 'Rivne region / Universal', value: '102492' },
          { name: 'Rostov', value: '10838' },
          { name: 'Rostov region', value: '11029' },
          { name: 'Rostov Region / Other', value: '21887' },
          { name: 'Rostov Region / Universal', value: '21886' },
          { name: 'Rubtsovsk', value: '11251' },
          { name: 'Russia', value: '225' },
          { name: 'Russia / All-Russian', value: '382' },
          { name: 'Russia / Other', value: '381' },
          { name: 'Ryazan oblast', value: '10776' },
          { name: 'Ryazan region / Other', value: '21931' },
          { name: 'Ryazan region / Universal', value: '21930' },
          { name: 'Rybinsk', value: '10839' },
          { name: 'Rzhev', value: '10820' },
          { name: 'Sakhalin Region', value: '11450' },
          { name: 'Sakhalin Region / Other', value: '21778' },
          { name: 'Sakhalin Region / Universal', value: '21777' },
          { name: 'Sakhtrata', value: '10937' },
          { name: 'Sakhtrata Volgograd Region', value: '10945' },
          { name: 'Salavat', value: '11115' },
          { name: 'Samara region', value: '11131' },
          { name: 'Samara region / Other', value: '21857' },
          { name: 'Samara region / Universal', value: '21856' },
          { name: 'San Francisco', value: '90' },
          { name: 'Sarapul', value: '11152' },
          { name: 'Saratov', value: '194' },
          { name: 'Saratov Oblast / Universal', value: '21858' },
          { name: 'Saratov Region', value: '11146' },
          { name: 'Saratov region / Other', value: '21859' },
          { name: 'Sarov', value: '11083' },
          { name: 'Satis', value: '20258' },
          { name: 'Satka', value: '11217' },
          { name: 'Sayanogorsk', value: '11341' },
          { name: 'Seattle', value: '91' },
          { name: 'Serbia', value: '180' },
          { name: 'Sergiev Posad', value: '10752' },
          { name: 'Serpukhov', value: '10754' },
          { name: 'Sevastopol', value: '959' },
          { name: 'Severodvinsk', value: '10849' },
          { name: 'Seversk', value: '11351' },
          { name: 'Shchelkovo', value: '10765' },
          { name: 'Shimkent', value: '221' },
          { name: 'Siberia / Other cities in the region', value: '573' },
          { name: 'Siberia / Universal', value: '574' },
          { name: 'Simferopol', value: '146' },
          { name: 'Slovakia', value: '121' },
          { name: 'Slovenia', value: '122' },
          { name: 'Smolensk region', value: '10795' },
          { name: 'Smolensk region / Other', value: '21933' },
          { name: 'Smolensk region / Universal', value: '21932' },
          { name: 'Snezhinsk', value: '11218' },
          { name: 'Sochi', value: '239' },
          { name: 'Solikamsk', value: '11110' },
          { name: 'Solnechnogorsk', value: '10755' },
          { name: 'South / Other cities in the region', value: '477' },
          { name: 'South / Universal', value: '478' },
          { name: 'South America', value: '10003' },
          { name: 'South Kazakhstan oblast', value: '29417' },
          { name: 'South Kazakhstan region / Other', value: '102507' },
          { name: 'South Kazakhstan region / Universal', value: '102521' },
          { name: 'South Ossetia', value: '29387' },
          { name: 'Spain', value: '204' },
          { name: 'St. Petersburg', value: '2' },
          { name: 'St. Petersburg and Leningrad Region / Other', value: '21893' },
          { name: 'St. Petersburg and the Leningrad Region', value: '10174' },
          { name: 'St. Petersburg and the Leningrad Region / Universal', value: '21892' },
          { name: 'Stary Oskol', value: '10649' },
          { name: 'Stavropol Territory', value: '11069' },
          { name: 'Stavropol Territory / Other', value: '21889' },
          { name: 'Stavropol Territory / Universal', value: '21888' },
          { name: 'Sterlitamak', value: '11116' },
          { name: 'Stupino', value: '10756' },
          { name: 'Stuttgart', value: '101' },
          { name: 'Sumy', value: '965' },
          { name: 'Sumy region', value: '20552' },
          { name: 'Sumy region / Other', value: '102472' },
          { name: 'Sumy region / Universal', value: '102497' },
          { name: 'Surgut', value: '973' },
          { name: 'Suzdal', value: '10671' },
          { name: 'Sverdlovsk', value: '21827' },
          { name: 'Sverdlovsk region', value: '11162' },
          { name: 'Sverdlovsk Region / Other', value: '21828' },
          { name: 'Sweden', value: '127' },
          { name: 'Switzerland', value: '126' },
          { name: 'Syzran', value: '11139' },
          { name: 'Taganrog', value: '971' },
          { name: 'Tajikistan', value: '209' },
          { name: 'Taldykorgan', value: '10303' },
          { name: 'Tambov region', value: '10802' },
          { name: 'Tambov region / Other', value: '21935' },
          { name: 'Tambov region / Universal', value: '21934' },
          { name: 'Tatarstan', value: '11119' },
          { name: 'Tatarstan / Other', value: '21855' },
          { name: 'Tatarstan / Universal', value: '21854' },
          { name: 'Tchistopol', value: '11129' },
          { name: 'Tel Aviv', value: '131' },
          { name: 'Ternopil (10357)', value: '10357' },
          { name: 'Ternopil (20531)', value: '20531' },
          { name: 'Ternopil region / Other', value: '102466' },
          { name: 'Ternopil region / Universal', value: '102491' },
          { name: 'Thailand', value: '995' },
          { name: 'Tiraspol', value: '10317' },
          { name: 'Tobolsk', value: '11175' },
          { name: 'Togliatti', value: '240' },
          { name: 'Tomsk region', value: '11353' },
          { name: 'Tomsk Region / Other', value: '21817' },
          { name: 'Tomsk Region / Universal', value: '21816' },
          { name: 'Trans-Baikal Territory', value: '21949' },
          { name: 'Trans-Baikal Territory / Other', value: '21819' },
          { name: 'Trans-Baikal Territory / Universal', value: '21818' },
          { name: 'Transcarpathian region / Other', value: '102470' },
          { name: 'Transcarpathian region / Universal', value: '102495' },
          { name: 'Tuapse', value: '1058' },
          { name: 'Tula region', value: '10832' },
          { name: 'Tula region / Other', value: '21939' },
          { name: 'Tula region / Universal', value: '21938' },
          { name: 'Turkey', value: '983' },
          { name: 'Turkmenistan', value: '170' },
          { name: 'Tver region', value: '10819' },
          { name: 'Tver region / Other', value: '21937' },
          { name: 'Tver region / Universal', value: '21936' },
          { name: 'Tynda', value: '11391' },
          { name: 'Tyumen region', value: '11176' },
          { name: 'Tyumen Region / Other', value: '21830' },
          { name: 'Tyumen Region / Universal', value: '21829' },
          { name: 'Tyva Republic / Universal', value: '21812' },
          { name: 'UAE', value: '210' },
          { name: 'Udmurt Republic', value: '11148' },
          { name: 'Udmurt Republic / Other', value: '21861' },
          { name: 'Udmurt Republic / Universal', value: '21860' },
          { name: 'Ufa', value: '172' },
          { name: 'Uglich', value: '10840' },
          { name: 'Ukraine', value: '187' },
          { name: 'Ukraine / Ivano-Frankivsk region', value: '20532' },
          { name: 'Ukraine / Others', value: '861' },
          { name: 'Ukraine / Universal', value: '862' },
          { name: 'Ulan-Ude', value: '198' },
          { name: 'Ulyanovsk', value: '195' },
          { name: 'Ulyanovsk region', value: '11153' },
          { name: 'Ulyanovsk region / Other', value: '21863' },
          { name: 'Ulyanovsk region / Universal', value: '21862' },
          { name: 'United Kingdom', value: '102' },
          { name: 'Universal (21942)', value: '21942' },
          { name: 'Universal (318)', value: '318' },
          { name: 'Universal (670)', value: '670' },
          { name: 'Ural / Other cities in the region', value: '541' },
          { name: 'Ural / Universal', value: '542' },
          { name: 'USA', value: '84' },
          { name: 'USA / Other', value: '637' },
          { name: 'USA / Universal', value: '638' },
          { name: 'Ussuriysk', value: '11426' },
          { name: 'Ust-Ilimsk', value: '11273' },
          { name: 'Ust-Kamenogorsk', value: '10306' },
          { name: 'Uzbekistan', value: '171' },
          { name: 'Uzhhorod', value: '10358' },
          { name: 'Velikiye Luki Oblast', value: '10928' },
          { name: 'Vidnoe', value: '10719' },
          { name: 'Vinnytsia', value: '963' },
          { name: 'Vinnytsia region', value: '20545' },
          { name: 'Vinnytsia region / Other', value: '102452' },
          { name: 'Vinnytsia region / Universal', value: '102477' },
          { name: 'Vitebsk (154)', value: '154' },
          { name: 'Vitebsk (29633)', value: '29633' },
          { name: 'Vitebsk region / Other', value: '101857' },
          { name: 'Vitebsk region / Universal', value: '101856' },
          { name: 'Vladimir', value: '192' },
          { name: 'Vladimir region / Other', value: '21915' },
          { name: 'Vladimir region / Universal', value: '21914' },
          { name: 'Vladimirckaya area of', value: '10658' },
          { name: 'Vladivostok', value: '75' },
          { name: 'Volga region / Other cities in the region', value: '509' },
          { name: 'Volga region / Universal', value: '510' },
          { name: 'Volgodonsk', value: '11036' },
          { name: 'Volgograd region / Other', value: '21869' },
          { name: 'Volgograd region / Universal', value: '21868' },
          { name: 'Vologda Oblast', value: '10853' },
          { name: 'Vologda region / Other', value: '21897' },
          { name: 'Vologda region / Universal', value: '21896' },
          { name: 'Volyn region', value: '20550' },
          { name: 'Volyn region / Universal', value: '102494' },
          { name: 'Volzhsky', value: '10951' },
          { name: 'Voronezh', value: '193' },
          { name: 'Voronezh region / Other', value: '21917' },
          { name: 'Voronezh region / Universal', value: '21916' },
          { name: 'Voronezhckaya area', value: '10672' },
          { name: 'Vyborg', value: '969' },
          { name: 'Vyksa', value: '20040' },
          { name: 'Washington', value: '87' },
          { name: 'Wedge', value: '10733' },
          { name: 'West Kazakhstan / Universal', value: '102519' },
          { name: 'West Kazakhstan region', value: '29410' },
          { name: 'West Kazakhstan region / Other', value: '102505' },
          { name: 'White Church', value: '10369' },
          { name: 'Yakutsk', value: '74' },
          { name: 'Yalta', value: '11470' },
          { name: 'Yamal-Nenets Autonomous District / Universal', value: '21835' },
          { name: 'Yamalo-Nenets Autonomous District', value: '11232' },
          { name: 'Yamalo-Nenets Autonomous District / Other', value: '21836' },
          { name: 'Yaroslavl Oblast', value: '10841' },
          { name: 'Yaroslavl Oblast / Universal', value: '21940' },
          { name: 'Yaroslavl region / Other', value: '21941' },
          { name: 'Yeisk', value: '10993' },
          { name: 'Yelabuga', value: '11123' },
          { name: 'Yevpatoriya', value: '11463' },
          { name: 'Yuzhno-Sakhalinsk', value: '80' },
          { name: 'Zakarpattia oblast', value: '20530' },
          { name: 'Zaporizhia Oblast', value: '20539' },
          { name: 'Zaporozhye', value: '960' },
          { name: 'Zaporozhye region / Other', value: '102459' },
          { name: 'Zaporozhye region / Universal', value: '102484' },
          { name: 'Zelenodolsk', value: '11125' },
          { name: 'Zhambyl oblast / Miscellaneous', value: '102511' },
          { name: 'Zhambyl region', value: '29409' },
          { name: 'Zhambyl region / Universal', value: '102525' },
          { name: 'Zheleznogorsk', value: '20086' },
          { name: 'Zhigulevsk', value: '11132' },
          { name: 'Zhodino', value: '26034' },
          { name: 'Zhukovsky', value: '20571' },
          { name: 'Zhytomyr', value: '10343' },
          { name: 'Zhytomyr region', value: '20547' },
          { name: 'Zhytomyr region / Other', value: '102454' },
          { name: 'Zhytomyr region / Universal', value: '102479' },
        ],
        default: '',
        description: 'Canonical location of the search',
        routing: {
          request: {
            qs: {
              location: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Yandex Domain (yandex_domain)',
        name: 'yandex_domain',
        type: 'options',
        options: [
          { name: 'Armenia', value: 'yandex.com.am' },
          { name: 'Azerbaijan', value: 'yandex.az' },
          { name: 'Belarus', value: 'yandex.by' },
          { name: 'Estonia', value: 'yandex.ee' },
          { name: 'Europe', value: 'yandex.eu' },
          { name: 'France', value: 'yandex.fr' },
          { name: 'Georgia', value: 'yandex.com.ge' },
          { name: 'Israel', value: 'yandex.co.il' },
          { name: 'Kazakhstan', value: 'yandex.kz' },
          { name: 'Latvia', value: 'yandex.lv' },
          { name: 'Lithuania', value: 'yandex.lt' },
          { name: 'Moldova', value: 'yandex.md' },
          { name: 'Russia (ya.ru)', value: 'ya.ru' },
          { name: 'Russia (yandex.ru)', value: 'yandex.ru' },
          { name: 'Tajikistan', value: 'yandex.tj' },
          { name: 'Turkey', value: 'yandex.com.tr' },
          { name: 'Turkmenistan', value: 'yandex.tm' },
          { name: 'Uzbekistan', value: 'yandex.uz' },
          { name: 'Yandex.com', value: 'yandex.com' },
        ],
        default: 'yandex.com',
        description: 'Yandex domain of the search',
        routing: {
          request: {
            qs: {
              yandex_domain: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Time Period (time_period)',
        name: 'time_period',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Last day', value: 'last_day' },
          { name: 'Last month', value: 'last_month' },
          { name: 'Last two weeks', value: 'last_two_weeks' },
        ],
        default: '',
        description: 'Restricts results to URLs based on date',
        routing: {
          request: {
            qs: {
              time_period: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Pagination',
    name: 'pagination',
    type: 'collection',
    placeholder: 'Add Pagination',
    default: {},
    options: [
      {
        displayName: 'Page (page)',
        name: 'page',
        type: 'number',
        typeOptions: {
          minValue: 1,
          numberPrecision: 0,
        },
        default: 1,
        description: 'Specifies the page of results to return. The default value is 1. Only the first four pages (1-4) are supported.',
        routing: {
          request: {
            qs: {
              page: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const yandex = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/yandex-api',
};
