import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['youtube_trends'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Youtube Trends',
  value: 'youtube_trends'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Category (bp)',
        name: 'bp',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Films', value: 'films' },
          { name: 'Gaming', value: 'gaming' },
          { name: 'Music', value: 'music' },
          { name: 'Now', value: 'now' },
        ],
        default: '',
        description: 'Specifies the category of trending content',
        routing: {
          request: {
            qs: {
              bp: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Country (gl)',
        name: 'gl',
        type: 'options',
        options: [
          { name: 'Algeria', value: 'DZ' },
          { name: 'Argentina', value: 'AR' },
          { name: 'Australia', value: 'AU' },
          { name: 'Austria', value: 'AT' },
          { name: 'Azerbaijan', value: 'AZ' },
          { name: 'Bahrain', value: 'BH' },
          { name: 'Bangladesh', value: 'BD' },
          { name: 'Belarus', value: 'BY' },
          { name: 'Belgium', value: 'BE' },
          { name: 'Bolivia', value: 'BO' },
          { name: 'Bosnia and Herzegovina', value: 'BA' },
          { name: 'Brazil', value: 'BR' },
          { name: 'Bulgaria', value: 'BG' },
          { name: 'Cambodia', value: 'KH' },
          { name: 'Canada', value: 'CA' },
          { name: 'Chile', value: 'CL' },
          { name: 'Colombia', value: 'CO' },
          { name: 'Costa Rica', value: 'CR' },
          { name: 'Croatia', value: 'HR' },
          { name: 'Cyprus', value: 'CY' },
          { name: 'Czechia', value: 'CZ' },
          { name: 'Denmark', value: 'DK' },
          { name: 'Dominican Republic', value: 'DO' },
          { name: 'Ecuador', value: 'EC' },
          { name: 'Egypt', value: 'EG' },
          { name: 'El Salvador', value: 'SV' },
          { name: 'Estonia', value: 'EE' },
          { name: 'Finland', value: 'FI' },
          { name: 'France', value: 'FR' },
          { name: 'Georgia', value: 'GE' },
          { name: 'Germany', value: 'DE' },
          { name: 'Ghana', value: 'GH' },
          { name: 'Greece', value: 'GR' },
          { name: 'Guatemala', value: 'GT' },
          { name: 'Honduras', value: 'HN' },
          { name: 'Hong Kong', value: 'HK' },
          { name: 'Hungary', value: 'HU' },
          { name: 'Iceland', value: 'IS' },
          { name: 'India', value: 'IN' },
          { name: 'Indonesia', value: 'ID' },
          { name: 'Iraq', value: 'IQ' },
          { name: 'Ireland', value: 'IE' },
          { name: 'Israel', value: 'IL' },
          { name: 'Italy', value: 'IT' },
          { name: 'Jamaica', value: 'JM' },
          { name: 'Japan', value: 'JP' },
          { name: 'Jordan', value: 'JO' },
          { name: 'Kazakhstan', value: 'KZ' },
          { name: 'Kenya', value: 'KE' },
          { name: 'Kuwait', value: 'KW' },
          { name: 'Laos', value: 'LA' },
          { name: 'Latvia', value: 'LV' },
          { name: 'Lebanon', value: 'LB' },
          { name: 'Libya', value: 'LY' },
          { name: 'Liechtenstein', value: 'LI' },
          { name: 'Lithuania', value: 'LT' },
          { name: 'Luxembourg', value: 'LU' },
          { name: 'Malaysia', value: 'MY' },
          { name: 'Malta', value: 'MT' },
          { name: 'Mexico', value: 'MX' },
          { name: 'Montenegro', value: 'ME' },
          { name: 'Morocco', value: 'MA' },
          { name: 'Nepal', value: 'NP' },
          { name: 'Netherlands', value: 'NL' },
          { name: 'New Zealand', value: 'NZ' },
          { name: 'Nicaragua', value: 'NI' },
          { name: 'Nigeria', value: 'NG' },
          { name: 'North Macedonia', value: 'MK' },
          { name: 'Norway', value: 'NO' },
          { name: 'Oman', value: 'OM' },
          { name: 'Pakistan', value: 'PK' },
          { name: 'Panama', value: 'PA' },
          { name: 'Papua New Guinea', value: 'PG' },
          { name: 'Paraguay', value: 'PY' },
          { name: 'Peru', value: 'PE' },
          { name: 'Philippines', value: 'PH' },
          { name: 'Poland', value: 'PL' },
          { name: 'Portugal', value: 'PT' },
          { name: 'Puerto Rico', value: 'PR' },
          { name: 'Qatar', value: 'QA' },
          { name: 'Romania', value: 'RO' },
          { name: 'Russia', value: 'RU' },
          { name: 'Saudi Arabia', value: 'SA' },
          { name: 'Senegal', value: 'SN' },
          { name: 'Serbia', value: 'RS' },
          { name: 'Singapore', value: 'SG' },
          { name: 'Slovakia', value: 'SK' },
          { name: 'Slovenia', value: 'SI' },
          { name: 'South Africa', value: 'ZA' },
          { name: 'South Korea', value: 'KR' },
          { name: 'Spain', value: 'ES' },
          { name: 'Sri Lanka', value: 'LK' },
          { name: 'Sweden', value: 'SE' },
          { name: 'Switzerland', value: 'CH' },
          { name: 'Taiwan', value: 'TW' },
          { name: 'Tanzania', value: 'TZ' },
          { name: 'Thailand', value: 'TH' },
          { name: 'Tunisia', value: 'TN' },
          { name: 'Turkey', value: 'TR' },
          { name: 'Uganda', value: 'UG' },
          { name: 'Ukraine', value: 'UA' },
          { name: 'United Arab Emirates', value: 'AE' },
          { name: 'United Kingdom', value: 'GB' },
          { name: 'United States', value: 'US' },
          { name: 'Uruguay', value: 'UY' },
          { name: 'Venezuela', value: 'VE' },
          { name: 'Vietnam', value: 'VN' },
          { name: 'Yemen', value: 'YE' },
          { name: 'Zimbabwe', value: 'ZW' },
        ],
        default: 'US',
        description: 'Defines the country of the search',
        routing: {
          request: {
            qs: {
              gl: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Language (hl)',
        name: 'hl',
        type: 'options',
        options: [
          { name: 'af', value: 'af' },
          { name: 'am', value: 'am' },
          { name: 'ar', value: 'ar' },
          { name: 'as', value: 'as' },
          { name: 'az', value: 'az' },
          { name: 'be', value: 'be' },
          { name: 'bg', value: 'bg' },
          { name: 'bn', value: 'bn' },
          { name: 'bs', value: 'bs' },
          { name: 'ca', value: 'ca' },
          { name: 'cs', value: 'cs' },
          { name: 'da', value: 'da' },
          { name: 'de', value: 'de' },
          { name: 'el', value: 'el' },
          { name: 'en', value: 'en' },
          { name: 'en-gb', value: 'en-gb' },
          { name: 'en-in', value: 'en-in' },
          { name: 'es', value: 'es' },
          { name: 'es-419', value: 'es-419' },
          { name: 'es-us', value: 'es-us' },
          { name: 'et', value: 'et' },
          { name: 'eu', value: 'eu' },
          { name: 'fa', value: 'fa' },
          { name: 'fi', value: 'fi' },
          { name: 'Fil', value: 'fil' },
          { name: 'fr', value: 'fr' },
          { name: 'fr-ca', value: 'fr-ca' },
          { name: 'gl', value: 'gl' },
          { name: 'gu', value: 'gu' },
          { name: 'hi', value: 'hi' },
          { name: 'hr', value: 'hr' },
          { name: 'hu', value: 'hu' },
          { name: 'hy', value: 'hy' },
          { name: 'id', value: 'id' },
          { name: 'is', value: 'is' },
          { name: 'it', value: 'it' },
          { name: 'iw', value: 'iw' },
          { name: 'ja', value: 'ja' },
          { name: 'ka', value: 'ka' },
          { name: 'kk', value: 'kk' },
          { name: 'km', value: 'km' },
          { name: 'kn', value: 'kn' },
          { name: 'ko', value: 'ko' },
          { name: 'ky', value: 'ky' },
          { name: 'lo', value: 'lo' },
          { name: 'lt', value: 'lt' },
          { name: 'lv', value: 'lv' },
          { name: 'mk', value: 'mk' },
          { name: 'ml', value: 'ml' },
          { name: 'mn', value: 'mn' },
          { name: 'mr', value: 'mr' },
          { name: 'ms', value: 'ms' },
          { name: 'my', value: 'my' },
          { name: 'ne', value: 'ne' },
          { name: 'nl', value: 'nl' },
          { name: 'no', value: 'no' },
          { name: 'or', value: 'or' },
          { name: 'pa', value: 'pa' },
          { name: 'pl', value: 'pl' },
          { name: 'pt', value: 'pt' },
          { name: 'pt-pt', value: 'pt-pt' },
          { name: 'ro', value: 'ro' },
          { name: 'ru', value: 'ru' },
          { name: 'si', value: 'si' },
          { name: 'sk', value: 'sk' },
          { name: 'sl', value: 'sl' },
          { name: 'sq', value: 'sq' },
          { name: 'sr', value: 'sr' },
          { name: 'sr-latn', value: 'sr-latn' },
          { name: 'sv', value: 'sv' },
          { name: 'sw', value: 'sw' },
          { name: 'ta', value: 'ta' },
          { name: 'te', value: 'te' },
          { name: 'th', value: 'th' },
          { name: 'tr', value: 'tr' },
          { name: 'uk', value: 'uk' },
          { name: 'ur', value: 'ur' },
          { name: 'uz', value: 'uz' },
          { name: 'vi', value: 'vi' },
          { name: 'zh-cn', value: 'zh-cn' },
          { name: 'zh-hk', value: 'zh-hk' },
          { name: 'zh-tw', value: 'zh-tw' },
          { name: 'zu', value: 'zu' },
        ],
        default: 'en',
        description: 'Defines the interface language of the search',
        routing: {
          request: {
            qs: {
              hl: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const youtube_trends = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/youtube-trends',
};
