import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
  show: {
    resource: ['youtube_transcripts'],
  },
};

const resource: INodePropertyOptions = {
  name: 'Youtube Transcripts',
  value: 'youtube_transcripts'
};

const properties: INodeProperties[] = [
  {
    displayName: 'Video ID (video_id)',
    name: 'video_id',
    type: 'string',
    required: true,
    default: '',
    description: 'The video ID to search. You can find these values in JSON responses in the YouTube engine or in the YouTube page URL: https://www.youtube.com/watch?v=video_id. Also accepts full YouTube URLs and share links (https://youtu.be/VIDEO_ID).',
    displayOptions,
    routing: {
      request: {
        qs: {
          video_id: '={{$value}}',
        },
      },
    },
  },
  {
    displayName: 'Localization',
    name: 'localization',
    type: 'collection',
    placeholder: 'Add Localization',
    default: {},
    options: [
      {
        displayName: 'Language (lang)',
        name: 'lang',
        type: 'options',
        options: [
          { name: 'Afrikaans', value: 'af' },
          { name: 'Akan', value: 'ak' },
          { name: 'Albanian', value: 'sq' },
          { name: 'Amharic', value: 'am' },
          { name: 'Arabic', value: 'ar' },
          { name: 'Armenian', value: 'hy' },
          { name: 'Assamese', value: 'as' },
          { name: 'Aymara', value: 'ay' },
          { name: 'Azerbaijani', value: 'az' },
          { name: 'Bangla', value: 'bn' },
          { name: 'Basque', value: 'eu' },
          { name: 'Belarusian', value: 'be' },
          { name: 'Bhojpuri', value: 'bho' },
          { name: 'Bosnian', value: 'bs' },
          { name: 'Bulgarian', value: 'bg' },
          { name: 'Burmese', value: 'my' },
          { name: 'Catalan', value: 'ca' },
          { name: 'Cebuano', value: 'ceb' },
          { name: 'Chinese', value: 'zh' },
          { name: 'Chinese (China)', value: 'zh-CN' },
          { name: 'Chinese (Hong Kong)', value: 'zh-HK' },
          { name: 'Chinese (Simplified)', value: 'zh-Hans' },
          { name: 'Chinese (Singapore)', value: 'zh-SG' },
          { name: 'Chinese (Taiwan)', value: 'zh-TW' },
          { name: 'Chinese (Traditional)', value: 'zh-Hant' },
          { name: 'Corsican', value: 'co' },
          { name: 'Croatian', value: 'hr' },
          { name: 'Czech', value: 'cs' },
          { name: 'Danish', value: 'da' },
          { name: 'Divehi', value: 'dv' },
          { name: 'Dutch', value: 'nl' },
          { name: 'English', value: 'en' },
          { name: 'English (United States)', value: 'en-US' },
          { name: 'Esperanto', value: 'eo' },
          { name: 'Estonian', value: 'et' },
          { name: 'Ewe', value: 'ee' },
          { name: 'Filipino', value: 'fil' },
          { name: 'Finnish', value: 'fi' },
          { name: 'French', value: 'fr' },
          { name: 'Galician', value: 'gl' },
          { name: 'Ganda', value: 'lg' },
          { name: 'Georgian', value: 'ka' },
          { name: 'German', value: 'de' },
          { name: 'Greek', value: 'el' },
          { name: 'Guarani', value: 'gn' },
          { name: 'Gujarati', value: 'gu' },
          { name: 'Haitian Creole', value: 'ht' },
          { name: 'Hakka Chinese (Taiwan)', value: 'hak-TW' },
          { name: 'Hausa', value: 'ha' },
          { name: 'Hawaiian', value: 'haw' },
          { name: 'Hebrew', value: 'iw' },
          { name: 'Hindi', value: 'hi' },
          { name: 'Hmong', value: 'hmn' },
          { name: 'Hungarian', value: 'hu' },
          { name: 'Icelandic', value: 'is' },
          { name: 'Igbo', value: 'ig' },
          { name: 'Indonesian', value: 'id' },
          { name: 'Irish', value: 'ga' },
          { name: 'Italian', value: 'it' },
          { name: 'Japanese', value: 'ja' },
          { name: 'Javanese', value: 'jv' },
          { name: 'Kannada', value: 'kn' },
          { name: 'Kazakh', value: 'kk' },
          { name: 'Khmer', value: 'km' },
          { name: 'Kinyarwanda', value: 'rw' },
          { name: 'Korean', value: 'ko' },
          { name: 'Krio', value: 'kri' },
          { name: 'Kurdish', value: 'ku' },
          { name: 'Kyrgyz', value: 'ky' },
          { name: 'Lao', value: 'lo' },
          { name: 'Latin', value: 'la' },
          { name: 'Latvian', value: 'lv' },
          { name: 'Lingala', value: 'ln' },
          { name: 'Lithuanian', value: 'lt' },
          { name: 'Luxembourgish', value: 'lb' },
          { name: 'Macedonian', value: 'mk' },
          { name: 'Malagasy', value: 'mg' },
          { name: 'Malay', value: 'ms' },
          { name: 'Malayalam', value: 'ml' },
          { name: 'Maltese', value: 'mt' },
          { name: 'Māori', value: 'mi' },
          { name: 'Marathi', value: 'mr' },
          { name: 'Min Nan Chinese (Taiwan)', value: 'nan-TW' },
          { name: 'Mongolian', value: 'mn' },
          { name: 'Nepali', value: 'ne' },
          { name: 'Northern Sotho', value: 'nso' },
          { name: 'Norwegian', value: 'no' },
          { name: 'Nyanja', value: 'ny' },
          { name: 'Odia', value: 'or' },
          { name: 'Oromo', value: 'om' },
          { name: 'Pashto', value: 'ps' },
          { name: 'Persian', value: 'fa' },
          { name: 'Polish', value: 'pl' },
          { name: 'Portuguese', value: 'pt' },
          { name: 'Punjabi', value: 'pa' },
          { name: 'Quechua', value: 'qu' },
          { name: 'Romanian', value: 'ro' },
          { name: 'Russian', value: 'ru' },
          { name: 'Samoan', value: 'sm' },
          { name: 'Sanskrit', value: 'sa' },
          { name: 'Scottish Gaelic', value: 'gd' },
          { name: 'Serbian', value: 'sr' },
          { name: 'Shona', value: 'sn' },
          { name: 'Sindhi', value: 'sd' },
          { name: 'Sinhala', value: 'si' },
          { name: 'Slovak', value: 'sk' },
          { name: 'Slovenian', value: 'sl' },
          { name: 'Somali', value: 'so' },
          { name: 'Southern Sotho', value: 'st' },
          { name: 'Spanish', value: 'es' },
          { name: 'Sundanese', value: 'su' },
          { name: 'Swahili', value: 'sw' },
          { name: 'Swedish', value: 'sv' },
          { name: 'Tajik', value: 'tg' },
          { name: 'Tamil', value: 'ta' },
          { name: 'Tatar', value: 'tt' },
          { name: 'Telugu', value: 'te' },
          { name: 'Thai', value: 'th' },
          { name: 'Tigrinya', value: 'ti' },
          { name: 'Tsonga', value: 'ts' },
          { name: 'Turkish', value: 'tr' },
          { name: 'Turkmen', value: 'tk' },
          { name: 'Ukrainian', value: 'uk' },
          { name: 'Urdu', value: 'ur' },
          { name: 'Uyghur', value: 'ug' },
          { name: 'Uzbek', value: 'uz' },
          { name: 'Vietnamese', value: 'vi' },
          { name: 'Welsh', value: 'cy' },
          { name: 'Western Frisian', value: 'fy' },
          { name: 'Xhosa', value: 'xh' },
          { name: 'Yiddish', value: 'yi' },
          { name: 'Yoruba', value: 'yo' },
          { name: 'Zulu', value: 'zu' },
        ],
        default: 'en',
        description: 'Sets the default language for transcripts. While a variety of languages are supported, often only a few are available.',
        routing: {
          request: {
            qs: {
              lang: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Filters',
    default: {},
    options: [
      {
        displayName: 'Only Available (only_available)',
        name: 'only_available',
        type: 'boolean',
        default: false,
        description: 'Whether to enable fallback behavior. The API first attempts to find a transcript matching your lang or transcript_name parameter. If no match is found, it returns the first available transcript instead of an error. Transcripts can still be filtered by transcript_type.',
        routing: {
          request: {
            qs: {
              only_available: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Transcript Name (transcript_name)',
        name: 'transcript_name',
        type: 'string',
        default: '',
        description: 'The transcript name to retrieve. Available transcript names can be found in the available_languages field of the video response. Use this to select the desired transcript by name instead of lang.',
        routing: {
          request: {
            qs: {
              transcript_name: '={{$value}}',
            },
          },
        },
      },
      {
        displayName: 'Transcript Type (transcript_type)',
        name: 'transcript_type',
        type: 'options',
        options: [
          { name: 'Any', value: '' },
          { name: 'Auto', value: 'auto' },
          { name: 'Manual', value: 'manual' },
        ],
        default: '',
        description: 'The transcript preference when both auto-generated and manually uploaded transcripts are available. auto - Prioritizes YouTube\'s auto-generated transcript. It can be translated into any lang language, but retrieval may be slower compared to manual transcripts. manual - Prioritizes manually uploaded transcripts.',
        routing: {
          request: {
            qs: {
              transcript_type: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  },
  {
    displayName: 'Zero Data Retention',
    name: 'zero_data_retention',
    type: 'collection',
    placeholder: 'Add Zero Data Retention',
    default: {},
    options: [
      {
        displayName: 'Zero Retention (zero_retention)',
        name: 'zero_retention',
        type: 'boolean',
        default: false,
        description: 'Whether to disable all logging and persistent storage. No request parameters, HTML, or JSON responses are stored or logged. Suitable for high-compliance use cases. Debugging and support may be limited while enabled.',
        routing: {
          request: {
            qs: {
              zero_retention: '={{$value}}',
            },
          },
        },
      }
    ],
    displayOptions,
  }
];

export const youtube_transcripts = {
  resource,
  properties,
  docsUrl: 'https://www.searchapi.io/docs/youtube-transcripts',
};
