import { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

const displayOptions = {
	show: {
		resource: ['youtube'],
	},
};

const resource: INodePropertyOptions = { 
	name: 'YouTube', 
	value: 'youtube' 
};

const properties: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'q',
		type: 'string',
		required: true,
		default: '',
		description: 'Search query to search on YouTube',
		options: [],
		displayOptions,
		routing: {
			request: {
				qs: {
					q: '={{$value}}',
				},
			},
		},
	},
	{
		displayName: 'Search Options',
		name: 'searchOptions',
		type: 'collection',
		placeholder: 'Add Search Option',
		default: {},
		options: [
			{
				displayName: 'Country',
				name: 'gl',
				type: 'options',
				default: 'US',
				description: 'Country code for localized results',
				options: [
					{ name: 'Algeria', value: 'DZ' },
					{ name: 'Argentina', value: 'AR' },
					{ name: 'Australia', value: 'AU' },
					{ name: 'Austria', value: 'AT' },
					{ name: 'Azerbaijan', value: 'AZ' },
					{ name: 'Bahrain', value: 'BH' },
					{ name: 'Bangladesh', value: 'BD' },
					{ name: 'Belarus', value: 'BY' },
					{ name: 'Belgium', value: 'BE' },
					{ name: 'Bolivia', value: 'BO' },
					{ name: 'Bosnia and Herzegovina', value: 'BA' },
					{ name: 'Brazil', value: 'BR' },
					{ name: 'Bulgaria', value: 'BG' },
					{ name: 'Cambodia', value: 'KH' },
					{ name: 'Canada', value: 'CA' },
					{ name: 'Chile', value: 'CL' },
					{ name: 'Colombia', value: 'CO' },
					{ name: 'Costa Rica', value: 'CR' },
					{ name: 'Croatia', value: 'HR' },
					{ name: 'Cyprus', value: 'CY' },
					{ name: 'Czech Republic', value: 'CZ' },
					{ name: 'Denmark', value: 'DK' },
					{ name: 'Dominican Republic', value: 'DO' },
					{ name: 'Ecuador', value: 'EC' },
					{ name: 'Egypt', value: 'EG' },
					{ name: 'El Salvador', value: 'SV' },
					{ name: 'Estonia', value: 'EE' },
					{ name: 'Finland', value: 'FI' },
					{ name: 'France', value: 'FR' },
					{ name: 'Georgia', value: 'GE' },
					{ name: 'Germany', value: 'DE' },
					{ name: 'Ghana', value: 'GH' },
					{ name: 'Greece', value: 'GR' },
					{ name: 'Guatemala', value: 'GT' },
					{ name: 'Honduras', value: 'HN' },
					{ name: 'Hong Kong', value: 'HK' },
					{ name: 'Hungary', value: 'HU' },
					{ name: 'Iceland', value: 'IS' },
					{ name: 'India', value: 'IN' },
					{ name: 'Indonesia', value: 'ID' },
					{ name: 'Iraq', value: 'IQ' },
					{ name: 'Ireland', value: 'IE' },
					{ name: 'Israel', value: 'IL' },
					{ name: 'Italy', value: 'IT' },
					{ name: 'Jamaica', value: 'JM' },
					{ name: 'Japan', value: 'JP' },
					{ name: 'Jordan', value: 'JO' },
					{ name: 'Kazakhstan', value: 'KZ' },
					{ name: 'Kenya', value: 'KE' },
					{ name: 'Kuwait', value: 'KW' },
					{ name: 'Laos', value: 'LA' },
					{ name: 'Latvia', value: 'LV' },
					{ name: 'Lebanon', value: 'LB' },
					{ name: 'Libya', value: 'LY' },
					{ name: 'Liechtenstein', value: 'LI' },
					{ name: 'Lithuania', value: 'LT' },
					{ name: 'Luxembourg', value: 'LU' },
					{ name: 'Malaysia', value: 'MY' },
					{ name: 'Malta', value: 'MT' },
					{ name: 'Mexico', value: 'MX' },
					{ name: 'Montenegro', value: 'ME' },
					{ name: 'Morocco', value: 'MA' },
					{ name: 'Nepal', value: 'NP' },
					{ name: 'Netherlands', value: 'NL' },
					{ name: 'New Zealand', value: 'NZ' },
					{ name: 'Nicaragua', value: 'NI' },
					{ name: 'Nigeria', value: 'NG' },
					{ name: 'North Macedonia', value: 'MK' },
					{ name: 'Norway', value: 'NO' },
					{ name: 'Oman', value: 'OM' },
					{ name: 'Pakistan', value: 'PK' },
					{ name: 'Panama', value: 'PA' },
					{ name: 'Papua New Guinea', value: 'PG' },
					{ name: 'Paraguay', value: 'PY' },
					{ name: 'Peru', value: 'PE' },
					{ name: 'Philippines', value: 'PH' },
					{ name: 'Poland', value: 'PL' },
					{ name: 'Portugal', value: 'PT' },
					{ name: 'Puerto Rico', value: 'PR' },
					{ name: 'Qatar', value: 'QA' },
					{ name: 'Romania', value: 'RO' },
					{ name: 'Russia', value: 'RU' },
					{ name: 'Saudi Arabia', value: 'SA' },
					{ name: 'Senegal', value: 'SN' },
					{ name: 'Serbia', value: 'RS' },
					{ name: 'Singapore', value: 'SG' },
					{ name: 'Slovakia', value: 'SK' },
					{ name: 'Slovenia', value: 'SI' },
					{ name: 'South Africa', value: 'ZA' },
					{ name: 'South Korea', value: 'KR' },
					{ name: 'Spain', value: 'ES' },
					{ name: 'Sri Lanka', value: 'LK' },
					{ name: 'Sweden', value: 'SE' },
					{ name: 'Switzerland', value: 'CH' },
					{ name: 'Taiwan', value: 'TW' },
					{ name: 'Tanzania', value: 'TZ' },
					{ name: 'Thailand', value: 'TH' },
					{ name: 'Tunisia', value: 'TN' },
					{ name: 'Turkey', value: 'TR' },
					{ name: 'Uganda', value: 'UG' },
					{ name: 'Ukraine', value: 'UA' },
					{ name: 'United Arab Emirates', value: 'AE' },
					{ name: 'United Kingdom', value: 'GB' },
					{ name: 'United States', value: 'US' },
					{ name: 'Uruguay', value: 'UY' },
					{ name: 'Venezuela', value: 'VE' },
					{ name: 'Vietnam', value: 'VN' },
					{ name: 'Yemen', value: 'YE' },
					{ name: 'Zimbabwe', value: 'ZW' },
				],
				routing: {
					request: {
						qs: {
							gl: '={{$value}}',
						},
					},
				},
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'options',
				default: 'en',
				description: 'Interface language for search results',
				options: [
					{ name: 'Afrikaans', value: 'af' },
					{ name: 'Albanian', value: 'sq' },
					{ name: 'Amharic', value: 'am' },
					{ name: 'Arabic', value: 'ar' },
					{ name: 'Armenian', value: 'hy' },
					{ name: 'Assamese', value: 'as' },
					{ name: 'Azerbaijani', value: 'az' },
					{ name: 'Basque', value: 'eu' },
					{ name: 'Belarusian', value: 'be' },
					{ name: 'Bengali', value: 'bn' },
					{ name: 'Bosnian', value: 'bs' },
					{ name: 'Bulgarian', value: 'bg' },
					{ name: 'Burmese', value: 'my' },
					{ name: 'Catalan', value: 'ca' },
					{ name: 'Chinese (Hong Kong)', value: 'zh-hk' },
					{ name: 'Chinese (Simplified)', value: 'zh-cn' },
					{ name: 'Chinese (Traditional)', value: 'zh-tw' },
					{ name: 'Croatian', value: 'hr' },
					{ name: 'Czech', value: 'cs' },
					{ name: 'Danish', value: 'da' },
					{ name: 'Dutch', value: 'nl' },
					{ name: 'English', value: 'en' },
					{ name: 'English (India)', value: 'en-in' },
					{ name: 'English (UK)', value: 'en-gb' },
					{ name: 'Estonian', value: 'et' },
					{ name: 'Filipino', value: 'fil' },
					{ name: 'Finnish', value: 'fi' },
					{ name: 'French', value: 'fr' },
					{ name: 'French (Canada)', value: 'fr-ca' },
					{ name: 'Galician', value: 'gl' },
					{ name: 'Georgian', value: 'ka' },
					{ name: 'German', value: 'de' },
					{ name: 'Greek', value: 'el' },
					{ name: 'Gujarati', value: 'gu' },
					{ name: 'Hebrew', value: 'iw' },
					{ name: 'Hindi', value: 'hi' },
					{ name: 'Hungarian', value: 'hu' },
					{ name: 'Icelandic', value: 'is' },
					{ name: 'Indonesian', value: 'id' },
					{ name: 'Italian', value: 'it' },
					{ name: 'Japanese', value: 'ja' },
					{ name: 'Kannada', value: 'kn' },
					{ name: 'Kazakh', value: 'kk' },
					{ name: 'Khmer', value: 'km' },
					{ name: 'Korean', value: 'ko' },
					{ name: 'Kyrgyz', value: 'ky' },
					{ name: 'Lao', value: 'lo' },
					{ name: 'Latvian', value: 'lv' },
					{ name: 'Lithuanian', value: 'lt' },
					{ name: 'Macedonian', value: 'mk' },
					{ name: 'Malay', value: 'ms' },
					{ name: 'Malayalam', value: 'ml' },
					{ name: 'Marathi', value: 'mr' },
					{ name: 'Mongolian', value: 'mn' },
					{ name: 'Nepali', value: 'ne' },
					{ name: 'Norwegian', value: 'no' },
					{ name: 'Odia', value: 'or' },
					{ name: 'Pashto', value: 'pa' },
					{ name: 'Persian', value: 'fa' },
					{ name: 'Polish', value: 'pl' },
					{ name: 'Portuguese', value: 'pt' },
					{ name: 'Portuguese (Portugal)', value: 'pt-pt' },
					{ name: 'Romanian', value: 'ro' },
					{ name: 'Russian', value: 'ru' },
					{ name: 'Serbian', value: 'sr' },
					{ name: 'Serbian (Latin)', value: 'sr-latn' },
					{ name: 'Sinhala', value: 'si' },
					{ name: 'Slovak', value: 'sk' },
					{ name: 'Slovenian', value: 'sl' },
					{ name: 'Spanish', value: 'es' },
					{ name: 'Spanish (Latin America)', value: 'es-419' },
					{ name: 'Spanish (US)', value: 'es-us' },
					{ name: 'Swahili', value: 'sw' },
					{ name: 'Swedish', value: 'sv' },
					{ name: 'Tamil', value: 'ta' },
					{ name: 'Telugu', value: 'te' },
					{ name: 'Thai', value: 'th' },
					{ name: 'Turkish', value: 'tr' },
					{ name: 'Ukrainian', value: 'uk' },
					{ name: 'Urdu', value: 'ur' },
					{ name: 'Uzbek', value: 'uz' },
					{ name: 'Vietnamese', value: 'vi' },
					{ name: 'Zulu', value: 'zu' },
				],
				routing: {
					request: {
						qs: {
							hl: '={{$value}}',
						},
					},
				},
			},
			{
				displayName: 'Filter Token',
				name: 'sp',
				type: 'string',
				default: '',
				description: 'Filters and pagination token for YouTube search results',
				options: [],
				routing: {
					request: {
						qs: {
							sp: '={{$value}}',
						},
					},
				},
			},
		],
		displayOptions,
	},
];

export const youtube = {
	resource,
	properties,
};